### ISSUE TITLE
frame:false , maximize() will be enter fullscreen!!!

### ISSUE THREAD

**Issue by aliencode** [nwjs/nw.js#1021]
```json
{
  "main": "index.html",
  "name": "nw-demo",
  "description": "demo app of node-webkit",
  "version": "1.0",
  "window": {
    "title": "node-webkit demo",
    "toolbar": false,
    "frame": false,
    "show": true,
    "fullscreen": false,
    "width": 1000,
    "height": 600,
    "position": "center",
    "min_width": 1000,
    "min_height": 600
  }
}
```

```javascript
require('nw.gui').Window.get().maximize();
```

Window not maximize, it enter the fullscreen !!

**Comment by adam-lynch** [comment]
I still see this in 0.11.5. The app goes over / under the taskbar on Windows.

**Comment by Gimmeaphatbeat** [comment]
Not for me, it works fine now, Windows 8.1.

**Comment by adam-lynch** [comment]
@Gimmeaphatbeat weird, I'm on Windows 8.1 too.

**Comment by Gimmeaphatbeat** [comment]
@adam-lynch I used the 64-bit Node-webkit if that matters.

**Comment by adam-lynch** [comment]
@Gimmeaphatbeat seems to happen with both for me.

**Comment by Gimmeaphatbeat** [comment]
This problem has come back for me in 0.12.0

**Comment by rogerwang** [comment]
@jtg-gg  could you please check this. Looks like related to the window style.

**Comment by jtg-gg** [comment]
@rogerwang ok I am looking into it

**Comment by JanPeter** [comment]
This seems still to be a problem, when I'm on Windows 8.1 frame set to false and resizable set to false. I'm using version v0.12.0-alpha3

**Comment by EladBezalel** [comment]
:+1:

**Comment by RobertJGabriel** [comment]
I had a problem the same problem with it being hidden behind / going in front of the taskbar and double clicking on the draggable-area when maximised wouldn't restore back to normal.
It seemed to be caused by the `resizable: false` in the manifest. Removing that and using `gui.Window.get().setResizable(false)` on load is a fix.

A knock on effect is that the double clicking on a draggable area will maximum the window, even if setResizable is set to `false`, but that's probably a separate issue.

Hope this helps.

**Comment by baconface** [comment]
I am having this issue with 0.12.1.

No frame and maximize exposes part of window frame in taskbar on a little bit on the second monitor on Windows 8.1.
