### ISSUE TITLE
[osx] Strange functioning zoom button in certain circumstances

### ISSUE THREAD

**Issue by szwacz** [nwjs/nw.js#1105]
To reproduce the problem use this snippet:
```html
<!DOCTYPE html>
<html>
<body>
<script>

var gui = require('nw.gui');
var win = gui.Window.get();

win.on('maximize', function () {
	console.log('maximize');
});

win.on('unmaximize', function () {
	console.log('unmaximize');
});

// this line, used before win.maximize() is the culprit, 
// comment it and problem disappears
win.moveTo(0, 0);

win.maximize();

</script>
</body>
</html>
```
Run this app, it will maximize at the startup.
Now try to click few times on green zoom button.
In console you should see that with every click 'maximize' event was fired (but we are already maximized), and 'unmaximize' event didn't occur.

I've stumbled upon this issue while working on "ultimate" window state storing.

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.
