### ISSUE TITLE
after use the app protocol, can't use relative path to run the app

### ISSUE THREAD

**Issue by yanxyz** [nwjs/nw.js#1117]
Here is a test:

nw 0.7.3/win7

    e:\test\1
           |-- app\
           |     |-- package.json
           |     |-- index.html
           |-- test\

package.json:

```json
{
  "name": "test",
  "main": "app://test/index.html",
  "window": {
    "toolbar": true,
    "width": 660,
    "height": 500
  }
}
```
index.html:

```html
<h1>App protocol</h1>
```

run app 

```cmd
REM under dir 'test'
e:\test\1\test>f:\nw\nw.exe ..\app
REM failed to load index.html

e:\test\1\test>f:\nw\nw.exe e:\test\1\app
REM ok

REM under dir '1'
e:\test\1\test>cd ..
e:\test\1>f:\nw\nw.exe app
REM ok
```
If this is not a problem, then I think the [wiki](https://github.com/rogerwang/node-webkit/wiki/App-protocol) should point this out.

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.
