### ISSUE TITLE
Showing tray icon menu with a menuItem belong to two Menus

### ISSUE THREAD

**Issue by nebulade** [nwjs/nw.js#1181]
Hi,

the following code snippet makes nw crash on linux:

```
var gui = require('nw.gui');
var tray, menuItem, menu1, menu2;

tray = new gui.Tray({ title: 'Tray', icon: 'img/icon.png' });

menu1 = new gui.Menu();
menu2 = new gui.Menu();

menuItem = new gui.MenuItem({ type: 'normal', label: 'Quit' });
menuItem.click = function () { process.exit(0); };

menu1.append(menuItem); // <- add the same menuItem to two menus
menu2.append(menuItem); // <- the order matters for below statements

// tray.menu = menu1;   // <- showing menu1 works fine
tray.menu = menu2;   // <- showing menu2 makes the app crash
```

The reason seems to be that the ```menuItem``` is used in both menus, but if the menu where the menuItem was added last is shown, nw crashes. Showing the first menu where it was added, works fine.

Maybe this is actually wrong usage?

The error is a GTK assert:
```
[5846:1007/081256:ERROR:browser_main_loop.cc(212)] Gtk: Can't set a parent on widget which has a parent

**
Gtk:ERROR:gtkcontainer.c:2743:IA__gtk_container_propagate_expose: assertion failed: (child->parent == GTK_WIDGET (container))
```

Writing that, it might even not be too related to the tray icon menu, but any other menu. Let me know if you need more details on that.

Thanks,
Johannes

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.
