### ISSUE TITLE
Mac menu merging creates duplicate menus

### ISSUE THREAD

**Issue by erikjjohnson** [nwjs/nw.js#1190]
I found several other issues reported regarding the merging of native menus in Mac.  E.g., #506) and some discussion about how this can be done by recompiling node-webkit.  I'm semi-reopening this issue in hopes that we can get a javascript interface to merging mac menu items.  Let me give a concrete example to reproduce the problem.  This code attempts to add the normal "zoom" item to the Mac Window menu:

nw: 0.7.5
Mac: 10.8.5

Add this code to index.html (or where ever in the app's startup):

function buildMacWindowMenu(nwGui) {
  var menu = new nwGui.MenuItem({label: 'Window'});
  menu.submenu = new nwGui.Menu();
  var menuItem = new nwGui.MenuItem({label: 'Zoom'});
  menuItem.click = function () {
    nwGui.Window.get().maximize();
  }
  menu.submenu.append(menuItem);
}

var nwGui = require('nw.gui');
var menubar = new nwGui.Menu({type: 'menubar'});
menubar.append(buildMacWindowMenu(nwGui));
nwGui.Window.get().menu = menubar;

The result is two Window menus on mac.  The documented "merge" with the system menus does not occur.

I also tried to first read nwGui.Window.get().menu to see if I could find the existing Window menu and muck with it, but that menu comes back as undefined.

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.
