### ISSUE TITLE
getProxyforURL doesn't seem to work on Ubuntu 13

### ISSUE THREAD

**Issue by ampgcat** [nwjs/nw.js#1191]
Hi.
Our code calls getProxyforURL. THe following is our situation.
For non-root users, this works perfectly.
For 'root', 
on 32-bit Ubuntu 12, if I set the manual proxies in "System Setting" , getProxyforURL correctly returning the PROXY. However, doing the same on Ubuntu 13 does not. It's still returned as DIRECT. I am currently trying to install another Ubuntu 13 to see if this problem is machine-specific, but am reporting this for the time being.

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.
