### ISSUE TITLE
High-DPI support

### ISSUE THREAD

**Issue by ghost** [nwjs/nw.js#1318]
Can I creating high dpi awareness applications without blur and etc. ?

**Comment by chrisJohn404** [comment]
On a Microsoft Surface pro 3 running windows 8.1 with the latest build of nw.js this issue is back.  I don't have a high resolution mac to test with.  Windows are displayed properly in the 0.11.6 release that is running chromium 38.0 but in the 0.12.0-alpha2 release running chromium 41.0 the windows are fuzzy again.  

The program icon in the windows task-bar for the running application is pixelated and the windows are all slightly larger.  I am sure the status of this issue will continue to change as newer chromium versions are released as windows itself doesn't have the best high-dpi support and neither version has been perfect.

**Comment by agozie** [comment]
Same here, fuzzy window and pixelated program icon. Win 8 on MBP retina display.

**Comment by chrisJohn404** [comment]
It looks like there is an active issue here:
https://github.com/nwjs/nw.js/issues/2998
