### ISSUE TITLE
OSX kiosk keyboard input not working

### ISSUE THREAD

**Issue by jmorvan** [nwjs/nw.js#1440]
When starting in kiosk mode on OSX my keydown events are not fired. Is this a known behavior or I am missing something?
##

**Comment by arthurakay** [comment]
In case anyone is still curious, this problem still affects `nw.js` v0.12.3 -- nearly two full years after this issue was opened.

I see @alexsmith540's comment about this being a more widespread problem with browser fullscreen APIs -- but is there any hope in getting this bug fixed in 0.13.x? Seems like a pretty nasty bug IMO to avoid fixing.

**Comment by alexsmith540** [comment]
@arthurakay my workaround was rather interesting. 
There are some low-level calls you can do via node on either windows or mac to spawn your window to the XY/Width/Height of each individual screen. Then you just hide the URL bars/navigation in your window config object and (boom) keyboard functionality in a "fullscreen" window(s). Kind of an ugly hack but for my case it was actually more ideal.. Hope that helps.
