### ISSUE TITLE
Crash on laptop sleep and wake

### ISSUE THREAD

**Issue by sdog869** [nwjs/nw.js#1473]
When I put my laptop to sleep, Mac OS X 10.9.1, by closing the lid, when I re-opened it later I found my app had crash with the error:

Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)

Is there something I can do to handle this error? Thanks!

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.
