### ISSUE TITLE
Cannot extract package   Failed to unzip the package file: xxx.nw

### ISSUE THREAD

**Issue by Crisisyun** [nwjs/nw.js#1493]
After package

**Comment by AlexisCaffa** [comment]
In my case it is because the limit of 260 characters of route on win32

**Comment by mashaly100200** [comment]
put the path between double quotation like  this
 nw "D:\program files\............"

**Comment by rockedpanda** [comment]
Got the same problem, and fixed by checking all the filenames in folder. 
By doing testing on windows, found that:
1 all file name in normal characters, its ok
2 name with Chinese\Japanese characters will fail to unzip by nw

some test case here(in windows 8 & nwjs-v0.12.0-win-x64)
index.html + package.json    ................................ OK
index.html + package.json + ~.txt......................OK
index.html + package.json + ~~........................ OK
index.html + package.json +  ~~.~ .....................OK
index.html + package.json +  中文.txt ..............Failed
index.html + package.json +  Françai................OK
index.html + package.json +  日本語.txt............Failed

not test in linux yet.
