### ISSUE TITLE
setTimeout() is inaccurate when running in node context

### ISSUE THREAD

**Issue by pracucci** [nwjs/nw.js#1504]
I just noticed that the setTimeout() is very inaccurate when running in node context, compared to setTimeout() running in webkit context or node standalone. I attached a simple test code, so that you can run on your system and check if you're able to reproduce it.

Node-webkit: **0.8.4**
Platform: **OS X 10.8.4**

#### File: test.js
*Put this file in the project root directory (the same directory that contains your main HTML file), then run the tests below.*
```js
module.exports = function() {
    setInterval(function() {
        console.time("test");
        setTimeout(function() { console.timeEnd("test"); }, 100);
    }, 500);
};
```

#### Running in node standalone
$ node -i
require('./test.js')();
test: 101ms
test: 101ms
test: 101ms
test: 101ms
test: 101ms
test: 100ms
test: 101ms
[...]

#### Running in node-webkit
*In the web dev console type:*
require('./test.js')();

*and get the output:*
test: 135.196ms
test: 299.880ms
test: 200.426ms
test: 299.351ms
test: 100.528ms
test: 299.373ms
test: 101.123ms
test: 203.213ms
[...]

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.
