### ISSUE TITLE
Support to Socket.IO?

### ISSUE THREAD

**Issue by ThePokyWizard** [nwjs/nw.js#1543]
Hi, i need create a desktop app to chat, but, my server are in the OpenShift and need Socket.IO to receive and send messages.
The node-webkit support use a script hosted in webhost (in case. socket.io.js)?

**Comment by faytom** [comment]
just found out this link:http://habrahabr.ru/post/181670/ is quite useful when making a server and client pack together in node webkit. I just got it working on my own example.

**Comment by khellste** [comment]
I'll leave this here in case it might help anyone else.  It's sort of related to this thread.

I was having an issue with Socket.IO in nwjs where all calls to `io.connect("my-server:8080")` were trying to connect to `file://socket.io` instead of `http://my-server:8080/socket.io`.  This was due to the fact that, in the absence of an explicit protocol, XHRs will try to connect using the protocol of the current page, which was `file://index.html` in my case.  Adding an explicit protocol, *e.g.*, `io.connect("http://my-server:8080")`, resolved the issue.

**Comment by andredelgado** [comment]
https://scotch.io/tutorials/a-realtime-room-chat-app-using-node-webkit-socket-io-and-mean

**Comment by aggregate1166877** [comment]
> It would make sense that you will have a socket.io server running independently from node-webkit

Not if you want the GUI application itself to be a server, such as in the case of video games (especially on Windows).
