### ISSUE TITLE
0.9.1 much worse video playback  comparing to 0.7.5

### ISSUE THREAD

**Issue by xdenser** [nwjs/nw.js#1559]
I have not yet isolated cause. 
My application intensivelly uses video elements - up to 12 not overlapping frameless windows on multichannel desktop and 1-5 video elements per window. As for 0.7.5 everything is smooth.
With 0.9.1 videos stall, sometimes even do not start.
And this is patched with ffmpegsumo.dll  from Crome 32.0.1700.107 and video is mp4

Trying to isolate issue I have started just single window, with single video and what I see:
0.7.5 tryes to download whole video asap(yet not on full speed)
0.9.1 pauses download or download is slower so video stalls even on local server
in Chrome 32 everything is ok

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.
