### ISSUE TITLE
Node Webkit is sending invalid Accept-Language Http Header

### ISSUE THREAD

**Issue by nvhoanganh** [nwjs/nw.js#1563]
Hi @rogerwang,

This is related to issue number https://github.com/rogerwang/node-webkit/issues/1240.  My computer is set to Dutch, when I use Chrome or IE, the Accept-Language Http Header is set correctly to nl-NL. However, when I use Node Webkit, the value is da-DK.

**Here is the Http Header for Chrome:**
Accept-Encoding: gzip,deflate
GET / HTTP/1.1

Host: 10.5.250.148

Connection: keep-alive

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0
.8

User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/32.0.1700.107 Safari/537.36

Accept-Encoding: gzip,deflate,sdch

Accept-Language: nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4

**Here is the Http Header for IE8:**
Accept-Encoding: gzip,deflate
GET / HTTP/1.1

Accept: application/x-ms-application, image/jpeg, application/xaml+xml, image/gi
f, image/pjpeg, application/x-ms-xbap, */*

Accept-Language: nl

User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.
0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Cent
er PC 6.0)

Accept-Encoding: gzip, deflate

Host: 10.5.250.148

Connection: Keep-Alive

**Here is the Http Header for Node Webkit (v0.8.4):**
Accept-Encoding: gzip,deflate
GET /?node=1&nodeport=2929&minimize=false HTTP/1.1

Host: 10.5.250.148

Connection: keep-alive

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0
.8

User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/30.0.1599.66 Safari/537.36

Accept-Encoding: gzip,deflate

Accept-Language: da-DK,en-us;q=0.8,en;q=0.6

Please help.

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.
