### ISSUE TITLE
Error when trying to call Web Audio API

### ISSUE THREAD

**Issue by deadprogram** [nwjs/nw.js#1584]
I was attempting to make calls using the Web Audio API, and received the following error:

```
[15126:0217/135908:ERROR:audio_manager_base.cc(422)] Not implemented reached in virtual std::string media::AudioManagerBase::GetDefaultOutputDeviceID()
```

Has anyone else tried to use this?

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.
