### ISSUE TITLE
[linux-x64] 0.9.2 Just hit the snapshot size limit.

### ISSUE THREAD

**Issue by miklschmidt** [nwjs/nw.js#1649]
```
Error: Command failed: partial snapshot spaces: 0 139016 712 0 12744 0
startup snapshot spaces: 0 1104888 461496 1183168 6120 41936
Error: Allocation in space 1 is 1104888: bigger than 1031936
Error: Allocation in space 3 is 1183168: bigger than 1019904
```

This is without third party code (bare minimum that i have to protect).

This is not a problem on ia32 platforms. @rogerwang is it possible to raise the size limit?

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.
