### ISSUE TITLE
Save File Dialog -> doesn't display list of file types correctly

### ISSUE THREAD

**Issue by CodeTrol** [nwjs/nw.js#1671]
I use this html code in order to call:
 <input type="file" saveas="noname" accept=".jpg" />

which is displaying file type list as expected:
1. *.jpg
2. All Files.

But when I use multiple formats like this:
<input type="file" saveas="noname" accept=".jpg,.png,.tga" />
I'm getting strange result (on different OSs).
Windows displays this:
1. Custom files (:how to solve this?)
2. All files.
Linux:
1. unknown (:how to remove this?), Image JPEG, Image PNG, Image TGA.
2. unknown (:how to remove this?)
3. Image JPEG
4. Image PNG
5. Image TGA
MacOS: I don't have any of them...

Is there any way to specify my own filter like "*.jpg|Image JPEG/*.png|Image PNG/*.tex|My own image format/*.*|All Types" in order to display list like this:
[Description]
1. Image JPEG
2. Image PNG
3. My own Image format
4. All Types
[extension]
1. *.jpg
2. *.png
3. *.tex
4. *.*

???

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.
