### ISSUE TITLE
HTML5 Audio element crashed after witching pause and play

### ISSUE THREAD

**Issue by dennislaupman** [nwjs/nw.js#1679]
I'm using the HTML5 audio Element wiith an ogg audio file. On OSX 10.9.2. After switching from play to pause and visaversa a several times in a row, the audio element crashed.

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.
