### ISSUE TITLE
FreeBSD binaries

### ISSUE THREAD

**Issue by claudiozz** [nwjs/nw.js#1747]
Would it be possible to have FreeBSD binaries ? 
##

**Comment by riatzukiza** [comment]
I haven't found any FreeBSD binaries, but FreeBSD does have a linux compatability layer
so my question instead, assuming that native binaries will never happen, is:
How can I run NW.js with a linux compatability layer on FreeBSD?

**Comment by jaredallard** [comment]
+1 on this!

**Comment by TheDharc** [comment]
they are ignoring us completely

**Comment by jaredallard** [comment]
@TheDharc It's most likely possible. If I find myself some free time over my winter break (19 Dec-7th of Jan) I'll try to compile this on FreeBSD, since chromium can run on it.

I wouldn't be offended by the lack of response. @rogerwang is incredibly busy, and as a maintainer of a pretty big project myself, I understand how issues can be lost in the flood of issues & etc.

**Comment by jeezs** [comment]
Thanks a lot!!!

**Comment by vyal** [comment]
@jaredallard Did you get a chance to try building it on FreeBSD?

**Comment by faust64** [comment]
Answering to @riatzukiza : the linux compatibility layer of FreeBSD could be used running nw.js apps, although you're very likely to be missing libraries.
Currently, only linux32 binaries seems to be recognized (10.3-RELEASE).
I was able to install nw-builder, generate my app. Running the produced binary, it fails loading `libgconf-2.so.4`. We're missing some `linux-(c6|f10)-gconf` port. Probably among others.

**Comment by yonas** [comment]
@faust64 Just a heads up, FreeBSD 11 has support for 64-bit linux.
