### ISSUE TITLE
CDT highlights the wrong window

### ISSUE THREAD

**Issue by oldgeeksguide** [nwjs/nw.js#1753]
When using the debugger (CDT), if you hover over an element it highlights it in the browser window.  I notice that sometimes in node-webkit, with multiple windows, the highlighting will happen in the wrong window.  I've noticed this at least with versions 0.8 and 0.9, though it may be older than that.  I can definitely reproduce with 0.9.2 and 0.8.5.

To reproduce, just open `node-webkit` (you don't need an argument, just using the default blank page is sufficient).  Then open up CDT by clicking on the gear icon and run the following commands:

    g = require('nw.gui')
    w = g.Window.open('http://google.com')
    w.window.document

Now you should see the expandable element representing the document.  If you expand it you can see that it represents the google home page, and if you examine `w.window.location.href` it points to google.com, but if you hover over it, or any elements within it, the highlighting will occur on the original window with the blank page.

What should happen is that it highlights the corresponding sections of the second window, open to google's home page.

I've seen this problem on a Mac running OSX 10.9.2, I haven't tried it on other systems, so I don't know if it's unique to the Mac.

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.
