### ISSUE TITLE
mp4 requests slower than in chrome or other browsers (keep-alive header issue?)

### ISSUE THREAD

**Issue by mjs2020** [nwjs/nw.js#1784]
Hi,
I'm building an app with popcornjs which uses HTML5 video. I've included a ffmpegsumo.dll taken from Google Chrome to be able to decode h264. The application runs in a company intranet and videos are available on an internal NAS server. I'm facing some slowness issues in the requests especially compared to other browsers, IE11 included (!). Network conditions are the same as well as the code. However when I inspect the request headers all other browsers have a:
Connection: keep-alive
header when requesting the mp4 file but NW doesn't and I'm wondering why. Considering that the request for the file comes from an HTML5 video tag and is not a XHR request is there a way I can force NW to use that header?
Or could the problem be elsewhere?
Thanks!

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.
