### ISSUE TITLE
Multi-monitor setup broken on Ubuntu?

### ISSUE THREAD

**Issue by mgcrea** [nwjs/nw.js#1829]
I'm trying to make node-webkit work accross multiple monitors on Ubuntu 14.04. So far I can't make it work, kiosk will fullscreen on one monitor, setting the resolution in the `package.json` (eg. `{width: 1080, height: 5760`) does seem to produce a bigger window, but it is not rendered on other screens.

If I start `nw` alone and resize the window manually, I can render it on the 3 screens.
##

**Comment by S-unya** [comment]
Hi, @mgcrea, which version of NWjs are you using? I have a related Issue with 0.13.0-Beta2 rather than 0.12.*. If you are using 0.12.*, perhaps my "fix" would work for you? In OSX there is a setting in "Mission Control" called "Displays have separate spaces" that allows each screen to have multiple virtual spaces. Unfortunately that causes fullScreen apps to become unable to stretch across screens. IIRC Ubuntu has a similar feature.

The interesting thing that I discovered is that KioskMode will go fullScreen and still be able to have width, height and offset manipulated. The key is to set kiosk mode first and then set the rest. I hope that helps you - I have this gist if you want to see a little more (https://gist.github.com/S-unya/898e9e66bd0cde9d4621)

Unfortunately - *back to my issue* - 0.13.0 now sets the app to enter fullScreen when it enters kioskMode where 0.12.* did not (even though the display was often fullscreen). The essential problem is that fullScreen snaps the application to only one screen which makes it impossible on OSX to span multiple screens. The question is - is it necessary to enter fullscreen when entering kioskMode because this limits the flexibility, at least on OSX?

**Comment by S-unya** [comment]
@mgcrea have you seen this? http://superuser.com/questions/862891/on-ubuntu-maximize-a-window-over-two-screens

**Comment by mgcrea** [comment]
@S-unya I haven't been using node-webkit for a while, we're using electron now. Good luck with your issue.
