### ISSUE TITLE
Iframe memory issue

### ISSUE THREAD

**Issue by raviraj555** [nwjs/nw.js#1931]
Hi, 
In application I m using  iframe load and unload which is increasing memory  usage and it never get free even after refreshing page (pro-grammatically), memory remain same and never goes down. i m using v0.9.2 node-webkit and application is running on win 7 64bit.
but same application if i run directly in browser it work fine the memory goes up as iframe load and goes down as soon as it's removed.
above case hangs exe if it reaches 900mbs.
please help

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.
