### ISSUE TITLE
OSX translucency

### ISSUE THREAD

**Issue by timuric** [nwjs/nw.js#1933]
Since apple unveiled today new OSX look, would there be any plans to introduce transparency+blur support? Or that would not be possible in the near future? 
##

**Comment by matthew-dean** [comment]
> I assume having transparency is enough, since blur is already available as -webkit-filter: blur()

@timuric I doubt it. That will only apply the blur to elements rendered by the browser. The OS layer is not rendered by the browser so it wouldn't be blurred by that. In addition, it would need to be a background filter, not a blur of the element in order to get that effect. See: http://caniuse.com/#feat=css-backdrop-filter
