### ISSUE TITLE
[win] node native module doesn't work with renamed exe (was node-sqlite3 module don't work in node-webkit package mode)

### ISSUE THREAD

**Issue by bicio** [nwjs/nw.js#199]
I've a problem with node-webkit v0.3.4 and node-sqlite3 module.
So, if I run my app with command nw C:\apps\packagedapp.nw my application work fine,
but if I create a package by command copy /b nw.exe+app.nw app.exe and launch it, my application crash whit error : Uncaught error: no error myPAth/node_sqlite3.node.

someone could help me
thanks

**Comment by adam-lynch** [comment]
Does this problem still exist?

**Comment by zsxsoft** [comment]
Wow, a 3-years bug!

**Comment by LiamKarlMitchell** [comment]
Can't we just get the program name at run-time and pass it to the module after its loaded if it is really required?

---

In Example:
OllyDBG and IDA Pro plugins have it so the plugin will have a method exposed which will pass over anything required including version numbers to check if the plugin was compiled for that version of the plugin api.

So for win32 targets just expose a hidden function like __nwmodule_init and give it the runtime information required. It should reply with the version of node webkit/ application binary interface it was compiled for then node webkit even if it is renamed could say yes or no to the module loading.

Or am I misunderstanding the complexity of this issue?
I may give it a go if this is still a problem.

**Comment by etx** [comment]
This bug is really bumming me out.

**Comment by rogerwang** [comment]
In NW13 we are splitting the code as Chrome does on windows: ship `nw.exe` and `nw.dll`. Thire party modules will be linking with `nw.dll`. Then the renaming of nw.exe won't break it.

**Comment by baconface** [comment]
Sounds awesome. Just curious, how much in a decrease in size can we expect for the nw.exe binary?

**Comment by LiamKarlMitchell** [comment]
that is a good idea if the same version is used on a system it will get around duplication of core functionality.

Just a thought, rather than copying the nw exe each time, it may be possible to make a shell extension/registry key on windows (i am not sure about other systems) to register a file extension that would run nw.exe on the directory or package / package.json chosen.

Similar to how java has jar files that can be opened in javaw by double clicking.
Is this something that has been considered or already done i must read more.

If a particular version of nw is required the package.json could say so and some sort of loader could load that core functionality to handle the process.

**Comment by etx** [comment]
Great to hear Roger! Thanks for your hard work.

**Comment by ArielBadichi** [comment]
Until we get nw.dll, maybe this can help: [NW.js with a custom executable name and native modules](http://developers.ironsrc.com/rename-import-dll/).

**Comment by morgondag** [comment]
@ArielBadichi nice! will test it out!

**Comment by githubuserxj** [comment]
@SingKo 
how to rebuild nw with ninja.
Can you give us a more detailed step by step ?
thanks.

**Comment by doruchiulan** [comment]
for me it doesnt work even if I rename the resulting exe from nw-builder to nw.exe. If I put my app files in the folder where original nw lives it works.

I am using leveldown in my app.

**Comment by asinbow** [comment]
The killer solution seems to provide a PE manipulating tool to modify import table.
[portable-executable-library](https://code.google.com/p/portable-executable-library/) looks great.
Since it supports:
* Read 32- and 64-bit PE files (PE, PE+) for Windows, work similar with both formats
* Read and write imports
I will spent some time on it.

**Comment by angufix** [comment]
Just renamed the nw.js to myapp.exe and run the exe file, the sqlite3(native module) can't handle it. Error log:

[8480:1215/172020:ERROR:gpu_child_thread.cc(146)] Exiting GPU process due to errors during initialization
[9188:1215/172020:ERROR:nw_shell.cc(335)] Error: The specified module could not be found.
C:\myapp\node_modules\sqlite3\lib\binding\node-webkit-v0.12.2-win32-ia32\node_sqlite3.node
    at Error (native)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at Object.<anonymous> (C:\myapp\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:451:26)
    at Object.Module._extensions..js (module.js:469:10)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
[9188:1215/172020:INFO:CONSOLE(346)] "Uncaught Error: The specified module could not be found.
C:\myapp\node_modules\sqlite3\lib\binding\node-webkit-v0.12.2-win32-ia32\node_sqlite3.node", source: module.js (346)

**Comment by asinbow** [comment]
@angufix Windows reports a `dll` module not found if any of its dependency not found. Your `node_sqlite3.node` depends on `nw.exe`, so it will fail when you renamed `nw.exe`. You can see my sample code [nw-addon-demo](https://github.com/asinbow/nw-addon-demo). There is a utility tool:
```
rename_import_lib\rename_import_lib.exe -i <path-to-node> [-o <path-to-output>] -r nw.exe <your-new-exe-name>
#
rename_import_lib\rename_import_lib.exe -i node_sqlite3.node -r nw.exe myapp.exe
```

**Comment by rogerwang** [comment]
This is supported in 0.13 now. Native modules depends on node.dll and nw.dll. And you can control the dependency. See more information here: https://groups.google.com/d/msg/nwjs-general/UqEq8ito2gI/W-ld9LSoDQAJ

**Comment by wozzup** [comment]
@rogerwang  not work with https://github.com/tojocky/node-printer

**Comment by dannatofrenk** [comment]
Hello guys, sorry to write on this old thread, but nw-gyp  is too much for me, I'm left with no developers and trying to build myself is no use. According to the developers our application requires 
nw-gyp 0.12.3 
sqlite3 is built succesfully but seems misplaced in windows builds:
the usual:

Uncaught Error: Cannot find module 'C:\Users\F6FAA~1.CHI\AppData\Local\Temp\nw3056_13763\node_modules\sqlite3\lib\binding\node-webkit-v0.12.3-win32-x64\node_sqlite3.node'


 The app has been previously built successfully on linux 64 and working correcly.

After days of trying on a very steep learning curve, I'm here to ask to HIRE someone of you who would compile for windows please show up if available or give a few hints. 

the environment I used:
node 5.6.0
npm 3.6.0

nw-gyp 3.4.0
node-pre-gyp 0.6.30
OS windows 7 professional
VStudio 2013 

command I run in build folder after npm install; npm run build; cd build ; npm i :
npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=ia32 --target="0.12.3"

I tryed to rename myapp.exe to nw.exe but still the same error. 
Should I use rename_import lib? nwjs ? another version of nw-gyp ? 
I'm pretty out of ideas...
Thank you 
F
