### ISSUE TITLE
[mac] Custom menu item crashes the app after the main (first) window is closed

### ISSUE THREAD

**Issue by mrfabbri** [nwjs/nw.js#2005]
On a Mac (node-webkit master/v0.10.0-RC1) if you define a menu with a custom menu item (with a click property) i.e.

```
var nw = require('nw.gui');
var nativeMenu = new nw.Menu({ type: 'menubar' });
nativeMenu.createMacBuiltin('node-webkit');
nativeMenu.items[0].submenu.append(
  new nw.MenuItem({
    label: 'Do Something',
    click: function () { alert('Doing something'); }
  })
);
```

when you click the menu item after closing the main (first) window (where the definition of the menu is) node-webkit crashes with a 

```
Unknown exception behavior: 0 
segmentation fault
```

See https://gist.github.com/mrfabbri/4b30c247ea147c0b1379 for a brief example (minimal node-webkit ap:p package.json+index.html).

I believe this is due to reference to the click handler function in the disposed context of the closed window. 

A workaround, as shown in the example above, is to hide and not to close the main window (so the context remain accessible), given the peculiarity of the Mac OS X platform regarding window management this could translate in general advice.
##

**Comment by thomaswrenn** [comment]
I believe I'm seeing the same issue but just on Windows, not Mac OS X. App crashes when a menu on the main window is .popup()'d after a second window is opened and then closed. (Also, while the second window is opened and the menu is .popup()'d with coordinates calculated relative to the main window, the popup menu appears at the 'top left corner of second window' + 'coordinates' position instead of 'top left corner of main window' + 'coordinates' position.
