### ISSUE TITLE
(NPAPI)Couldn't load plug-in

### ISSUE THREAD

**Issue by richcat1982** [nwjs/nw.js#2193]
Hi

I'm now haveing a problem to load a NAPAI in node-webkit V0.10
The strange thing is that the plug-in could be loaded and works well on some PCs, while fail on some others.
All the PCs have the same OS (Win7, 32bit, With Service Pack1)
I wonder how I can check this problem, any advice?
Thanks :-)
##

**Comment by KingRial** [comment]
The question is pretty old but I'd like to share my experience on this:

I had the same problem on PCs with Windows 64bit. It was caused by the difference  between the compiled nw.js iand the plugin.

For example:
if you use a VLC plugin 32bit you need to use a nw.js compiled for a 32bit machine. Otherwise it won't work and will show that error.
