### ISSUE TITLE
Embedding YouTube video.

### ISSUE THREAD

**Issue by vlakarados** [nwjs/nw.js#2291]
I have difficulties playing an embedded video, the error I get is `An error occurred, please try again later.`. This error is shown after clicking the "play" button on the video. One more thing is that the video background (the preview image) is completely black too.

Here's the console log:

	[28334:0903/093637:INFO:CONSOLE(0)] "XMLHttpRequest cannot load chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js. Cross origin requests are only supported for HTTP.", source: https://www.youtube.com/embed/undefined?html5=0 (0)
	[28334:0903/093637:INFO:CONSOLE(0)] "XMLHttpRequest cannot load chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js. Cross origin requests are only supported for HTTP.", source: https://www.youtube.com/embed/undefined?html5=0 (0)
	[28334:0903/093637:INFO:CONSOLE(0)] "XMLHttpRequest cannot load chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js. Cross origin requests are only supported for HTTP.", source: https://www.youtube.com/embed/undefined?html5=0 (0)
	[28334:0903/093637:INFO:CONSOLE(0)] "XMLHttpRequest cannot load chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js. Cross origin requests are only supported for HTTP.", source: https://www.youtube.com/embed/undefined?html5=0 (0)
	[28334:0903/093637:INFO:CONSOLE(0)] "XMLHttpRequest cannot load chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js. Cross origin requests are only supported for HTTP.", source: https://www.youtube.com/embed/undefined?html5=0 (0)
	[28334:0903/093637:INFO:CONSOLE(184)] "Uncaught ReferenceError: chrome is not defined", source: https://s.ytimg.com/yts/jsbin/www-embed-player-vflhH34Cp/www-embed-player.js (184)
	[28334:0903/093637:INFO:CONSOLE(140)] "Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js'.", source: https://s.ytimg.com/yts/jsbin/www-embed-player-vflhH34Cp/www-embed-player.js (140)

What is this `chrome-extension://.../cast_sender.js`? Is it the root of the problem?

Related question on SO: http://stackoverflow.com/questions/25622310/node-webkit-and-youtube-chrome-is-not-defined.

**Comment by moranm6** [comment]
@octalmage I tried the player API technique but it's not working for me. I used your exact example. It works fine in a browser, but doesn't even display the videos in my nwjs exe. 

When I embed the video in an object or iframe, the correct video appears, but I get an error when I actually try to play it.

Any ideas as to what might be going on here?

My stack question:
http://stackoverflow.com/questions/28972140/embedding-youtube-videos-not-working-with-node-webkit

**Comment by octalmage** [comment]
@moranm6 what version of nw.js are you using? Are there any errors in the JavaScript console?

**Comment by moranm6** [comment]
@octalmage Thanks for reaching out!

I'm using nwjs-v0.12.0-win-ia32.

No errors in console (just the loading log). Here's what I see with your code:  http://i.imgur.com/u4wiOil.png

As you can see, just the iframe video shows up, but I get an error when I click to play it.

Thanks again, let me know if you have any ideas!

**Comment by moranm6** [comment]
@octalmage  In what version of nw.js were you able to get this video to work? I'll try to replicate it.

**Comment by adam-lynch** [comment]
I can reproduce this too (on multiple Mac versions using NW.js 0.13.2), but it only happens for some videos. Embedding https://www.youtube.com/watch?v=cwXfv25xJUw is fine but https://www.youtube.com/watch?v=awVNGfmCQsg doesn't play. It seems to be the format/encoding of the video. Look at how the requests differ:

Success:

<img width="854" alt="screen shot 2016-03-29 at 17 53 59" src="https://cloud.githubusercontent.com/assets/1427241/14116372/4ce41ece-f5d7-11e5-86f2-0280362f0ff8.png">

There are a load of webm requests...

Fails:

<img width="924" alt="screen shot 2016-03-29 at 17 54 18" src="https://cloud.githubusercontent.com/assets/1427241/14116510/fb79e838-f5d7-11e5-80d1-d7df2d76891e.png">

Just one MP4 request.

So MP4s seem to fail. I've testing with a lot of different video formats/encoding (i.e. uploading videos to youtube and embedding them), including MP4, which worked. So it must be something about the video that I don't know about which is different to the ones I made.

I've tried adding this:

```json
"webkit": {
    "plugin": true
}
```

`ffmpegsumo.so` *is* there. I've tried passing these flags to Chromium with no luck:

```json
"chromium-args": "--enable-decoder=pcm_u8,pcm_s16le,pcm_s24le,pcm_s32le,pcm_f32le,pcm_s16be,pcm_s24be,pcm_mulaw,pcm_alaw,aac,h264,mp3,mpeg4 --enable-demuxer=ogg,matroska,wav,aac,mp3,mov,avi,vorbis --enable-parser=aac,h264,mpegaudio,opus,vorbis"
```

I have no plugins (Chromecast or otherwise) or anything weird like that, just regular NW.js.

---

There's a ZIP attached containing a simple `package.json` and `index.html` to reproduce.
[blah.zip](https://github.com/nwjs/nw.js/files/193868/blah.zip).

**Comment by adam-lynch** [comment]
Reopening after I tried embedding a 4 hour old YouTube video and saw this:

<img width="762" alt="screen shot 2016-07-30 at 21 07 38" src="https://cloud.githubusercontent.com/assets/1427241/17272863/c7d062b4-5699-11e6-97d2-50d961eb7a2e.png">

**Comment by ghostoy** [comment]
Could you send a minimal app to reproduce? Did you use original ffmpeg
provided by NW?

Adam Lynch <notifications@github.com>于2016年7月31日周日 04:08写道：

**Comment by adam-lynch** [comment]
@ghostoy that's the 0.16.0 SDK download from the site but I opened devtools and used the elements tab to stick in an youtube embed iframe (it's only reproducible with recently uploaded videos I think).

**Comment by frankhale** [comment]
@adam-lynch, @ghostoy: I've noticed this as well with some YouTube videos. I solved it by replacing the shipped ffmpeg with a more capable version. I typically replace ffmpeg with the one that ships with Electron and it solves the playback issues (like this one) that I've come across.

**Comment by adam-lynch** [comment]
@frankhale can you please describe what you do step by step? For Windows and OS X.

**Comment by frankhale** [comment]
I've noticed issues with YouTube playback just like what you described since my app is a YouTube player I am very sensitive to playback issues. What I do is very simple, I download the latest version of Electron and replace NW.js's ffmpeg.dll with the one from Electron. This has solved the problem (just as you described above in your screenshot) for me.

**Comment by adam-lynch** [comment]
@frankhale but the dll will only fix it for Windows right? I've noticed it being worse for our OS X app.

**Comment by frankhale** [comment]
I've never tried it for other OSes so I am not sure.

**Comment by adam-lynch** [comment]
@frankhale ok thanks. @ghostoy Is there an equivalent of that for Mac that you know of?

**Comment by ghostoy** [comment]
@adam-lynch Could you send out a link that we can reproduce?

If it's ffmpeg issue, you can download prebuilt [ffmpeg for all nw.js releases from community](https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases). See http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/#get-ffmpeg-binaries-from-the-community for more details.

**Comment by adam-lynch** [comment]
@ghostoy https://www.youtube.com/watch?v=GoEk7Uu8a2M for example, but I think it's only videos recently uploaded to YouTube so that might work fine by the time you try it.

I didn't know that existed, thanks. My understanding of this is limited though. NW.js comes with ffmpeg right? So why do I need to download it? 😃

**Comment by frankhale** [comment]
@adam-lynch The ffmpeg that NW.js ships does not include proprietary codecs. There are various prebuilt ones out there that you can replace the one that ships with NW.js. I always replace the one from NW.js because it simply cannot play all YouTube videos.

**Comment by frankhale** [comment]
I'm going to test that video you linked in just a few minutes

**Comment by frankhale** [comment]
That video works for me in my NW.js app. I've replaced the ffmpeg that ships with NW.js with the one that ships with Electron. That scenario I know works on Windows so I don't know if it'll *just* work on Linux or Mac.

There are other builds out there for ffmpeg. Googling reveals quite a lot of results.

**Comment by ghostoy** [comment]
@adam-lynch The builtin ffmpeg only contains royalty free codecs. See http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/ for the list of supported codecs in builtin ffmpeg. We couldn't ship ffmpeg with proprietary codecs due to legal issues. So you have to get ffmpeg libraries from community or build yourself if you are eligible to use them in your app.

**Comment by ghostoy** [comment]
See [Enable Proprietary Codecs](http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/) for latest instructions for NW.js 0.13.0 or later.

**Comment by Yonezpt** [comment]
Just to clarify things for further reading, YouTube has multiple streams in different formats. One of those formats is MP4 which is most of the times the default format selected by the player itself. Since NWJS does not come with proprietary codecs enabled (MP4 being one) lots of YouTube videos will simply fail to play. The few videos that do play have their default video format selected to one that does not need proprietary codecs, WEBM format for example.

This was previously discussed here: https://github.com/nwjs/nw.js/issues/4561

**Comment by adam-lynch** [comment]
Forgot to say thanks @ghostoy 👍
