### ISSUE TITLE
Allow turning on / off frame after app / window is open

### ISSUE THREAD

**Issue by adam-lynch** [nwjs/nw.js#2390]
See #2387. 

Since the experience is different per platform (i.e. fine on Windows), then a user might use the native frame on Mac and a custom HTML frame / controls on other platforms ( at least until #2389 is there with enough flexibility).  That would mean that the user would have to build the app more than once (with [node-webkit-builder](https://github.com/mllrsohn/node-webkit-builder), etc.) because the app's [manifest](https://github.com/rogerwang/node-webkit/issues/2389) would be different.

Therefore, we should be able to toggle the frame on the app / a window, at any point.
##

**Comment by 1j01** [comment]
:+1: and I don't plan on building my app any time soon, and just distributing it through npm, as it's a somewhat [npm-focused app](https://github.com/1j01/project-nexus) anyways. So separate builds is not a solution for me.
What I've done in absence of the ability to toggle the frame on the fly is relaunch the window on startup, unless it's already frameless, with options from the `package.json` and options overridden to turn off the frame. I can't directly check whether the window has a frame or not because there's no API for that but luckily I also wanted to toggle transparency along with the frame, so I was able to use that as a check for whether it's been relaunched already.
It's a bit more complicated than it ought to be :smile:
