### ISSUE TITLE
Run node-webkit behind all other apps (or as dockapp in openbox).

### ISSUE THREAD

**Issue by flynnham** [nwjs/nw.js#2397]
I have made a simple UI app that allows a minimal interface with the system. Is there a way to draw the app behind all other running apps (including openbox)?

It is running with openbox as the window manager.

Also, is it possible to run a node-webkit-app as an "dockapp"?
##

**Comment by flynnham** [comment]
Nobody?

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by flynnham** [comment]
So, I get a reply over 3 years later? I'm impressed. I'll still be sure to checkout the mailing list tho.

**Comment by flynnham** [comment]
ETA 2020

**Comment by rogerwang** [comment]
@flynnham we are scrubbing and archiving old issues so you get this update.
By cleaning them the issue system will be put in better use. And we decided
questions and discussions belongs to the mailing list. This will be helpful
on a clean issue tracking system. Your questions would be more likely to be
answered there or in the chat room of the community because there are more
people.

While we would like to try our best to help all the users by fixing bugs
reported by them and answering the questions in the community, please don't
assume you are entitled to an answer. Thanks.
