### ISSUE TITLE
Application not starting with file name parameter

### ISSUE THREAD

**Issue by rjaros** [nwjs/nw.js#2416]
Our application build with node-webkit and packaged to *.exe (copy /b nw.exe+app.nw app.exe) does not start when a valid file name (of existing file) is passed as a first command-line parameter. But it starts correctly when an invalid (not existing) file name is passed, or when there are no parameters at all. The problem appeared in v0.10.3. Tested on Windows and Linux.
##

**Comment by AndryBray** [comment]
+1

**Comment by swaitz** [comment]
I have exact this problem with the new version 13.2.
Is there a work around available so that it would start with parameters?

When I start my application with "ctiClient.exe --agentId 9999 --agentPass 9999" the application will not be shown but I can see it in the task manager. But when I start the application like this "ctiClient.exe ctiClient.nw --agentId 9999 --agentPass 9999" it will start and do a login for the user.

I have also packed the appliaction with this command "copy /b nw.exe+ctiClient.nw ctiClient.exe".

Can anybody help me with this? 

Thanks, Sascha

**Comment by octachrome** [comment]
Still broken in v0.21.3.

**Comment by MaxEden** [comment]
Can confirm. Reproducible in nwjs-v0.21.4-win-x64
