### ISSUE TITLE
Tab Based Application

### ISSUE THREAD

**Issue by acefxlabs** [nwjs/nw.js#242]
I dont know if this is possible. NodeWebkit was based on chromium engine, which makes it a logical browser.
So i wanted to ask if it is possible to build a tab based application with node webkit.

I mean an app that where user can open tabs.

Thanks

**Comment by elmariofredo** [comment]
If anyone is intrested, here is bit simpler solution using Web Components.

https://github.com/angie-party/Thinc

It's early stage but any feedback is welcome. You can try live demo of how it is working http://angie-party.github.io/Thinc/

**Comment by JayrAlencar** [comment]
See this plugin: https://github.com/JayrAlencar/bootstrap-dynamic-tabs

Add, Remove and move tabs bootstrap

I'm working to demonstrate the use in NWJS

**Comment by thedracle** [comment]
I'm interested in getting a stream for each of the windows that comprise my application.

This is possible using desktop capture with some maneuvering to get the native window IDs.

It would be more efficient to use the chrome.tabCapture and I could do it in a more cross-platform way without referring to any platform specific identifiers.

But, it seems like the chrome.tabs API is mostly broken in NWJS, I think due to what is being discussed in this thread.

The tabCapture API seems to work however- but capturers the debugger window. I'm not sure exactly what tab IDs it wants to be fed to capture the contents of my other windows.

Any help regarding this would be greatly appreciated. Especially a simple way to get a 'stream' with the contents of my nwjs window.

**Comment by razzbee** [comment]
I am working on a similar project , I have successfully implemented the tabs with javascript , I will opensource the tabs js file after further features has been added to it
![beebrowser2](https://cloud.githubusercontent.com/assets/3003019/19232469/74d5863e-8ecf-11e6-853a-cc2deaaed574.PNG)

**Comment by jayralencar** [comment]
Great work @razzbee !

**Comment by wanjochan** [comment]
looking for separate proxy solution for each tab...

**Comment by franck34** [comment]
> looking for separate proxy solution for each tab...

Did you find ? On my side, sticked with one proxy for all webviews.

**Comment by mishagin-tim** [comment]
Does nwjs still not support chrome native tabs?
