### ISSUE TITLE
nw search for 'icudtl.dat' and 'nw.pak' in its own directory instead of the current work directory

### ISSUE THREAD

**Issue by spacewander** [nwjs/nw.js#2548]
I put the `nw` into `~/bin`, so that I could use `nw` everywhere wihout typing the whole pathname of `nw`. However, the problem happened:

```
[lzx:~/code/Miu]$ nw . 
[13300:1031/154306:ERROR:icu_util.cc(149)] Couldn't mmap /home/lzx/bin/icudtl.dat
[13300:1031/154306:FATAL:content_main_runner.cc(716)] Check failed: base::i18n::InitializeICU(). 
[1]    13300 abort (core dumped)  nw .
[lzx:~/code/Miu]$ ls
bower_components  build   icudtl.dat  latest_version.json  miu.png  package.json  resource
bower.json  credits.html  index.html  locales  node_modules  nw.pak  README.md     themes
```

Unluckily, `nw` doesn't recoginize `icudtl.dat` in **current work directory**. It searched for the required files in **where it lies**.
In my opinion, let `nw` search in the current work directory, instead of searching in where it lies, is more reasonable. Therefore, would this behavious be changed?

BTW, the `nw` I am using is from `node-webkit-v0.11.0-rc1-linux-x64`.

**Comment by chrisrgue** [comment]
Could you please reconsider reopening the issue above. 
I am using "node-webkit-v0.11.5-linux-x64" and it seems that the issue described above still exists and is currently also breaking node-webkit's own packaging mechanism:
Although the following works very well:

/home/cg/node-webkit-v0.11.5-linux-x64/nw    ~/frameless-window_demo.nw

using the same app after repackanging it into a standalone executable via:

cat /home/cg/node-webkit-v0.11.5-linux-x64/nw   ~/frameless-window_demo.nw   > /tmp/frameless-window_demo_standalone

and

chmod +x /tmp/frameless-window_demo_standalone

Trying to run the resulting exeutable file always fails with the same error:

~/node-webkit-v0.11.5-linux-x64 $ /tmp/frameless-window_demo_standalone
[31439:0104/144414:ERROR:icu_util.cc(149)] Couldn't mmap /tmp/icudtl.dat
[31439:0104/144414:FATAL:content_main_runner.cc(716)] Check failed: base::i18n::InitializeICU(). 
Aborted

Maybe I am missing something crucial. 
How is the repackaged executable supposed to work because in this case there is no "icudtl.dat" file and it seems that this is the reason why it fails in this case ?

**Comment by chrisrgue** [comment]
Please ignore my last post. The missing steps wrt. packaging are perfectly explained in https://github.com/rogerwang/node-webkit/wiki/How-to-package-and-distribute-your-apps
