### ISSUE TITLE
How to use inspect element?

### ISSUE THREAD

**Issue by meetwudi** [nwjs/nw.js#2579]
I found that node-webkit prevented the context menu from presenting, so how can I use inspect element to debug?

**Comment by peterchylewski** [comment]
Thanks! This works for me.

**Comment by OlsonDev** [comment]
I've been using this method since I started using nwjs but I'd like a convenience function. I want to register a middle-click handler on the entire body which opens the dev tools (if not already open) and inspects the element my mouse was over. I'm aware of how to do the first part (open the dev tools). Is there a way to programatically tell the dev tools to inspect a specific element?

**Comment by ncannasse** [comment]
Would be interested in a solution for that too @OlsonDev @thefallofbecause

**Comment by OlsonDev** [comment]
@ncannasse I started using Electron instead of nwjs a while ago. They have an `inspectElement` function: https://github.com/atom/electron/blob/master/docs/api/web-contents.md#webcontentsinspectelementx-y

**Comment by himanshuoodles** [comment]
i am use MAC OS , i can not see inspect element on right click of nw app but when i use it in linux it show me inspect element on right click . pls tell what to do in MAC OS to inspect
