### ISSUE TITLE
Suppress proxy dialog

### ISSUE THREAD

**Issue by tommoor** [nwjs/nw.js#2618]
One of our users is behind a proxy - this happens when they open our node-webkit based application - ideas on how we could better handle this? Is there a way to suppress these dialog boxes at the very least?

![image](https://cloud.githubusercontent.com/assets/380914/5055867/6244cdf0-6c20-11e4-9df5-99b315eb61f6.png)
##

**Comment by Thatkookooguy** [comment]
This is also a problem I have.

When my program runs behine a proxy, nothing works since it requires a connection to the internet.

when I run nw.App.setProxyConfig(settings.proxySettings.proxy + ':' + settings.proxySettings.port+",direct://"); in my app, which suppose to translate to 'use proxy, unless you can't, it doesn't work no matter what I do. even if I remove the direct:// it still doesn't work.

every request I send doesn't come back with a statusCode of 200.

Is this something that is known to be an issue?
