### ISSUE TITLE
Gui Global Shortcut masking keyboard events from other Running Application

### ISSUE THREAD

**Issue by kamesh-a** [nwjs/nw.js#2636]
Hello,

There is issue, which we are able to see when trying to use Global shortcuts gui.Shortcut, when we register a command say "ctrl+f".

Expected Behaviour : shortcut should work within the app, Yea it works, but
Defered behaviour: when app is background, say for example we are active in some other app "chrome" perhaps, if we initiate the same key press, it goes to my node-webkit app instead of that active app, plus keyboard ns event does NOT bubble to other application. Search bar not shows up in "chrome".

snippet:
```
var gui = require('nw.gui');

var option = {
  key : "Ctrl+f",
  active : function() {
    console.log("Only Node Webkit app will recieve this KEYpress, NO other apps even when they are active !!!"); 
  },
  failed : function(msg) {
    // :(, fail to register the |key| or couldn't parse the |key|.
    console.log(msg);
  }
};

// Create a shortcut with |option|.
var shortcut = new gui.Shortcut(option);
// Registering Global HotKey
gui.App.registerGlobalHotKey(shortcut);

```

Tested both in 0.10.6 and 0.11 build.

System Specs:
OS : OS X yosemite 10.10 and Maverics.

**Comment by leifwells** [comment]
I am seeing the same behavior in Mac OS X Yosemite 10.10.1 with 0.12.alpha2

**Comment by mrfabbri** [comment]
Hi @kamesh-a, this is the expected behaviour. The shortcut is global, i.e. system-wide, so, yes, it will override other shortcuts (otherwise it won't work when the app is not active), the documentation in [`Shortcut`](https://github.com/nwjs/nw.js/wiki/Shortcut) is clear: "If registered successfully, it works even if your app does not have focus". 

If you want to implement application wide shortcuts you may have a look at https://gist.github.com/mrfabbri/3a32baf9c5eb5a446a48.
