### ISSUE TITLE
Hide source code possibility

### ISSUE THREAD

**Issue by darky** [nwjs/nw.js#269]
I mean about executable container, which not allow to show source code.
Not offer obfuscation

**Comment by darrrk** [comment]
> 2) Use Visual Basic Script:
> CreateObject("Wscript.Shell").Run 'nw.exe --no-toolbar --url="https://my-server.herokuapp.com" --user-> agent="lhMf4Tct78ro08r74hUTR88bJ258FI" '
> This script exported in exe with ExeScript for example

Now can use jxcore for this purpose

**Comment by rajiff** [comment]
@rogerwang
Is .bin files readable (crackable) by users in any way? 
Is it possible to have more than one .bin files in the app? @kevsmt  too asked this above, not sure if that was answered, hence asking again

**Comment by shaynem** [comment]
In my experience If you cat the bin file the info is still visible in
amongst the data using nwsnapshot which defeats the purpose.

**Comment by yangguo-chromium-org** [comment]
Maintainer and implementer of the serializer/deserializer in V8 here.

We've recently improved the serializer/deserializer a lot to support code caching and custom startup snapshot. Among others, the snapshot size issue has been fixed so that we can have arbitrary number of pages in the snapshot.

Using the code cache, JIT code compiled from a script can be serialized and later deserialized to bypass parsing/compiling. It's somwhere between 10x to 100x faster.

Using the custom startup snapshot, you can create a snapshot blob after running a user-specified script. When you pass in that snapshot blob in v8::Isolate::New, the serialized heap and context are restored.

What I'm curious about though is how you manage to hide the source code. V8 assumes that the source code is available in order to recompile (for debugging and when compiling for optimized code). Did you disable recompiling so that you can remove the source code?

**Comment by rogerwang** [comment]
@yangguo-chromium-org Glad to hear from you. 

Starting from 0.12.0-rc1 NW uses v8 code cache to implement this feature, before that we use the startup snapshot. Thanks for your work to make this happen.

To answer your question: yes, we patched v8 to disable the recompilation. See https://github.com/nwjs/v8/commit/67b65e04c0ded8f80729a389b404896c803216b6

https://github.com/nwjs/nw.js/blob/nw12/src/api/v8_internal_helper.cc

**Comment by rogerwang** [comment]
PS: By disabling the recompilation to remove the source code, the result is that the code runs slower with the fullgen compiler. In future we plan to provide some tool so developer could run their code with some data in compile time, so the other crankshaft compiler in v8 would be used to generate faster code. Any thought on this?

**Comment by rogerwang** [comment]
@rajiff the binary code is not readable by end users.
@kevsmt @simonhoss @rotatingJazz 

In 0.12.0-rc1 released yesterday the feature is improved as you requested: the size limitation is removed; multiple binaries can be loaded from JS; see the release notes: https://groups.google.com/d/msg/nwjs-general/Sykci3Qhgus/AoF0zT7TEIoJ

**Comment by yangguo-chromium-org** [comment]
@rogerwang we are actually considering caching code after it has executed and including type information into the cache, in order to have the optimizing compiler kick in earlier. But that's not even work in progress yet.

**Comment by ekhaled** [comment]
@rogerwang with the introduction of `evalNWBin()`, snapshotted code is no longer used by V8 as a template to create JS contexts.
The user has to explicitly call `evalNWBin()`.
In light of that, how do I make snapshotted code available in `node-main` and / or `bg-script` scripts?

Thanks for the awesomeness BTW

**Comment by rajiff** [comment]
@rogerwang do we have a sample package.son or a snippet to check how to use
multiple bin files

**Comment by nicu** [comment]
@yangguo-chromium-org are you saying that in the future the snapshot **might** be useless for hiding code? Could we somehow choose the option to hide the code over the earlier optimisation? 

Does anyone know of any good alternatives?

I'm about to start work on a project that requires me to obfuscate part of the business logic and I wouldn't want to use a solution that might break in the future.

Thank you.

**Comment by yangguo-chromium-org** [comment]
@nicu
V8 never supported hiding source code via snapshot in the first place. Consider Function.prototype.toString, which is specified in ECMA262. It won't support hiding source code in the foreseeable future either.

nw.js makes hiding source code possible by sacrificing the ability to run optimized code, since the optimizing compiler compiles from source code. There is no guarantee that the hack that made this possible can be easily implemented for future V8 versions.

**Comment by yoyoy** [comment]
hello
is it a way to improve encryption of bin file with nwjc.exe ? an option to enable ? 
I can read some datas i the bin file with a text editor :'(
https://github.com/nwjs/nw.js/issues/3399

**Comment by darrrk** [comment]
Interesting utility
[enclose](https://github.com/igorklopov/enclose)
Maybe it's would be useful

**Comment by L3V147H4N** [comment]
EncloseJS seems really promising for this matter, has anyone tested this with nwjs?

**Comment by sujkh85** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

sujkh@naver.com 님께 보내신 메일 <Re: [nw.js] Hide source code possibility (#269)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by darkguy2008** [comment]
EncloseJS does seem good but it does require contacting the author for a payment option in order to be used in a commercial version (contrary to what nw.js offers since it's under the MIT). If he did it, I'm sure the V8 maintainer can do it too, right?

**Comment by yangguo-chromium-org** [comment]
I'm fairly sure EncloseJS simply uses V8's code serializer to serialize compiled code. Its github repo dates back to roughly the same time when I finished with implementing that feature in V8, except for a few bugfixes. It's described here in the section "Code Cache":
http://www.hashseed.net/2015/03/improving-v8s-performance-using.html

EncloseJS probably patched V8 so that it can deal with missing source code (i.e. no optimizing compile pass) and prevents code flushing (at least it should; not sure if it really does). This is not really supported and may lead to bugs.

Caching code speeds up start up a bit by not having to compile anything, but you would still have to execute that start up code. V8's custom heap snapshot is superior to that: you would simply bootstrap V8 into a state as if the start up code already executed.

**Comment by yangguo-chromium-org** [comment]
Also: https://github.com/igorklopov/enclose/issues/9

**Comment by namaljayathunga** [comment]
How can I hide toolbar programmatically?

**Comment by makkesk8** [comment]
@namaljayathunga check the wiki.

**Comment by rohan-deshpande** [comment]
Chiming in on this topic as it's pretty interesting for me. I'm developing a (hopefully) closed source game engine with JavaScript and NodeWebkit (I'm still on `v0.10.5`). Is it necessary to do a v8 snapshot of the entire codebase, or can you say, compile your own code this way but load other, open source libraries the regular way so that they get optimisation benefits?

For example, I have all my proprietary code concatenated to `game.js`, however the libraries that I use are inside of `vendor.js`. Can the snapshot somehow run the vendor code normally and run the snapshot of the game code or is this an "all or nothing" situation?

**Comment by hashseed** [comment]
Having a custom snapshot does not affect other parts of V8, including compiling and running scripts. So your game.js can be included in the snapshot, but vendor.js does not need to be.

However, V8 snapshot is not designed to hide source code. Chances are that the source of game.js will be serialized into the snapshot as well. Extracting it from the snapshot would be fairly easy.

**Comment by rohan-deshpande** [comment]
Ah right that's good to know, but as per https://github.com/nwjs/nw.js/issues/269#issuecomment-76524096, doesn't the recompilation avoidance stop the source code from being exposed or am I misunderstanding?

**Comment by hashseed** [comment]
Well you could definitely hack V8 to drop the source code, and make sure it's not used for display or recompilation, but V8 does not support this out of the box. Unfortunately I don't know whether nw.js has patched V8 to do that.

**Comment by rogerwang** [comment]
@hashseed @rohan-deshpande yeah, NW supports dropping source code for source code protection, check http://docs.nwjs.io/en/latest/For%20Users/Advanced/Protect%20JavaScript%20Source%20Code/

**Comment by rohan-deshpande** [comment]
Thanks @rogerwang, so let's take my example (https://github.com/nwjs/nw.js/issues/269#issuecomment-224177077), if you used the source code protection for `game.js` but not for `vendor.js` would you only see speed reductions in `game.js` code and not `vendor.js` code?

**Comment by rogerwang** [comment]
@rohan-deshpande the document said this clearly: "The compiled code runs slower than normal JS: ~30% performance according to v8bench. Other non-compiled JS source code will not be affected."

**Comment by rohan-deshpande** [comment]
Cool! Yes I read that just wondering if I read it correctly or not. Thanks for clearing it up :)

**Comment by hashseed** [comment]
@rogerwang you could give this a try: run V8 with --ignition --turbo. That forces V8 to use a different compiling pipeline. Ignition is our upcoming interpreter that compiles source to bytecode. We can then optimize from bytecode directly without having to parse from source.

**Comment by rogerwang** [comment]
@hashseed great! will try.

**Comment by danschumann** [comment]
Are there any issues with source code protection mentioned here? http://docs.nwjs.io/en/latest/For%20Users/Advanced/Protect%20JavaScript%20Source%20Code/

I know a previous version had a bug and I'm wondering if my source code would be totally protected.

**Comment by rogerwang** [comment]
@danschumann no there is no issues.

**Comment by alphasdev** [comment]
How reliable this way to protect source code now? Is it possible to crack the javascript source code now (last ver nwjs & chromium)?

**Comment by alphasdev** [comment]
How reliable this way to protect source code now? Is it possible to crack the javascript source code now (last ver nwjs & chromium)?

**Comment by baconface** [comment]
> @alphasdev How reliable this way to protect source code now? Is it possible to crack the javascript source code now (last ver nwjs & chromium)?

Refer to the two comments above yours.

**Comment by darkguy2008** [comment]
Haha, come on, if he'd release the source code, alphasdev and all of us would be able to know. What is the point of publishing something on GitHub if you are not going to use it for SOURCE CODE ? It's not a file hosting ffs.

**Comment by alphasdev** [comment]
@darkguy2008, off topic.

**Comment by darkguy2008** [comment]
That's not offtopic, we're talking about the code protection which we can't see if the source code is not published. It's pretty on-topic for me.

**Comment by baconface** [comment]
> That's not offtopic, we're talking about the code protection which we can't see if the source code is not published. It's pretty on-topic for me.

I cannot see how someone's opinion on GitHub's purpose pertains to or aids this discussion/issue.

**Comment by darkguy2008** [comment]
Ah crap, my bad, I thought this was about that other side-project which uses nw.js and claims to be able to hide the source code but he never releases the source code because he's a jerk. Sorry about all the offtopic xD

**Comment by hashseed** [comment]
This should become possible soon. V8 is going to switch to a bytecode interpreter and the new optimizing compiler in the next few months. Once that's done, V8 will no longer need the source code, if everything is compiled to bytecode ahead of time.

**Comment by danschumann** [comment]
@hashseed isn't this topic about a similar method of protection?  I open up the .bin files with a hex editor and I see a few recognizable names, including strings, but isn't the rest already some sort of byte code which cannot be turned back into readable javascript?

You're just saying that they're adding it to the core V8, including web browsers soon, right?

**Comment by jportoles** [comment]
@danschumann the issue is that currently, in order to compile to a native V8 snapshot, run time V8 optimizations have to be sacrificed, and hence the code ends up being 30-50% slower. A bytecode compiler/interpreter would solve this problem by natively supporting compiled javascript while still being able to do run time optimizations. Thus it would be a win-win for NW.js to adopt this method of compilation vs the existing one, once @hashseed and their team get their implementation ready.

**Comment by hashseed** [comment]
Currently, V8 needs to include the source string for the functions it includes in the snapshot. Otherwise it cannot recompile these functions to optimized code. Afaik nw.js includes a hack to remove the source string to obscure it, but that prevents optimization.

V8 will soon move to a compiler pipeline that does not need the source string to recompile to optimized code anymore. So for these, we could introduce a new option to eagerly compile functions to include the bytecode in the snapshot, and in return be able to drop the source string.

**Comment by rogerwang** [comment]
Happy to announce that it's fixed finally, source code protection performance vastly improved: https://nwjs.io/blog/js-src-protect-perf/

**Comment by f3l1x** [comment]
@rogerwang Good job man.

**Comment by flddr** [comment]
I am very late here, but @rogerwang my biggest respect - thank you very much!
