### ISSUE TITLE
Window menu not showing up (version 0.11.1/0.11.0 x64 linux)

### ISSUE THREAD

**Issue by thesabbir** [nwjs/nw.js#2696]
```javascript

        var nw = require('nw.gui');

        // Window menu
        var windowMenu = new nw.Menu({
            type: 'menubar'
        });

        // Assign to window
        nw.Window.get().menu = windowMenu;

        // Help menu
        var helpMenu = new nw.Menu();

        // Add to window menu
        windowMenu.append(new nw.MenuItem({
            label: 'Help',
            submenu: helpMenu
        }));

        // About sub-entry
        helpMenu.append(new nw.MenuItem({
            label: 'about',
            click: function(){
                alert('I made this!');
            }
        }));

```

Version 0.10.0:
![](http://i.imgur.com/hff69mu.png)

Latest Version:
![](http://i.imgur.com/FiDv0qx.png)

Just title bar height  is increasing. No text or menu is showing up.

GTK 3.12.2
Gnome Ubuntu 14.04 x64
Node Webkit 0.11.1

**Comment by physicsshark** [comment]
I think this is because the previous users are using dark themes.  With a light gtk theme, the menu shows, but did not match my theme colors.  I was able to replicate this issue with a dark gtk theme.  With this titlebar gets larger, the menu item disappears.  I think this is because the new node-webkit code, the menu is being created by some pseudo-gtk chromium thing, rather than actual gtk code, as it was in 0.8.6.  I feel strongly that the previous gtk code should be restored.  I think this is a serious issue that needs to be addressed with upcoming versions.  Otherwise, you shoud tell users not to use node-webkit gui menus on Linux.

**Comment by thesabbir** [comment]
@jonwwilkes @physicsshark 
Also new version doesn't supports (or undocumented?) unity global menu.

**Comment by physicsshark** [comment]
@thesabbir That would make sense, as it appears that the new version is using is not real gtk code.

**Comment by physicsshark** [comment]
@jonwwilkes @thesabbir @rogerwang 
I was just trying out the 0.8.6 version, and the gtk support is so much better.  But the older code doesn't support some of the newer features I want to use.  I would contribute, but I don't know how to code gtk.

**Comment by thesabbir** [comment]
@physicsshark same here.

**Comment by physicsshark** [comment]
I was playing with the different versions of node-webkit, and the gtk menu works in node-webkit 0.10.5, but not 0.11.0, so somewhere between the two releases, the code must have been changed.

**Comment by kensully** [comment]
I have the same issue. I think it stems from cromium's swiching to it's own tool `aura` after version 34. Since they removed gtk dependent source code, we face to many broken feature in recent version of `node-webkit` 
It must be replaced somehow.

**Comment by physicsshark** [comment]
@kensully Do you think there's a way to abstract the chromium code to not use ```aura```?  The Qt people have done it with QtWebEngine (http://qt-project.org/wiki/QtWebEngine).  Also, you don't have to use gtk for native linux menus.  You can also use Qt, too.

**Comment by kensully** [comment]
@physicsshark 
I don't know how `Aura` works. I read that,  in Chrome OS, `Aura` is using `Ash` ( Aura Shell window manager) to communicate with desktop. If it's possible to use Aura's API then it should be correct way to implement missing features using Aura, otherwise we ll have to inject gtk code back into chromium sorce code, or as you mentioned, it also appears to port gtk to qt. But it's  beyond my coverage
I am not an expert, I'm just thinking.

**Comment by kensully** [comment]
One of the regression in node-webkit I reported earlier is related to issue here https://github.com/rogerwang/node-webkit/issues/2833

**Comment by rogerwang** [comment]
You could try assigning menu to the window in the last step after menu construction. That should work because it's how I tested it.

I'll fix your case.

**Comment by rogerwang** [comment]
@kensully could you please list all the regressions? I'd like to fix them all.

**Comment by kensully** [comment]
@rogerwang 
Thank you for handling the issue in person. I only came across the `as_desktop` issue. I ll report any regression when I meet them. I checked out the node-webkit issues tagged as `regression`, you self-assigned them all. 
I'm glad to read that you ll fix them. We owe you much for your work.
Regards.

**Comment by physicsshark** [comment]
@rogerwang Yes, thanks so much.

**Comment by jonwwilkes** [comment]
@rogerwang: thanks, the workaround you proposed indeed gives a menu.  However, it doesn't look like a standard window menu.  For example, the popup containing the menu items isn't always left-aligned with the name of the menu in the menubar.  (I can post a screenshot if that's helpful.)

How much would it cost to pay someone to fix this so that it looks like proper menus (i.e., looking like they did on nw 8.6)?

Also, is there a way to bind the Alt key to activate the window menu, and arrow keys to navigate among the menus in the menubar?

Thanks,
Jonathan

**Comment by jonwwilkes** [comment]
Sorry, ignore that last off-topic sentence-- I'll ask it on the nw group.

**Comment by leomuniz** [comment]
Same here! I'm using 0.11.6 for Windows 32bit. Assigning menu to the window after menu construction worked for me, how rogerwang suggested. Thank you very much! 

Here's how:

    var win = gui.Window.get();
    win.menu = menu;
