### ISSUE TITLE
Video cannot play on read-only usb stick in Windows

### ISSUE THREAD

**Issue by shaase** [nwjs/nw.js#2781]
Hey, I'm not sure if this is an appropriate question for the issues section here, but I'm running into an issue with a node-webkit project where I have video embedded. I included all the required codecs, and everything works fine when the program is launched on the hard drive or on a regular usb stick.

However, we copied the program onto a read-only stick, and when we click to open a video, we get the following error:

> There is a write protection on the device where it cannot be recorded. 
> Please delete the write protection on the device.

I'm only loading and playing video files via Javascript. Not sure if Windows or Chromium is trying to cache something here.
##

**Comment by micsan13br** [comment]
Hello,

I've just noticed a similar problem with a node-webkit application with webm videos embedded.
It works just fine in our LAN, on my local disks, from a (writable) USB stick and even when burned to DVD, but for some reason it throws an error when running from a read-only USB stick.

The video plays fine, but when I try to use the seekbar, I get the following error:

Title: "nw - Write Protect Error"
Message: "The disk cannot be written to because it is write protected. Please remove the write protection from the volume USB_DISK_LABEL in drive I:"

I have no idea why nw wants to write something anyways.
Do you have any clues?
