### ISSUE TITLE
Input File Bug

### ISSUE THREAD

**Issue by fddxsc** [nwjs/nw.js#2826]
HTML code：
<input id="input_bgImage" type="file" onchange="PreviewImage(this);"/>
<img id="bgPreview" style="width:100px; height:100px;"/>

JS code：
function PreviewImage(imgFile){
　　//alert(imgFile.value);
　　document.getElementById("bgPreview").src = imgFile.value;
};

Image File Name：
image1 name：8b78d8f8fca9d01d93dab145f99a6a20.jpg
image2 name：123.jpg

Description：
First, choose image1 then change to image2. Image2 cannot  be loaded because that it has a wrong path(imgFile.value). 
##

**Comment by felixSchl** [comment]
Here are more symptoms:

* For me, it only happens when `accept=""` is set. It may be empty, but as soon as it's there, stuff goes awry
* The first file I load works fine, however the second file does not. I found, however, that the number of characters in the second file's filepath matches the number of characters of the first file's filepath. It seems to use the old string and replace only as many characters as it needs, leaving the old characters there.
