### ISSUE TITLE
“command not found” issue

### ISSUE THREAD

**Issue by LorinWeb** [nwjs/nw.js#2855]
I get "command not found" error trying to execute a bash command from an app. I'm using Node.js's _child_process()_ to achieve this. In my particular case the missing command is _casperjs_, but both of the following are working fine in the terminal:

```
$ casperjs myCasperScript.js
$ node myNodeScript.js (the script I'm trying to run whithin the app)
```

Here is the log of my node-webkit app:

```
stderr: /bin/sh: casperjs: command not found
exec eror: Error: Command failed: /bin/sh -c casperjs myCasperScript.js
```

I believe the problem relates to "/bin/sh" not being the right path, but am not able to find a solution. I've already tried to add the _env_ option in the _child_process()_.
In that case, the error is different:

```
stdout: Fatal: [Errno 2] No such file or directory; did you install phantomjs? 
```

(I tried also with /usr/local/bin and /usr/local/bin/ getting the same error)
*phantomjs it's installed obviously.
##

**Comment by MarcFowler** [comment]
Can you specify the explicit, full path to the command that you're running? Perhaps http://docs.casperjs.org/en/latest/faq.html#can-i-use-casperjs-without-using-the-casperjs-executable will help.. it explains that you can [download the PhantomJS binary](http://phantomjs.org/download.html), and then you could call that.

So you'd be calling `child_process.spawn(pathToPhantom, args);`

This would mean you can include PhantomJS inside your node-webkit app and point to that using the local file system. Otherwise your end-users will require having PhantomJS installed on their system too, but this would package it up in one for them. Check that the licensing allows that.

(FWIW, I've never used PhantomJS before, let alone inside node-webkit! But I've done similar things with ffmpeg and some Obj-C apps I've written myself so I hope this helps! Upon some reading, I'm not sure it's a great idea to package up a 9mb PhantomJS app inside node-webkit itself but...)

**Comment by octalmage** [comment]
I'm running into a similar issue, the command runs fine using node.js, but the same code fails in node-webkit. I just can't figure it out. :sob:

**Comment by MaxSvargal** [comment]
Any program doesn't found on child_process.exec. It's bug in nw.

**Comment by achekulaev** [comment]
This is an interesting but though. When I develop an app and run it without packaging then $PATH seems ok. But when I bundle into an standalone app for release then $PATH only contains of couple of dirs like app was running from another user.

**Comment by achekulaev** [comment]
Just in case someone will struggle with it. The issue is that when bush is run non-interactively then it does not read `.bashrc`.
