### ISSUE TITLE
WebVR?

### ISSUE THREAD

**Issue by justinmchase** [nwjs/nw.js#2857]
It would be pretty cool to get a build of node-webkit that had the WebVR api's available. It perhaps makes even more sense in node-webkit than it does in the browser itself...

I have no idea how hard it is to do that but here is some info:
http://blog.tojicode.com/2014/07/bringing-vr-to-chrome.html

I'd be willing to help if I can, but I'm not sure where to begin.

**Comment by jwerle** [comment]
+1

**Comment by moosingin3space** [comment]
Is there a way to build a version of `nw.js` that uses that build of Chromium?

**Comment by andresiraola** [comment]
I'm working on it on my own fork.

I'm trying to replicate Brandon's work in nwjs: https://chromium.googlesource.com/experimental/chromium/src/+/refs/wip/bajones/webvr_openvr

I'm a bit blocked because Brandon's work is based on a more recent version of chromium/blink so I have 3 options and I didn't decided yet which one I'll take:

1) update nwjs 13 to the version Brandon is using.
2) adapt Brandon's implementation to work with the current nwjs's chromium/blink version
3) apply only the commits i need to make it work. i think this could become a recursive task that will end by taking to chromium to the last version :)

Perhaps 2) is the easiest one. It would be better if nwjs13 alpha5 is based in a more recient or the last version of chromium/blink where by the way, blink is merged into chromium's repo..

I'll keep you posted
