### ISSUE TITLE
Enabling ECMAScript 6?

### ISSUE THREAD

**Issue by Bigmacbook** [nwjs/nw.js#2872]
Is there a way to enable ECMAScript 6 in node-webkit 0.11.4 because in Chrome Version 39.0.2171.95 m there is a chrome://flags to turn on ECMAScript 6 under "Enable Experimental JavaScript Mac, Windows, Linux, Chrome OS, Android" 

The reason I ask this is because I want to use the new "Class" feature.
##

**Comment by kaustavha** [comment]
Easiest way to use ES6 features would be to compile ES6 source code to ES5 using something like facebooks regenerator or google traceur compiler imo. 
You can also plug them into gulp or a cakefile or any other build tool. 
Not optimal but gets the job done.

**Comment by wookiecooking** [comment]
See this https://github.com/nwjs/nw.js/wiki/Manifest-format#chromium-args

**Comment by LestaD** [comment]
v8/v8-git-mirror

**Comment by wookiecooking** [comment]
is this still relevant since the switch over to io.js?

**Comment by lendrick** [comment]
Randomly stumbled on this issue while googling about whether nw.js supports ES6.  Since there wasn't a conclusive answer here, I tested a couple of ES6 features on the current version at the time of this writing (0.20.2), and it appeared to work fine.  Note that my tests were in no way exhaustive, but they seem to indicate that ES6 support is there.

**Comment by rogerwang** [comment]
Thanks for the information.

**Comment by Xsmael** [comment]
@lendrick  though your tests were not exhaustive, did you at least test some feature that would ultimately fail in browser that doesnt support ES6 ?
