### ISSUE TITLE
Modal windows

### ISSUE THREAD

**Issue by dalerobbins** [nwjs/nw.js#2879]
@rogerwang would it be possible to have an option to specify a modal window when creating/opening another window in node-webkit? Example: Let's say I want to present an about window to the user for my node-webkit app which the user would have to close in order to continue back to the application. This would prevent the user from clicking back to the node-webkit app leaving the about window open in the background and would also prevent the user from instantiating another about window when it is already running.

This feature would give a node-webkit application a more native look and feel under certain circumstances.

**Comment by philgin** [comment]
Why was this closed? It's a very important feature for native applications...

**Comment by baconface** [comment]
Likely because it is possible with CSS and JavaScript. Make a div with fixed position and large z-index take up the whole screen. Make it dark or light background color with transparency to signify the window is disabled. When they click this element in the parent window have an onclick event give focus to the child again. Remove this element only when you are ready to give the user access to the window.

Also possible with most UI libraries that have modal windows/dialogs.

**Comment by marckris** [comment]
Please reopen this issue.

Using CSS we can only cover the browser window, not the builtin menu bar created with Menu (http://docs.nwjs.io/en/latest/References/Menu/) i.e. we can still click on the menus.

I don't think there is a workaround to this problem.

**Comment by rogerwang** [comment]
let's keep it close and merge into #1409

**Comment by ropbla9** [comment]
+1

**Comment by mohamedattache** [comment]
+1

**Comment by Quartzbell** [comment]
+1
Yes, we need a REAL modal window, not those HTML-CSS popup inside the screen work around.
Let's bring back those old modal popup window back in NWJS.
Yes we all know a modal popup window can lead to multitude security issues in chromium as a web browsers. But we also know that doesn't apply at chromium as a desktop application, a modal popup window is A MUST HAVE feature in NWJS.

**Comment by muhammad-bassiouni** [comment]
Is there any update on this feature?

**Comment by attachemd** [comment]
+1
