### ISSUE TITLE
Crash dumps not generated

### ISSUE THREAD

**Issue by User199011** [nwjs/nw.js#2906]
Hello,

I'm developing an application (on Windows now but I'd like to have a mac version as well) using angularjs and node webkit.

It happens that my application crashes but I don't know why. So I thought I should check the dump file generated as precised here : https://github.com/rogerwang/node-webkit/wiki/Crash-dump

So here is my code :
// Load native UI library
var ngui = require('nw.gui');

ngui.App.setCrashDumpDir("logs");

// Get the current window
var nwin = ngui.Window.get();
// show devtools to debug
nwin.showDevTools();

onload = function() {
    nwin.show();
    nwin.maximize();
}

ngui.App.crashBrowser();

I've put the last line to find a crash report but I'm unable to find any in the logs folder of my application.
Why ?

Thank you
##

**Comment by chino23** [comment]
having the same issue.

**Comment by rogerwang** [comment]
It's a bug of 'setCrashDumpDir()', you may find it in the default location.

**Comment by chino23** [comment]
thanks for replying, @rogerwang . But the default location which is specified in the wiki doesn't work on Mac, there is nothing in there either.

**Comment by User199011** [comment]
thank you, I finally find dump files in the default location. However I can't manage to read them using Windows, could you help me ? 
(The link for the resources https://s3.amazonaws.com/node-webkit/v0.8.0/nw.exe.pdb.zip seems to be broken)

**Comment by mateoguzman** [comment]
I am getting this same issue. No crash dump file is generated in my case. 
I am using Windows 7 and tried NW versions 0.11.6, 0.11.4 and 0.10.0 with no success.
However using NW version 0.8.7-rc4 the .dmp file is being generated.
I am using the crash API to force NW to crash

    var gui = require('nw.gui');
    gui.App.crashBrowser()

Thank you.

**Comment by mateoguzman** [comment]
Additional information: Seems to be a problem on Windows 7, since tried in Windows 8 and the crash dump file is being generated.
I also found that when the crash happens a Windows Log is generated (Type Application, Level Error)  with the following description: 

>The description for Event ID 1 from source Chrome cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

>If the event originated on another computer, the display information had to be saved with the event.

>The following information was included with the event: 

>Chrome has encountered a fatal error.
>ver=0.0.0.0-devel;lang=;guid=;is_machine=1;oop=1;upload=1;minidump=C:\Program Files (x86)\Google\CrashReports\5b7c2500-1e81-4394-a44e-388b58fc9397.dmp

**Comment by smiller333** [comment]
Windows 7 (64bit), NW version 0.10.5 - I am seeing the same issue as mateoguzman.  I am getting Windows logs that point to the actual Chrome installation for the crash dump location.  The crash dumps are being written there instead of the "System temporary directory" as per the "Crash Dump" wiki page.  I tried with and without setting a custom dump directory and get the same results both times.

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 and later versions we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.
