### ISSUE TITLE
No nm.exe

### ISSUE THREAD

**Issue by andy2ndlife** [nwjs/nw.js#2918]
When I downloaded the project page package, there is no nm.exe file to run the "C:\path\to\node-webkit\nw.exe C:\your\project\folder" command.  Please direct me to where I could download the .exe for Windows.

Thanks in advance.

**Comment by mpreziuso** [comment]
Hello @andy2ndlife!

`nm.exe`? Maybe you mean `nw.exe`: there shouldn't be a nm executable to my knowledge.

In order to run your project on node-webkit you need launch `"C:\path\to\node-webkit\nw.exe C:\your\project\folder"` where `C:\path\to\node-webkit\nw.exe` is the path to the extracted archive you downloaded from [README#Downloads](https://github.com/rogerwang/node-webkit#downloads).
Make sure you download one the versions for Windows!

That's all :)

**Comment by andy2ndlife** [comment]
Hi Michele,

Yes, I meant nw.exe.  Thanks for the new download link.  I got it now.

Once again, thanks.

Regards,
*Vuong Software Development <http://www.vuongsoftwaredevelopment.com>*
*[facebook <https://www.facebook.com/VuongSoftwareDevelopment>] | [L
<https://www.linkedin.com/in/vuongsoftwaredevelopment>**inkedin
<https://www.linkedin.com/in/vuongsoftwaredevelopment>]*

**Comment by mpreziuso** [comment]
Hi Andy, you're welcome!

**Comment by jorisvddonk** [comment]
@andy2ndlife Please close this issue
