### ISSUE TITLE
Switch over to io.js means dropping Windows XP support?

### ISSUE THREAD

**Issue by vsemozhetbyt** [nwjs/nw.js#2932]
nwjs-v0.12.0-alpha1-win-ia32 still works in Windows XP. As I see by the `process.versions` it has **node 0.11.13-pre**, not **iojs 1.0.1**. However when it does have iojs, nw.js will not work in Windows XP anymore, because most likely io.js team will drop Windows XP support. [See comments in this issue.](https://github.com/iojs/io.js/issues/374)

**Comment by wookiecooking** [comment]
The comments in that issue for io suggest that they will drop support for windows XP if someone doesnt pick up the work. Like someone else suggested in that thread, newer versions of visual basic wont even run on XP, nor is microsoft supporting it anymore.

from what I can see @rogerwang supports the idea of moving over to io in the next version, 0.12.

**Comment by vsemozhetbyt** [comment]
Well, the io.js issue was just closed. Probably,  that means NW.js will not support Windows XP soon.

**Comment by ChALkeR** [comment]
WinXP does not even receive critical security updates anymore.
Whoever is still using WinXP, they have more serious problems than not being able to install new software developed in 2015+.

Just forget it.

**Comment by vsemozhetbyt** [comment]
And the main browsers and script languages still support it(

**Comment by ChALkeR** [comment]
Chrome drops XP support in 2 months.

It's dead, jim.

**Comment by ChALkeR** [comment]
Btw, IE is also a major browser, and the latest major version for XP is IE8, it does not receive non-security fixes for several years, and it _does not receive security updates for 8 monhts_. That's not what you call «supported».

**Comment by vsemozhetbyt** [comment]
And what about this? http://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0

**Comment by wookiecooking** [comment]
@vsemozhetbyt Granted the market does still have windows XP machines running on it, but the same could be same about users still using IE6.

Are we to support older operating systems that are even declared obsolete from the developers who created it? 

The requirements to meet a small market share just doesnt make sense.

**Comment by vsemozhetbyt** [comment]
OK, I give up) May be this issue sould be closed too.

**Comment by formula1** [comment]
@vsemozhetbyt I understand the feeling of trying to find a stable operating system. XP is stable, Vista was terrible, Windows 7 was better (than vista), Windows 8 bad etc.... Unfortunately, XP is old. And though people still may need it supported and developers want to support it, from what I understand it can be worse than cross browser compatability.

I don't think you should be barraged by insults by @wookiecooking or @ChALkeR for wanting a stable operating system to come with your badass applications. But, unfortunately, supporting XP would be holding back progress. You can always have an XP partition. There are many stable(ish) linux distrobutions available. And the more you work in/understand linux, the easier it will be to handle server logistics (since most servers run on it). I'm personally using Ubuntu, though when NodeOS becomes a thing, I without a doubt will be using that (even if it means I'm the guineapig).

**Comment by wookiecooking** [comment]
@formula1 I wasn't attempting to be insulting, I was merely supplying the fact that it is not supported anymore and io.js developers were actively suggesting that people who wish to support could jump in and do it.

The same issue could be said for chromium, which is another project dropping support for XP.

Technically, you could just use a older port of nw.js, it just wont have all the same bells and whistles.

Like they mentioned in the linked issue, it just doesn't make sense to for their application, which happens to be used for this project.

I believe this issue should be closed, since the issue of XP support actually relies on io.js and chromium.

**Comment by vsemozhetbyt** [comment]
It' OK, no hard feelings. Thanks to all for the comments.

**Comment by ChALkeR** [comment]
@formula1, sorry if my wording insulted you or @vsemozhetbyt.
I just tried to bring up the fact that xp should be considered broken and insecure itself, then I corrected an invalid statement that was made by @vsemozhetbyt.
Maybe I was a bit harsh, excuse me, if so. No offence meant.

My opinion is that there is no point to keep support to the dead operating system — it's just harming the users. The users should be motivated to no longer use an unsecure system.

**Comment by smolleyes** [comment]
+1

**Comment by formula1** [comment]
@wookiecooking @ChALkeR I agree with you guys, I am -1 on supporting XP. I just know we can all get amped up about these types of things. I don't know what OS you guys use, but if you are still using windows or have felt the changes along the years, I think you can agree XP was decent compared to future iterations. I don't update my iphone because it works perfectly as is. But yeah, this is a chromium/v8 issue, where its a choice between falling behind in versions or forking chromium (which is more work than it sounds)

to clarify 

-1

**Comment by Anachron** [comment]
Well if we support WinXP still then the WinXP users will argue when some apps work and some don't. I've heard it tons of times and I am sick of it "There are programs that support IE x / Win xy, so we want support for <insert very old product here> too!". It just doesn't make sense, WinXP was good, one of the best operating systems ever made. But its sadly dead, and if you want to revive it, you got to start contacting Microsoft.

**Comment by old9** [comment]
Some good news maybe, *Re-enable Windows XP / 2003 support*, that's on the [io.js v1.0.3 changelog](https://github.com/iojs/io.js/blob/v1.0.3/CHANGELOG.md#2015-01-20-version-103-rvagg).

**Comment by Mithgol** [comment]
This issue should be closed because the switch to io.js didn't cause nw.js to drop Windows XP support.

(Future Google Chrome changes might require the drop, but that's a matter for some other issue.)
