### ISSUE TITLE
Does page-cache persist between app restarts?

### ISSUE THREAD

**Issue by oaleynik** [nwjs/nw.js#2939]
Hi, just wondering - does nw keep cache between app restarts? For me it seems like after restart images are still downloaded from external resources. But if reload page (like in regular browser) images took from cache. Any ideas why it's happening?

**Comment by bartvanheukelom** [comment]
I'm wondering this as well. And if it does persist where?
Since my nw.js app is basically just a viewer to a remote app, I really need the cache to persist.

**Comment by AndryBray** [comment]
:+1:

**Comment by matthew-dean** [comment]
I'm also curious how to invalidate the cache in NW.js.

**Comment by Gimmeaphatbeat** [comment]
This works for me:

var gui = require("nw.gui");
gui.App.clearCache();

**Comment by joshuaterrill** [comment]
I believe it does. I've had issues with caching even after doing an app restart. If you want to clear the cache every time you load your app, do this: ```gui.App.clearCache()```

**Comment by willian12345** [comment]
So, Even i restart my app ,  and cut my network down.  The remote page still show me 

The local page is index.html ,  and The remote page is main.html
```javascript
gui.Window.open('http://b.live.geekint.com/main.html',{toolbar:false,frame:true, focus: true, show: false, width: 1100, height: 600})
```

**Comment by joshuaterrill** [comment]
In my project we have to do a ```clearCache()``` and then ```reloadIgnoringCache()``` to get cache to clear correctly.

**Comment by b1rdex** [comment]
@rogerwang here is some debug info.
Persistent page cache is working in 0.12.0 and is broken in 0.12.3 (didn't tested versions between this two).
Cache folder format changed between this versions and I don't know what real problem is behind this.
0.12.0 have 1 cache entry = 1 cache file; 0.12.3 packages many cache entries to some files.
0.12.0 doesn't clear cache folder on start and uses cache.
0.12.3 clears part of cache files and loads every resource from remote.

Manifest has `webkit: { page-cache: true }` set and it has no difference for 0.12.3.

**Comment by john-hu** [comment]
@b1rdex 
How do you to test it? I had noticed that the last modified time of cache folder was still the same while using 0.12.0. But nw.js doesn't send any `If-Modified-Since` or `If-None-Match` header to web server.

**Comment by b1rdex** [comment]
My app is located remote. Main page have image. It's loaded every time I
restart app. Browser caches this image. Nwjs not.

**Comment by orther** [comment]
Did anyone ever get a solution for this? My nw.js 0.12.3 app isn't caching the remote assets I am loading on app start. If I refresh the app in the DevTools (reload main html rather than restart the app process) the assets are pulled from cache correctly but on app start they always download from remote.

**Comment by bartvanheukelom** [comment]
No, we just implemented our own, which is more reliable and configurable anyway

**Comment by b1rdex** [comment]
@bartvanheukelom could you please provide any details of implementation?

**Comment by bartvanheukelom** [comment]
We get a manifest file from the server, containing a list of all app files and their hashes. Then we download the missing or mismatched (based on the hash) files to the local appdata directory, and launch using the local files.

**Comment by orther** [comment]
It looks like I'll be implementing the same type of fix. Thanks for
explaining your solution @bartvanheukelom

On Wed, Feb 24, 2016 at 1:35 AM, Bart van Heukelom <notifications@github.com
