### ISSUE TITLE
[0.12.0-alpha2] Devtools window is shown even in headless mode

### ISSUE THREAD

**Issue by felicienfrancois** [nwjs/nw.js#2976]
Tested with the snippet from https://github.com/nwjs/nw.js/wiki/Devtools-jail-feature#headless

The event "devtools-opened" is called with the devtools url but the devtools window is shown in any case.

This is a regression from 0.11
##

**Comment by ghostoy** [comment]
Headless devtools is currently disabled.

**Comment by felicienfrancois** [comment]
FYI, I used the following workaround:

In __package.json__
`"chromium-args": "--remote-debugging-port=9222"`

Then open `http://127.0.0.1:9222/` or `http://127.0.0.1:9222/json` to get list of devtools

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.
