### ISSUE TITLE
Trouble in installing nw.js

### ISSUE THREAD

**Issue by nidhin001** [nwjs/nw.js#3016]
Hi, I'm having trouble in installing nw.js. I just extracted the nw.js package and then tried to execute the nw executable file and its now executing. I tried executing "/path/to/node-webkit/nw /your/project/folder". But then I'm getting the following error "error while loading shared libraries: libudev.so.1: cannot open shared object file: No such file or directory" Where did I went wrong ?

**Comment by rogerwang** [comment]
please check https://github.com/nwjs/nw.js/wiki/The-solution-of-lacking-libudev.so.0

**Comment by nidhin001** [comment]
I tried the second one 'Modify the nw binary itself' and executed the command  'sed -i 's/udev\.so\.0/udev.so.1/g' nw'. But that doesn't make any change.

**Comment by felicienfrancois** [comment]
That's the opposite issue you're facing:

https://github.com/nwjs/nw.js/wiki/The-solution-of-lacking-libudev.so.1

**Comment by nidhin001** [comment]
I tried running the shell script in debian 64 bit machine and got this error "version `GLIBC_2.14' not found".  I tried to install GBLIC but not successful. How to get rid of this ?

**Comment by felicienfrancois** [comment]
Maybe you should create another issue for this problem.
One of my app users reported the same issue on debian stable.

This is due to the libc6 version shipped in Debian stable is the v2.13 (very obsolete one) whereas most others distros ships v2.15 or newer.

v2.14 or newer is required by a lot of common programs.

You can probably fix it by installing glibc from debian testing (I've not tested myself):
`apt-get -t testing libc6-dev libnss3-dev`

**Comment by nidhin001** [comment]
@felicienfrancois  apt-get -t testing install libc6-dev worked for me
