### ISSUE TITLE
Style Developer Tools window

### ISSUE THREAD

**Issue by NetOperatorWibby** [nwjs/nw.js#3017]
Right now, it is possible to customize the chrome of your default window, thanks to the `toolbar` line in `package.json`. Could this also be applied to the Dev Tools? I would like to call this window when it's behind my main window too, but there is currently no way of doing that.
##

**Comment by RIAEvangelist** [comment]
you can call the devtools window with win.showDevTools();

            app.data.gui = require('nw.gui');
            app.data.win = app.data.gui.Window.get();
            app.data.win.showDevTools();

I do this as well to get the F12 functionality

                window.addEventListener(
                    'keyup',
                    function(e){
                        if(e.keyCode!=123){
                            return;
                        }
                        app.data.win.showDevTools();
                    }
                );

**Comment by NetOperatorWibby** [comment]
The headless instance thing confuses me. I've tried variations of the code you provided (which is also in the wiki), with no luck. Hopefully I will be able to stumble upon a solution.

**Comment by RIAEvangelist** [comment]
What part confuses you?

**Comment by felicienfrancois** [comment]
Headless devtools does not work in latest release (0.12-alpha2) #2976
Use previous version (0.11) or use the workaround 2976#issuecomment-70808045

**Comment by NetOperatorWibby** [comment]
@RIAEvangelist The fact that it wasn't working when I copied and pasted the code.

@felicienfrancois I thought about using that workaround and tried to do it, but I couldn't get multi-instance working. I was trying to open a new window with the custom debugging URL I have specified in my `package.json`.

**Comment by RIAEvangelist** [comment]
@NetOperatorWibby if you had put in a bit more effort than just copy paste and roll over you might have gotten it. Let me give you something so that you don't have to think, or read the documentation which is quite clear. That way you can just copy paste it and tweak my code instead of writing your own :

            app.data.gui = require('nw.gui');
            app.data.win = app.data.gui.Window.get();
            
            app.data.win.showDevTools(false, true);
            app.data.win.on(
                'devtools-opened', 
                function(url) {
                    console.log("devtools-opened: " + url);
                    var tools=document.createElement('iframe');
                    tools.src = url;
                    document.querySelector('body').appendChild(tools);
                    tools.style.background='black';
                    tools.style.position='absolute';
                    tools.style.top='0px';
                    tools.style.left='0px';
                    tools.style.width='100%';
                    tools.style.height='100%';
                    tools.style.border='none';
                    tools.style.color='white';
                }
            );

![Custom dev tools screenshot](http://i.imgur.com/ltEkaHy.png?1)

**Comment by NetOperatorWibby** [comment]
@RIAEvangelist What the hell is your problem? I clearly stated (https://github.com/nwjs/nw.js/issues/3017#issuecomment-72389032) that I tried various implementations of that code and I couldn't get it to work. @felicienfrancois also mentioned that the functionality I want is disabled in the latest version of NW.js, which is what I am using. Your attitude and tone of voice was unnecessary. Maybe you're a Seahawks fan?

I've never thanked an asshole before, but I suppose I should thank you for the code. I'll keep it in mind. When you're not busy with dealing with sticks stuck up your ass, you can check out my browser project (https://github.com/IdeasNeverCease/Aries). When the headless tools regression gets fixed in the next version of NW.js, I'll implement the custom Developer Tools chrome I want.

@felicienfrancois Thank you for actually being a positive force in the Universe.

**Comment by RIAEvangelist** [comment]
@NetOperatorWibby  My response was due to the answer you gave when I asked 
` What part confuses you? `... 
you're answer was direct, clear and simple in [ this comment ](https://github.com/nwjs/nw.js/issues/3017#issuecomment-72883235) 
` @RIAEvangelist The fact that it wasn't working when I copied and pasted the code. ` 

Had you given some other answer perhaps it would have been more confidence inspiring and seemed that you were confused by more than cutting and pasting. Then I could have helped with your specific issue. However since the issue you gave to my question on your confuson was ` wasn't working when I copied and pasted the code. ` perhaps you can better understand my answer. Which was directly answering the issue of not having code that would work with copy paste.

Your welcome for the code, hope it helps you on your way. Also, yes I'm an ass sometimes, but think how you would react if someone said I am confused because it doesn't work when I copy paste it... Your probably not as big an ass as me so you might be more politically correct about it, but I hope in future questions or answers you NEVER say ` because it didn't work when I copied and pasted ` but rather elaborate slightly more to tease the exact help from the person who is helping you.

Also, you can get the devtools to open in the 0.12 alpha. they don't work, but setting topframe to true on the iframe will allow them to load, next you get denied by the websocket. In any case though you can see and modify the basic format of the tools. I reccomend developing against  11.6 for now as the 12 candidates are really unstable. The same is true if you open a live preview from brackets (which I know you love) and then use that url as your main file and allow node-remote in the package. Either way you get to see the basic tools. but the topframe is easier since neither way gives actual dev control.

![](http://www.reactiongifs.com/wp-content/uploads/2013/11/1106.gif)

I'll checkout your repo. Perhaps less assholishly.

**Comment by NetOperatorWibby** [comment]
:+1:
