### ISSUE TITLE
Crash on removing MenuItem of type separator at index 0 on tray menu.

### ISSUE THREAD

**Issue by waltfy** [nwjs/nw.js#3022]
Removing the first item from a `Tray.menu` causes the application to crash with the following error:

`Check failed: static_cast<size_t> (index) < items_.size() (1 vs. 0)`

To reproduce you can [use these files](https://gist.github.com/waltfy/5e979a0942129611eddc) and play around with the provided interface. Doing the following, will definitely cause a crash on `Windows`:
1. Click on `+ Separator`.
2. Click on `Remove All`.

I have tested on `OSX` and the issue is not present. Currently unsure what the situation is on Linux.
##

**Comment by waltfy** [comment]
![demo](https://cloud.githubusercontent.com/assets/1257595/5961246/32b85a68-a7d3-11e4-80d1-f40282adb587.gif)

**Comment by eugirdor** [comment]
I am having the same issue in a slightly different use case. Mine is happening on `Window.menu` instead of `Tray.menu`.  Issue appears to happen when modifying the menu items after the menu has been assigned to the window.  Code runs fine on OS X and crashes on Windows (untested on Linux) with following error:

```
[3980:0220/134515:FATAL:simple_menu_model.cc(439)] Check failed: static_cast<size_t>(index) < items_.size() (5 vs. 5)
```
