### ISSUE TITLE
Undefined functions will cause the whole application crash.

### ISSUE THREAD

**Issue by tony0918** [nwjs/nw.js#3028]
On node side, if using some undefined functions will cause the whole application crash.
Such as `console.trace()`

**Comment by RIAEvangelist** [comment]
I believe this is expected functionality isn't it?

Doesn't node always crash if you don't handle the error?

If one piece crashes the whole thing will.

I suggest fixing the bug that causes the crash, or if you REALLY want to be lazy, you could handle all uncaught errors with

            process.on(
                'uncaughtException', 
                function(err){ 
                    console.log('node-webkit error which I should fix but don't want to right now :  ', err); 
                }
            );

**Comment by mrfabbri** [comment]
I stand with @RIAEvangelist this is the expected behaviour and follows the general suggestions (wrt error handling) one can find in https://www.joyent.com/developers/node/design/errors, i.e. generally you want to fail quickly and loudly when a programmer error –using an undefined function– (vs. an operational error) happens.
