### ISSUE TITLE
Memory leak with iframe

### ISSUE THREAD

**Issue by Aizenko** [nwjs/nw.js#3069]
Hi,

Got an appli which loop loading media (html) into 2 iframe. The amount of memory taken by nw is growing steadily. If i force a reload of the page it release the memory.
In the webkit tools the heap memory does not seem to grow, and in the memory seems to be released. The heap snapshop stays around 5Mo but the processes still grow.
Is there a workaround ? 
On windows 7 even if I reload regurlarly the page the process continue to grow.... On Ubuntu it's less dramatic.

**Comment by kamesh-a** [comment]
+1

**Comment by Aizenko** [comment]
The version I got on Osx doesn't seem to have this problem (0.10.5).

**Comment by Aizenko** [comment]
I'm affraid that's a problem which won't be corrected soon (cf this chromium bug [270000](https://code.google.com/p/chromium/issues/detail?id=270000&q=iframe%20leak&colspec=ID%20Pri%20M%20Week%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified
) 
It make nodewebkit unusable for what I wanted to do with it... :-(

**Comment by rbfowler9lfc** [comment]
I noticed the same behavior on my app, in my case the rss size grows at each page loaded. A dead simple scriptless html page linking to another similar page keeps increasing rss in the order of 5mb if you keep navigating back and forth until nw crashes out of memory. Interestingly enough, if you fire Window.reloadDev() at any time the rss drops to its initial size.

**Comment by rbfowler9lfc** [comment]
@Aizenko what about loading content with AJAX instead of using iframes? I had a layout similar to yours using iframes to load dynamic content and I could significantly reduce the memory waste by ditching iframes wherever it was possible.

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.

**Comment by mangaga** [comment]
This should be working with latest version now.   The latest version means version 0.15.x ?
