### ISSUE TITLE
Snippets in Dev tools not saved

### ISSUE THREAD

**Issue by mikeptweet** [nwjs/nw.js#3136]
If I load nw.exe, create a new snippet in devtools, save it and exit, it is gone when I reload nw.exe

How can I enable it to save code snippets?
##

**Comment by remss** [comment]
Same thing with breakpoints, they are lost across NW runs. (nwjs 0.12.1)

**Comment by kamesh-a** [comment]
Upon adding --remote-debugging-port=<port-number> the snippets and
breakpoints will be save across each app load. currently nwjs debugging
port number is random so, its unable to load previous breakpoints/snippets
because ports are changing.
{
    "chromium-args": "--always-enable-dev-tools
--remote-debugging-port=9555",
    "window": {
        "frame": true,
        "height": 700,
        "min_height": 700,
        "min_width": 1152,
        "position": "center",
        "show": true,
        "toolbar": true,
        "width": 1152,
        "kiosk":false,
        "fullscreen":false
    }
}

Hope this helps !!

On Tue, May 5, 2015 at 8:44 PM, remss <notifications@github.com> wrote:

> Same thing with breakpoints, they are lost across NW runs. (nwjs 0.12.1)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nwjs/nw.js/issues/3136#issuecomment-99111370>.
>



-- 
Thanks,
Kamesh.

**Comment by Christywl** [comment]
I can't reproduce on nwjs-sdk-v0.24.0. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
