### ISSUE TITLE
How to keep temporary folder on running

### ISSUE THREAD

**Issue by aretias-kr** [nwjs/nw.js#3156]
Temporary directory can be deleted by cleaner apps on running
after cleaning, resources can't be access by my nw.js app such as html, js, images

Can I keep temporary folder on running?

**Comment by baconface** [comment]
The only reliable fix if you don't mind it would be to make a directory in your app's executable directory. Then you make a NW.js project that redirects to it but doesn't package it. And put your application files in there. Otherwise a lot of these resource cleaners usually support deletion of locked files.

**Comment by rogerwang** [comment]
@aretias-kr  you can consider redistribute the tree without zipping it. NW support this "package" format.

**Comment by aretias-kr** [comment]
@baconface @rogerwang Thanks for your comments. I'm gonna considering about another support package format. Actually, I don't have experience about package without supporting libraries. Only with nodewebkit-builder.
