### ISSUE TITLE
keeping memory usage low when running 24/7

### ISSUE THREAD

**Issue by mscreenie** [nwjs/nw.js#3190]
Does anybody have any suggestions on keeping memory usage low when using nwjs? I've found myself a problem when nwjs is open for 2-3 days with two or three YouTube video running fullscreen and playing after another on a loop.

I think it's because YouTube's API writes a new Iframe each time a video is played. After 3 days total mem usage is up to **2.3 GB**, I've been thinking about restarting the application when this is reached but I don't think thats a good long term solution. 

Appreciate any input.
##

**Comment by PierBover** [comment]
Maybe the garbage collector isn't collecting those iframes because your not releasing the HTML properly.

**Comment by mscreenie** [comment]
Could you suggest a good way to cycle through Iframes that allow garbage collector to recover memory? 

Currently I'm using jQuery to cycle through Iframes and toggle css display property.

**Comment by PierBover** [comment]
So you have a big list of hidden iframes that you are switching on and off?

Instead of that you should create and destroy those iframes dynamically. To destroy an HTML element with jQuery you use `.remove()` which will not only remove it from the DOM, but also remove any events attached to it. If there are no other vars referencing that iframe, then it should be garbage collected at some point.

http://api.jquery.com/remove/
http://stackoverflow.com/questions/11042492/jquery-remove-and-memory-leaks

**Comment by mscreenie** [comment]
Great, I'll amend my code and see how .remove() impacts memory usage. I'm interested in using nwjs for digital signage applications - I wouldn't be surprised if someone is already.

Your input is greatly appreciated. Will report back.

**Comment by stwiname** [comment]
Did this work? I'm having large memory usage when changing the source of an iframe

**Comment by mscreenie** [comment]
Looks like memory is never recovered when changing the source or destroying the iframe element. I've had to change my app model to work around this. 

I read somewhere 12.2 supported the webview tag and also webviews can be configured to spawn separate processes provided you don't need nwjs functions. 


I haven't tested webviews yet and memory management / collection.

**Comment by mscreenie** [comment]
Should be able to manage memory better with webview. Closing.
