### ISSUE TITLE
How to get http headers from opened window?

### ISSUE THREAD

**Issue by dexcell** [nwjs/nw.js#3208]
Let's say i open a website in new window using code like this:
````
var win = gui.Window.open('https://github.com',);
````
Can i get the http response headers from github? if so, how?

Thank you

**Comment by felicienfrancois** [comment]
NWJS Github is reserved to bug reporting and features request.
For questions, please post to [google group](https://groups.google.com/forum/#!forum/nwjs-general)

To get response headers, you can use [chrome webRequest API](https://developer.chrome.com/extensions/webRequest) which is available in NWJS since 0.12.0

**Comment by dexcell** [comment]
Sorry, thank you for your response, i will post there.

If you don't mind please elaborate, or give some simple example
Here is the thread
https://groups.google.com/forum/#!topic/nwjs-general/cK3rXac2MPE

Thank you
