### ISSUE TITLE
[Mac] nb.pak file not found

### ISSUE THREAD

**Issue by tnViking** [nwjs/nw.js#3218]
I just created a new project, but every time I compile it, I get:
```
[18983:0311/112340:WARNING:shell_main_delegate.cc(231)] nb.pak file not found.
[18984:0311/112340:WARNING:shell_main_delegate.cc(231)] nb.pak file not found.
[18985:0311/112340:WARNING:shell_main_delegate.cc(231)] nb.pak file not found.
[18986:0311/112341:WARNING:shell_main_delegate.cc(231)] nb.pak file not found.
```
I'm compiling on OS X 10.10.2, with the latest node and nw. And my language of OS is Norwegian Bokmål.
How can I fix this?

**Comment by TeddyBones** [comment]
I'm experiencing this problem as well. My OS language is Norwegian Bokmål.

**Comment by georgelanes** [comment]
I have the same problem. The workaround is duplicate the pak file and rename to lang file. In my case is pt-BR the window.navigator.language return pt only. So I have duplicate the file pt-BR.pak and rename to pt.pak. 
You can find this files on nwjs.app/Contents/Frameworks/Resources folder.

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.

**Comment by yueqianW** [comment]
I am a chinese developer,I'm compiling on OS X 10.12.6, with the latest node and nw v0.12.3,and I meet the same question,it‘s warning "zh-Hans-CN.pak file not found" ,and the console is nothing,I can't get any information from nw's console.So I duplicate the file zh-CN.pak and rename to zh-Hans-CN.pak,it doesn't work.I don't know why.
