### ISSUE TITLE
MAC OS X Yosemite, Develop / Distribute

### ISSUE THREAD

**Issue by A-Monkey** [nwjs/nw.js#3243]
I just got one question, is it really this simple or have I missed something... ?!
To run the program, I just double click the nwjs.app (renamed hello).
To have a complete finished product for mac I just put the files inside the contents/resource folder.
Now I have a single executable app !! 

Develop:
![2](https://cloud.githubusercontent.com/assets/6350636/6665309/502321ea-cbd8-11e4-8eaa-e065a93daa59.png)

Distribute : 
![1](https://cloud.githubusercontent.com/assets/6350636/6665300/3610f58e-cbd8-11e4-8d73-cc5bd41c4db5.png)

**Comment by alexeyst** [comment]
To ensure successful distribution to other computers running OS X you’d have to sign it with an Apple OS X developer certificate and either create a dmg/pkg for installation or distribute through Mac AppStore, otherwise your end users might have a trouble running the app in the first place. 

Also, you will probably want to edit the `Info.plist` file to reflect your unique bundle ID within the app and potentially helper apps (if you want to submit to Mac AppStore), create an app icon, etc.

There are many tools that help automate the process, like [this](https://github.com/mllrsohn/node-webkit-builder) one. See the more or less complete list and process [here](https://github.com/nwjs/nw.js/wiki/How-to-package-and-distribute-your-apps).

Although possible, it will display an unwanted message that the app is coming from an untrusted developer.

**Comment by A-Monkey** [comment]
Hi Alex,

Thanks for reply and info.

The nwjs is already an fully functional app. (nwjs.app).
Change name, icons and info(Info.plist), put all your content in contents/resource then run disk utility (in mac)
to create a dmg file. Done !

To distribute to Mac AppStore i guess you need developer certificate and so on, 
but to a friend, hey here you go.. ; )

Thanks, this is really fun, it´s like html on steroids superpowered by node ; )
