### ISSUE TITLE
How to call IE browser? [$5]

### ISSUE THREAD

**Issue by fjyans** [nwjs/nw.js#3244]
Bank of China mandatory to use IE.Bank of China mandatory to use IE. But I do not know how to run IE browser

**Comment by baconface** [comment]
Are you talking about accessing the site within a NW.js project? Spoof the headers and see if that helps. If it has IE specific technology you might run into issues. Otherwise try setting ```user-agent```  to one of the user strings found on http://www.useragentstring.com/pages/Internet%20Explorer/ and see if it tricks their validation check.

**Comment by fjyans** [comment]
I do not need to use the user-agent, all I need is to click on a link to be able to use another browser to open this link

**Comment by shaynem** [comment]
jquery example - add ID to your element <a id="blah">click here</a>

$('#blah').on('click', function() {
return gui.Shell.openExternal('https://link.com');
}

You can use inline with your HTML also. It wont specifically open in IE it
will open in the default browser.
