### ISSUE TITLE
v0.12.0 does not run when package.json name contains hyphen

### ISSUE THREAD

**Issue by rot1024** [nwjs/nw.js#3276]
NW.js v0.12.0 does not run when package.json name contains "-" (hyphen)

e.g.

``` json
{
  "name": "foo-bar",
  "main": "index.html"
}
```

I tried on Windows7 64bit SP1.
##

**Comment by rdtsc** [comment]
Cannot reproduce this on either 32- or 64-bit builds on W7 x64 (en-US).

What happens if you remove the app's cache directory?
```batchfile
rmdir /S /Q %localappdata%\foo-bar
```

**Comment by baconface** [comment]
I cannot reproduce this error with the 32-bit or 64-bit builds on W8.1 x64.

**Comment by rot1024** [comment]
I solve it. 
I killed invisibly remaining nw.exe processes and deleted cache directory. 
I think that's because these processes remained, so cache directory was locked. 
Thank you for your trouble.

**Comment by xy124** [comment]
also happens on ubuntu 64bit,
```bash
$ nw --version
> nwjs 51.0.2704.22
```
Please could you fix it so that an error message is shown that gives a hint? (Took me half an hour to find the error as it always said 
```bash
Created new window in existing browser session.
```
and then closed)

**Comment by callahanp** [comment]
The problem persists.  A hung nwjs session 

~/workd/nw/lorikeet-nwjs$ nw
[0516/065228.840918:WARNING:chrome_main_delegate.cc(565)] final extension: 
Created new window in existing browser session.
user@node:~/workd/nw/lorikeet-nwjs$

No window appears

ps aux|grep nw

user      6801  0.0  0.6 3183204 106688 pts/0  SLl  06:50   0:00 /usr/lib/node_modules/nw/nwjs/nw .
user      6803  0.0  0.2 344872 40104 pts/0    S    06:50   0:00 /usr/lib/node_modules/nw/nwjs/nw --type=zygote --no-sandbox --enable-crash-reporter=, --user-da
user      6835  0.0  0.4 840348 75640 pts/0    Sl+  07:26   0:00 /proc/self/exe --type=gpu-process --field-trial-handle=1 --no-sandbox --enable-crash-reporter=, --user-data-dir=/home/pac1/.config/lorikeet --nwapp-path=. --supports-dual-gpus=false --gpu-driver-bug-workarounds=7,19,23,42,50,54,63,74,85,87,93 --disable-gl-extensions=GL    
user  6838  0.0  0.4 1746432 81032 pts/0   Sl   06:50   0:00 /usr/lib/node_modules/nw/nwjs/nw --type=zygote --no-sandbox --enable-crash-reporter=, --user-da

kill -9 6801
nw
[0516/072651.267050:WARNING:chrome_main_delegate.cc(565)] final extension: 

Window now appears.

To reproduce this you must use ctrl/c to cancel a running nw js program that is incorrectly set up.
Steps to reproduce:
1.  Edit package.json - change index.html to index.js 
2. Run nw
3. See error message about missing index.js: Failed to load extension from /home/user/workd/nw/lorikeet-nwjs. Could not load background script index.js.
3a come to the wrong conclusion about why index.js is "missing"
4. touch index.js
5. Run nw
6. Observe message including " Created new window in existing browser session."
7. ctrl/c
8. ps aux|grep nw
9. observe still running processes
10. run nw
11. observe message [0516/074358.739346:WARNING:chrome_main_delegate.cc(565)] final extension: 
  Created new window in existing browser session.

The fix:
ps aux |grep nw
kill the still running parent nwjs process
ps aux |grep nw to make sure they all died
fix the package.json to point to html instead of js or whatever other error caused the processes to remain.

I did not have to consider any cache directories.

**Comment by Christywl** [comment]
I can't reproduce on Linux/windows with nwjs-sdk-v0.24.0. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
