### ISSUE TITLE
windows universal support

### ISSUE THREAD

**Issue by shaynem** [nwjs/nw.js#3284]
Is it possible? or has anyone with more knowledge looked into anyway to have NWJS work with Windows universal platform development for the upcoming windows 10 release?
##

**Comment by justinmchase** [comment]
I'm pretty sure it won't work. The universal platform on the desktop hasn't fundamentally changed from win8, they just added some more features and bug fixes, etc. It supports WWA apps, which, unfortunately are quite different. When making C++ apps you can't just link to any library you want, it's pretty limited. You can't even link to Microsofts own Chakra libraries, and there is even less hope for v8.

You could simply use WWA and then do a lot of abstracting away to make a maximum amount of your code run in both nwjs and wwa.

**Comment by shaynem** [comment]
Thank you very much for your insight. I'll do some research on WWA it's for
a VPN application so as long as I can access native VPN apis I should be
able to make it work at least on mobile and tablet and have separate app
for desktop using nwjs which we currently been doing for the past year.

Just not sure if it's worth it... I guess it depends on the uptake of
Windows 10 mobiles and tablets.

**Comment by justinmchase** [comment]
Windows 8.1 and 10 have built-in VPN... And they almost certainly don't have apis in the univeral apps for vpn's. You could use nw.js to do it, with native modules. It will be a desktop app though instead of a universal app. It probably won't work on arm tablets though.

But windows has built in vpn features, what exactly are you trying to do that windows doesn't already do?
