### ISSUE TITLE
How can I force the initial window to open in the foreground?

### ISSUE THREAD

**Issue by chevex** [nwjs/nw.js#3298]
During development when I run my app it always starts behind my terminal window. Is there a simple way to force it to open in the foreground?

**Comment by rdtsc** [comment]
To answer your question: call [`Window.focus()`](https://github.com/nwjs/nw.js/wiki/Window#windowfocus) on `DOMContentLoaded`, or whenever is appropriate. For example:
```javascript
require('nw.gui').Window.get().focus();
```
That said, the behavior you describe seems strange. Window managers typically give focus to newly spawned windows without issue. Did you verify that your terminal window(s) aren't set to "Always on Top" mode?

**Comment by mackwic** [comment]
@rdtsc I confirm the issue under osx 10.9, and iTerm2.app. No window focus and the terminal isn't in "Always on Top". When I do alt-tab, the new nwjs is at the end of the list.
This happens only on our dev setup (running `node_modules/nw/bin/nw ./app/`).
It doesn't happens when running `~/app.app/Content/MacOS/nwjs ~/app.app/Content/Resources/app.nw`, neither when running directly `open ~/app.app`. It doesn't happens on Linux.
I think it's some kind of misconfiguration on my part, so I didn't submit an issue.

**Comment by chevex** [comment]
@rdtsc thanks! Calling `.focus` works to bring it to the front when I start it. I'll have to do some poking around because I use livereload and now it comes to the front whenever I save changes :P

I have the same setup as @mackwic.

![image](https://cloud.githubusercontent.com/assets/874394/6854874/87ab25e8-d3b9-11e4-95ce-be4edc27f630.png)

I also use iTerm2. Even the simplest hello world app created with nwjs opens behind the iTerm2 window so I don't think it's a misconfiguration on my end, but feel free to correct me if I'm wrong.

**Comment by rdtsc** [comment]
@mackwic and @chevex : This doesn't look like an issue with NW.js specifically, as executing the following in a terminal also exhibits the behavior you describe:
```bash
/Applications/Calculator.app/Contents/MacOS/calculator
```
In our case, the `nw` module appears to call the NW.js equivalent of the above (see `nw/lib/findpath.js`).

Running a binary through the `open -a` command, however, results in the expected behavior where the newly spawned window is injected into the top of the Window manager's z-stack:
```bash
open -a /Applications/Calculator.app/Contents/MacOS/calculator
```

Perhaps try patching your start script(s) to leverage `/usr/bin/open -a`, instead? I don't know much about OS X to be of any further help, unfortunately.

---

@chevex : Regarding your live-reload situation -- you should be able to use the `node-main` manifest field as a workaround. Here's a small example:

#### package.json
```json
{
  "name": "nwjs-focus-test",
  "main": "index.html",
  "node-main": "devenv.js"
}
```

#### index.html
```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="refresh" content="1">
    <title>NW.js Focus Test</title>
  </head>
  <body>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        document.body.innerHTML += Math.random();

        // Only focuses the window once.
        process.mainModule.exports.focusWindow();
      });
    </script>
  </body>
</html>
```

#### devenv.js
```javascript
(function() {
  var isFirstRun = true;

  exports.focusWindow = function() {
    if(isFirstRun) {
      window.require('nw.gui').Window.get().focus();
      isFirstRun = false;
    }
  };
})();
```

**Comment by chevex** [comment]
@rdtsc Awesome! That's exactly what I need. A script that runs only on startup and then never again :) Thanks!

No worries about the other issue. I didn't even think much of it until you said it shouldn't be happening like that. I'm happy with the focus solution :)

**Comment by vizworkshop** [comment]
On my Windows 10.1 box with nwjs-sdk-v0.24.0 if I open the nw.js window, then click on another app, then call win.focus(),  the nw.js window is not brought to the front.  

Working around this with win.setAlwaysOnTop(true) for as long as I need the window up front.

**Comment by GSBeast** [comment]
On my Windows 10.1 box with nwjs-sdk-v0.24.0 if I open the nw.js window, then click on another app, then call win.focus(), the nw.js window is not brought to the front.

Working around this with win.setAlwaysOnTop(true) for as long as I need the window up front.
