### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by mn1aC** [nwjs/nw.js#3338]
Hi,

i'm running the 0.12.0 on win32/win7 with exceljs plugin and works fine. 

On a 64bit machine running the same code (32bit compilation), the app crashes  Sometimes. I can't find why because there is no debugging information. Even though I have added

// Load native UI library
var ngui = require('nw.gui');

ngui.App.setCrashDumpDir("logs");
##

**Comment by mn1aC** [comment]
It seems to be that debugging information is not available in 0.12.0...

**Comment by mn1aC** [comment]
In the mean time I know for sure it has something todo with the fact that i'm loading a webapp in an iFrame. and then pass node functions to the iFrame, such that the webapp (js-code) could call node functions.

Does anyone know how to do this properly such that it doesn't crash?

**Comment by mscreenie** [comment]
Experienced similar since 12.0 , however only when I close the app using a button which runs gui.App.quit, fails to close and gives me Windows error collector message, doesn't happen often but can never predict it or reproduce when I want to, I'm loading content and node functions from the Iframe if that helps.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
