### ISSUE TITLE
"-webkit-app-region: drag" not work in iframe?

### ISSUE THREAD

**Issue by wufeng87** [nwjs/nw.js#3367]
Is it normal that the css "-webkit-app-region: drag" not work in iframe?
##

**Comment by gihrig** [comment]
This has been my experience.

My solution was to create a transparent div in the parent document, and position that in front of the iframe using the css z-index property. I just needed to drag the whole window, so I positioned my transparent div at the top 20px of the page.

In my case the iFrame covers the entire viewport/browser window.

Note that any controls on the iFrame covered by this div will not be accessible. That's why only 20px at the top.
