### ISSUE TITLE
Drag and Drop windows admin right

### ISSUE THREAD

**Issue by ethaMont** [nwjs/nw.js#3445]
Hi there,

I noticed an issue about drag and drop when executing the app as an administrator on Windows.
The cursor is blocked, and you can drop anything from the filesystem to the app. 

I thought it was my code, but I created a new project with the tutorial available on the wiki, and the issue is the same. 

The same code, executed as an user work, but doesn't work executed as an administrator. 

Is there any particular code to add somewhere ? 

Thanks in advance

**Comment by ComSecNinja** [comment]
This may have something to do with the Windows' *User Account Control* (UAC). Because the application is being executed with administrative rights but the drag event – and the file – is coming from a non-admin source it is considered "unsafe" and is being prohibited. This could be easily proven by opening the *Windows Explorer* as admin (Start Menu, type "explorer", right-click it and run as administrator) and trying to drag and drop from there, but [you can't actually elevate the explorer privileges that way](http://superuser.com/a/59106). It **should** prompt the user like any other action that requires privilege elevation, I think.

I don't have an actual solution for your problem but you may have to consider separating the functions that require administrative rights from the file system related activities that do not.

**Comment by ethaMont** [comment]
Thank you for this complete answer!
