### ISSUE TITLE
about uac

### ISSUE THREAD

**Issue by xiaojiantang** [nwjs/nw.js#3448]
how can i elevate uac in nodewebkit ?because i want to get File permissions,thanks

**Comment by shaynem** [comment]
The below might not be what your after (as you might not want to always run
as Administrator) and i don't fully understand the question but it might
point you in the right direction.

If you need to run as Administrator  (I'm not sure what you mean by File
permissions, but obviously Administrator would alleviate these issues,
instead of having to right click "Run as Administrator")

you need mt.exe from the Windows SDK  (
http://stackoverflow.com/questions/1423492/how-do-i-add-a-manifest-to-an-executable-using-mt-exe
)

then create a manifest file like the below name it YOURAPP.manifest

you run the MT command on the resulting .exe file, either the nw.exe or a
packed exe using enigma virtual box

https://github.com/nwjs/nw.js/wiki/How-to-package-and-distribute-your-apps


<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <assemblyIdentity version="1.0.0.0" processorArchitecture="X86"
name="YOURAPP" type="win32"/>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="requireAdministrator"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <dependency>
    <dependentAssembly>
      <assemblyIdentity
          type="win32"
          name="Microsoft.Windows.Common-Controls"
          version="6.0.0.0"
          processorArchitecture="*"
          publicKeyToken="6595b64144ccf1df"
          language="*"
        />
    </dependentAssembly>
  </dependency>
</assembly>

**Comment by xiaojiantang** [comment]
Thank you shaynem, your solution worked.

**Comment by c0bra** [comment]
This doesn't because mt.exe clobbers the end-of-file contents that nw.exe houses. At least it does inthe version of node-webkit I'm using.

After using mt.exe my nw.exe file is about 20MB lighter and all I get is the blank "Node-Webkit" screen in ascii art.

**Comment by HUN73R13** [comment]
easiest way I found is using a free tool called "Resource Hacker"

install RH, right click nw.exe and click on "Open using Resource Hacker"
click on manifest and look for this part `<requestedExecutionLevel level="asInvoker" uiAccess="false">` now just replace `asInvoker` with `highestAvailable`

you can also edit version info and change icon this way
