### ISSUE TITLE
window.onblur event is not firing on Mac

### ISSUE THREAD

**Issue by drikin** [nwjs/nw.js#3463]
I confirmed this behavior on v0.12.1 on Mac.
When my nwjs application becomes inactive by switching application(e.g. by command+tab), window.onblur event never happen. It's working well on Windows.

I believe Windows behavior is correct.

**Comment by bcalik** [comment]
I just came here to report the same issue. I'm glad to see that I'm not alone.

It just never fire the window.onblur event. I tried bluring, minimizing, hiding, etc. None of them worked.
I have only tested on OSX Mavericks.

**Comment by orther** [comment]
Did anyone ever find a solution to this? I am having the same issue with v0.12.3 and curious if this has been fixed of if there is a work around.

**Comment by bcalik** [comment]
@orther Just use [Electron](http://electron.atom.io).

**Comment by rogerwang** [comment]
This should be working with latest version now.

**Comment by rogerwang** [comment]
In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/  and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.
