### ISSUE TITLE
[discussion] Thoughts on protecting source code when packaging for distribution

### ISSUE THREAD

**Issue by eabovsky** [nwjs/nw.js#3505]
Hey everyone,

After doing a bunch of reading on distribution best practices for protecting source code, it seems like the options available aren't super robust yet. It's my first go-around at this, so apologies if I'm being naive.

Anyways, since the v8 snapshotting approach has some size limitations on the script size and performance, I had a thought on a "hybrid" protection approach:

Also please note that my app is primarily for running in browser context, not node context.

Anyways, what I was thinking is:

1. During packaging, have a grunt process that uglifies/minifies my code just as if I were building it for a website distribution.
2. As an additional step at the end, run an encryption process on the generated file.
3. Build a very small decrypt script that has the encryption key built into it. Turn this script into a V8 snapshot.

Then, when the app launches, on start-up, it would basically use that snapshot to decrypt the main code payload file and eval it.

Anyone have thoughts on this approach?

Also - any ideas on how to protect the package.json file? I think it would be easy for anyone to potentially modify that from a distro to do something like enable the toolbar and get access to the developer tools. I'd like to be able to guard against that if possible.

-Eugene

**Comment by baconface** [comment]
You do realize when you execute an NW.is project it unpacks to a temporary dir? You can minify, uglify, obfuscate all you want. In the end I can extract your entire directory and load it into the browser/dev tools of my choice. If you are talking about protecting the source for security reasons you need to get in the mentality that you are creating a website and your use has full access to the front end. You will only protect code if it is server side and connecting to the logic/data via remote calls. All other methods will make it hard and deter a lot of people but ultimately won't stop them from having access.

**Comment by baconface** [comment]
Ref: #3404

**Comment by overlookmotel** [comment]
@eabovsky I've been thinking along the same lines as you. Did you get anywhere with this idea?

Yes, it's not perfect - a determined attacker could always find a way to circumvent whatever protections you want to try to put in place. But this seems to me a decent compromise - not having your source code in plain text in the package and also not taking the performance hit of packaging the whole application as a snapshot.

Anyway, I wondered if you managed to implement it? Or found a way to prevent access to the developer tools?

**Comment by EZaca** [comment]
Hello, everyone! Sorry for any English mistake, but I will try to join the discussion by criticizing to points.

About the **server protection**, I don't think it should not be an option to NWJS.
I think the idea to force open source should be browser-only and the server way to protect one's application seems not valid here.
See my case: I want to develop a game, but I am a better Javascript developer than a C++ or C# developer. Today it is not safe to develop a paid game with NWJS and Canvas or WebGL. At least, it is not safe like compiling to binary because the source will be entirely open/exposed and what license should I use to protect the source I am giving away? Most licenses protect against reverse engineering and disassembling, but it is not the case when the source is exposed.

**Built-in encryption** seems not the way. Maybe somebody would like to study some approaches like Denuvo, but I think it shouldn't be the current focus.
If the application can access the source, the attacker can access the source (disassembling and debugging the application).
I think NodeJS has some methods of cryptography, so the developer itself can encrypt the source, load the encrypted, decrypt and "eval" the plain code.

The documentation of NWJS states that the **compiled source** is about 30% slower and has size limitations. I don't understand why there are these limitations. I have read it is related to context. Is it impossible to just read and replace the entire cache?

**Linking libraries dinamically**
For my problem with the games, I can move lots of logic to a DLL/SO file compiled from a simple C program. It is easy to make the library file with CodeBlocks or whatever. But I cannot simply compile a DLL and link it to the Javascript. I must turn it into a module, compile it with a specific tool (with specific requirements) and/or do a lot of complex works to get it running.

NWJS modifies the Chromium itself? In Lazarus (Delphi-like), I have played a lot with DLLs and dynamic loading of DLLs, and as far as I see, there are some platform functions which handle the DLLs/SO. Same thing for C/C++. There is no way to add some kind of handler for simple libraries in the same way we make with GCC and Lazarus and expose it to Javascript?

I don't know if it is an NWJS, a NodeJS, a V8 or a Chromium issue, but:
- I don't think V8 care about it because it is pointless to Chromium;
- Chromium will never implement it because it is unsafe for browsers;
- NodeJS could implement it, but they have their (complex) modules;
- NWJS? =) Please, please, please, please =D

\* However, I don't know if I should open a new discussion with this subject. My first thought was to post here and complement the idea of code protection. External libraries seems a viable way to do it!

**Comment by rogerwang** [comment]
Please discuss in our mailing list 
 https://groups.google.com/forum/#!forum/nwjs-general
