### ISSUE TITLE
nwjs-v0.13.0-alpha0-win-ia32 nw.js how to change user-agent?

### ISSUE THREAD

**Issue by wealeson** [nwjs/nw.js#3517]
I wan't my user only can use nw.js views my website, so I want change user agent, only my permit user agent can view.

could somebody tell me how to change user-agent?

**Comment by baconface** [comment]
This can be [changed via the package.json](https://github.com/nwjs/nw.js/wiki/Manifest-format#user-agent).

However since anyone can spoof a user agent I wouldn't use this method for security reasons. If it is for security purposes I would either use a password/username or if you don't want a username/password set up come up with a secure token system the client passes off to your website. Otherwise you will be fine.

**Comment by shaynem** [comment]
You can use a proxy also ? And then set your firewall to only allow that
address and the proxy to only proxy your address.

Then the nwjs to use the proxy settings.

Long way to go about it but user friendly

**Comment by wealeson** [comment]
I forget mark version, I can change useragent on nwjs-v0.13.0-alpha0-win-ia32

**Comment by wealeson** [comment]
Hi @baconface ,there is work on Version 0.12.2,BUT it's not working on v0.13.0.

**Comment by dogancelik** [comment]
Probably related to #2850

**Comment by rogerwang** [comment]
Thanks for reporting. This is just fixed in git. Will be available in the next alpha release or live build.
