### ISSUE TITLE
nw.js 0.12.2 fail to load local emscripten generated javascript.

### ISSUE THREAD

**Issue by junmin-zhu** [nwjs/nw.js#3542]
Test case: https://github.com/yxl/opencore-amr-js/tree/master/js

When package the case and run with 0.12.2 version, it reports "Uncaught TypeError: Cannot read property 'replace' of undefined" when loading amrnb.js.

When locate the case on apache server, and run with 0.12.2 version. it's OK.
When package the case and run with 0.13.0 alpha version, it's OK.

**Comment by rogerwang** [comment]
hello,

The error report by amrnb.js when it tries to access process.argv[1] because it thinks it runs in Node.js environment. And we don't have process.argv[1] here.

When you put the files on web server, NW.js disable the Node.js functions because it's remote page. Then amrnb.js didn't find the Node.js symbols so it thinks the environment is browser and then runs well.

You can add this workaround to demo.html to trick on amrnb.js and makes it thinks it's running in browser:

```html
<head>
    <title>AMR decode/encode tests</title>
    <script>
var require = null;
    </script>
    <script src="amrnb.js" defer></script>
</head>
```

**Comment by junmin-zhu** [comment]
Thanks @rogerwang, It works.:)
