### ISSUE TITLE
Widevine/Netflix DRM Implementation

### ISSUE THREAD

**Issue by Zensin** [nwjs/nw.js#3563]
This is something that can only be found in Chrome releases at the moment but it really holds people back from doing things like Netflix integration. In fact, it seems impossible without the plugin required which when attempting to use with nw.js does not work; however, I was shown this http://alien.slackbook.org/blog/watch-netflix-video-in-your-chromium-browser-this-time-for-real/

where someone describes making it work in chromium and am wondering if this is something that nw.js could implement. Here is what they used: http://taper.alienbase.nl/mirrors/people/alien/slackbuilds/chromium-widevine-plugin/
##

**Comment by christomitov** [comment]
Please let me know if you get this figured out. I have tried loading pepper plugins with `--register-pepper-plugins` but I don't think that flag is respected by nw.js

**Comment by mattbab** [comment]
While not well versed in this all, it sounds as though you're running up against Chrome totally dropping PPAPI support in recent releases. I'm hopeful it'll work itself out once the plugin creator (Netflix in this case) moves to HTML5 - however I thought this was already complete for Netflix.

It may also be caused by the content provider blocking unknown clients. Either way this sounds like an issue for Netflix to address.

**Comment by christomitov** [comment]
@mattbab The switch to HTML5 is complete for netflix. the Pepper API plugin they're using is specifically for DRM, that's what widevine does. It isn't chrome that's dropped support it's chromium. Chromium does not want DRM plugins in their browser so people have found ways to hack it in, unfortunately I can't get it working in nw.js 0.12.0 on linux. That's what I'm trying to figure out, also related to this issue: https://github.com/nwjs/nw.js/issues/3486

**Comment by GnorTech** [comment]
This is enabled in 0.29.0 pre-release. See updates in #6425
