### ISSUE TITLE
Node Webkit installer (.nw as native apps)

### ISSUE THREAD

**Issue by AlexisTM** [nwjs/nw.js#3640]
Dear,

I would like to know if it is planned to "install" node-webkit. I mean, you install node-webkit, double click on app.nw or app.pak to start the app. 

While this is undone for newbie users, we are forced to pack the application WITH node webkit (which is an overkill) or to make them install node-webkit and add a script file (.cmd, .bat) to start the application, which is not gorgeous. 

Is it planned, is there a project doing this or should I start one ?

Thanks, 
Alexis
##

**Comment by glenn9** [comment]
Seems like an unsafe way. Let's say nw.js 1.0.0 comes out, and breaks previous API's. Apps who aren't updated by the time the user globally installs 1.0.0, won't work anymore, and there's a good chance they can't even update themselves because they break/throw before that can happen

In the grand scheme of things, nw.js isn't that big, lots of applications end up with 1GB+

**Comment by AlexisTM** [comment]
Ohw, I understand. Maybe should we add the version of nw.js in the package.json. 

1GB+ is so big for one JS & HTML application ! I though it was less, like 5MB, or 15MB with lot of images. (Certainly cause of the node_modules! )

**Comment by glenn9** [comment]
I meant others as in some native applications, like Adobe Photoshop for example.

Our production nw.js app is zipped around 50MB and contains plenty of 3rd party modules.

**Comment by AlexisTM** [comment]
Hahaha ! Sorry for my misunderstanding!
