### ISSUE TITLE
High memory usage when using node webkit for a period of time

### ISSUE THREAD

**Issue by joshuaterrill** [nwjs/nw.js#3642]
I've been experiencing memory usage of upwards 1GB+ when using node webkit to test a web app. (This includes multiple page refreshes, etc) has anyone else experienced this?

**Comment by chrisJohn404** [comment]
I have, I'm not sure what you were doing to run into issues but I am integrating "flotcharts" into nwjs.  They have several examples available:
http://www.flotcharts.org/flot/examples

The easiest example to use to reproduce what memory issues I am seeing is to load their realtime one:
http://www.flotcharts.org/flot/examples/realtime/index.html

When running this in Chrome, Firefox, or IE, I don't run into any memory consumption issues however when I pull it into my nwjs 0.12.2 based project I quickly run up 200-600MB.  I tried loading the example with the alpha2 version of nwjs 0.13 and didn't have any memory consumption issues but I am not sure what that indicates as far as what the issue is.  the included iojs version on 0.12.2 is 1.2.0 and for 0.13-alpha2 it is 1.5.1.  I assume the version of chromium also changes.

The two biggest things that get used are **canvas** elements and **timers** that trigger a lot of things to happen.  I did pull up chromes dev-tools on all 3 tests (chrome, nwjs 0.12.2, and 0.13-alpha2) and can see a triangle-wave pattern in heap size which is a good indicator of a memory leak but it is weird that 0.12.2 behaves differently than browsers.  I'm not very familiar with garbage-collection in node and nwjs other than your ability to add a "js-flag" to your package.json:
        "js-flags": "--expose-gc",
to expose the global function "global.gc()" that you can call to trigger the garbage collector to run.  It is a little bit comical seeing how v8 comes in and optimizes the code during run-time and drastically reduces its memory foot-print after about 2-5min of running.

I am thinking this is related to timers doing something weird or a difference in how the garbage collector is run because the program doesn't spend a lot of time "painting" or "rendering" as long as you have the various .dll's to allow hardware-accelerated canvas rendering around but I really have no clue.  It may just have something to do with the inclusion of an older io.js version in nwjs 0.12.2 which is a rapidly changing project.

What are you doing to run up your memory usage?

**Comment by joshuaterrill** [comment]
So in version 0.13a2 you didn't have any issues? It appears that most of my memory consumption issues are related to async calls to a database or server and scheduled jobs.

**Comment by joshuaterrill** [comment]
Closing this now, it was related to a bug I had in my tree control making a number of requests to a servlet.
