### ISSUE TITLE
[0.13.x] io.js version?

### ISSUE THREAD

**Issue by clintwood** [nwjs/nw.js#3655]
Looks like the version used are quite 'old', v1.5.1, while v2.3.4 is currently shipping!  What is the plan to bring this in line with the current io.js release and is there a plan to track those releases.

In particular [io.js ships with many ES2015 (es6)](https://iojs.org/en/es6.html) features enabled which is awesome!

Lastly, current releases of both [node.js](https://github.com/joyent/node/blob/master/ChangeLog#L3) & [io.js](https://github.com/nodejs/io.js/pull/2141) ship with critical security fixes.

Thanks for the awesome project!

**Comment by rogerwang** [comment]
It's rebased to the 'next' branch here (I'll push the code to github soon): https://github.com/nodejs/io.js/tree/next

So in NW.js 0.13.0-alpha3 io.js will be based on the code in 'next 'branch of IO.js. Currently the version number shows 2.3.4, but it would be 3.0 later. And Chromium is rebased to 44.

We had been pending on the old IO.js and Chromium because the v8 versions in them mismatch, see https://github.com/nodejs/io.js/issues/1451

**Comment by clintwood** [comment]
Awesome, thanks for the feedback!!
