### ISSUE TITLE
Restart on crash?

### ISSUE THREAD

**Issue by mscreenie** [nwjs/nw.js#3671]
Is there a way to set nwjs to restart on crash, maybe due to lack of memory for example. I thought of creating a helper app or script to run along side the app, but i assume this would also be affected if the main app crashed.

Has anyone implemented this is a good manner?
##

**Comment by lklepner** [comment]
+1

**Comment by vjancic** [comment]
I used PM2 on *nix systems (on windows I believe NSSM should do the trick) to restart after crash due to lack of memory.

Firstly I installed nw locally via NPM, then I started the PM2 process:
`sudo pm2 start "/home/panel/presentation/node_modules/nw/bin/nw" --name "presentation"`

Now when the application crashes it is restarted automatically.

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
