### ISSUE TITLE
Simple file sync app

### ISSUE THREAD

**Issue by webchaz** [nwjs/nw.js#3712]
From what I've seen, I can use nwjs to create an app, much like a website.  I want to create a Dropbox similar client for Mac that would allow you to sync files with a remote server, this would act like a mounted folder, this possible with nwjs?
##

**Comment by ed4becky** [comment]
I have an application that keeps files in sync with Dropbox, so yes

**Comment by baconface** [comment]
Short answer yes.

**Comment by MarcFowler** [comment]
The biggest thing to consider here is garbage collection right? Because you'll want the app to run permanently in the background I'm guessing. There are some reports of issues with this (#3722 etc) and in a long-lived app like that you might run in to problems. For me, the issues seems CPU; it seems to be consistently using up 12% of CPU, and I'm working on getting that down.

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
