### ISSUE TITLE
Bundled libffmpegsumo.so doesn't work with mp3's

### ISSUE THREAD

**Issue by twolfson** [nwjs/nw.js#3723]
In [plaidchat/plaidchat#100][], we recently discovered that Google Chrome/Chromium doesn't include a `libffmpegsumo.so` in it's `deb/rpm` packages. As of `nw.js@0.12.3`, `nw.js` seems to include a `libffmpegsumo.so` in its downloads. Unfortunately, this file doesn't seem to work with mp3's as it should.

[plaidchat/plaidchat#100]: https://github.com/plaidchat/plaidchat/issues/100

We have created a test gist to reproduce the issue and well as verify that other prebuilt `libffmpegsumo.so` files work properly. Please find the instructions here:

https://gist.github.com/twolfson/24bb1093cb6c833cfc55#file-readme-md

**Comment by rdtsc** [comment]
The FFmpeg binary that ships with NW.js never supported MP3, IIRC, because of licensing issues. Here's a [wiki entry](https://github.com/nwjs/nw.js/wiki/Using-MP3-&-MP4-%28H.264%29-using-the--video--&--audio--tags.) describing the "issue" and [instructions](https://github.com/nwjs/nw.js/wiki/Using-MP3-&-MP4-%28H.264%29-using-the--video--&--audio--tags.#build-it-yourself) for building your own copy with the correct directives.

As it stands now, it doesn't look like the binary that's shipped with NW.js will change any time soon. If you're tied to a particular format and building your own copy of the lib's not an option, you'll probably have to resort to ripping a copy of from Electron (or similar). Automating that as part of your build process should not be difficult.

**Comment by twolfson** [comment]
I could have sworn that 0.12.2 didn't include a bundled `libffmpegsumo.so` but there it is.

http://dl.nwjs.io/v0.12.2/nwjs-v0.12.2-linux-x64.tar.gz

However, the wiki page isn't entirely accurate any more. As mentioned Google Chrome no longer bundles a `libffmpegsumo.so` (let alone an mp3 compatible one).

> The directory location may vary according to the Linux distribution you are using. Under Ubuntu, it's located at /opt/google/chrome. Copy libffmpegsumo.so to the nw.js folder.

Currently, we are distributing a CLI application via `npm` which runs `nw` in an unpacked format. Some flawed options are:

- Install `electron-prebuilt` and copy `libffmpegsumo.so` from it
    - This downloads unnecessary excess data which is impratical
- Copy `libffmpegsumo.so` to a folder like `dist/` on `prepublish` from a library like `electron-prebuilt`
    - Since `npm` only supports 1 publication for all architectures, we will either have to:
        - Only support a single platform (bad for 32 bit and 64 bit platforms)
        - Publish all `.so` variants in `npm` (excess data once again)

Do you know of any libraries that support downloading only the `.so` file for a single platform?

**Comment by rdtsc** [comment]
@twolfson: This is a bit off-topic for NW.js, I think. Let's continue this in: [plaidchat/plaidchat#100](https://github.com/plaidchat/plaidchat/issues/100).

**Comment by twolfson** [comment]
As mentioned in plaidchat/plaidchat#100, I don't believe this is off topic as it's a platform wide problem (i.e. the existing solution for using pre-existing binaries -- copying from Google Chrome -- no longer works).

Maybe `nw.js` can create a new repository which serves these compiled assets as you suggested in plaidchat/plaidchat#100 (except now generalized outside of `plaidchat`)? This would allow that repository to specifically be licensed under GPL as required and leave `nw.js` under its existing license.

**Comment by rdtsc** [comment]
@twolfson: Sorry, I was under the impression that you were looking for a solution specific to your project. Hence my redirect. I see now that I was mistaken.

In relation to the "problem" itself, I believe the existing solution of ripping the shared object lib from other distributions (Chrome, Electron, etc.) is actually considered an unsupported fallback that just happend to work in previous versions (last time I used it was in the 0.9.x days). As mentioned in the [wiki](https://github.com/nwjs/nw.js/wiki/Using-MP3-&-MP4-%28H.264%29-using-the--video--&--audio--tags.#overview):
> Alternatively, you can try to use the media libraries from Chrome. It has been reported to work, but it hasn't been properly tested, so it may or may not work for you in latest version.

So, it seems to me like the "official" method of getting MP3 support (as it stands now) is to build your own copies of FFmpeg and not rely on 3rd party binaries.

> Maybe nw.js can create a new repository which serves these compiled assets as you suggested in plaidchat/plaidchat#100 (except now generalized outside of plaidchat)? This would allow that repository to specifically be licensed under GPL as required and leave nw.js under its existing license.

Agreed. A generalized official repo is a good idea as this problem is widespread.

**Comment by Qqwy** [comment]
I also agree with this, and hope that such an repository will quickly be created, as I am having a lot of trouble to compile the FFmpeg support properly, let alone cross-platform.

**Comment by namaljayathunga** [comment]
+1

**Comment by ghostoy** [comment]
Chrome no longer provides separate dll/so/dylib of ffmpeg. Since 0.13.0, there are 2 options to get them:

1. Get it from community from [iteufel/nwjs-ffmpeg-prebuilt](https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases)
2. Build it yourself. See [Enable Proprietary Codecs](http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/).
