### ISSUE TITLE
Content bleeding pink

### ISSUE THREAD

**Issue by watdafox** [nwjs/nw.js#3741]
Hello, 

On [our application](https://git.popcorntime.io/popcorntime/desktop/tree/development), we're using nwjs 12.1, and 3 users so far have reported some sort of "pink" overlay on top of the application:

![image](https://cloud.githubusercontent.com/assets/10504232/9143995/18ec0686-3d4a-11e5-9ce6-435380a9395e.png)
_"Pink" overlay (don't look at the console code, it's non-relevant to this issue)_

At first, I thought it was because of our modifications to the nwjs binary (adding broad codec support), but a user [reported in a message](https://discuss.popcorntime.io/t/windows-10-waterpaints-popcorn-time-pink/47267) that the same thing happens if he replaces our modified binary by an official build.

Here's more information:
- Only 32bits, we don't use your nwjs 64bit as for now.
- Issue seen on nwjs 9.2, 12.1 and 12.3.
- Issue present apparently only with our application: [PowderPlayer](https://github.com/jaruba/PowderPlayer) using nwjs 12.2 doesn't seem affected.
- Yet, [this chromium ticket](https://code.google.com/p/chromium/issues/detail?id=319115) and [that blog post](http://usedmonkey.com/2014/01/fix-google-chrome-pink-screen/) seem to indicate that something is wierd with nVidia, Windows & Chromium.
- All users having trouble were running Windows x64 (8.1 or 10) with a nVidia graphic card.

Two users solved it by installing the drivers again, the other one with the disabling of 3D stereoscopic mode.

---

Now, if this is a chromium issue, I imagine you guys won't do anything. But the wierd part is that it doesn't happen with all nwjs applications, hence this question: any idea what might cause that, maybe something we (developpers of the application) can do to prevent it? A flag, avoid this or that kind of module, ... 
##

**Comment by sammuel86** [comment]
+1

**Comment by jaruba** [comment]
Wow, this issue has been reported even 2 years ago, I keep seeing reports of it in different places (even the asus forum).

It is most certainly an issue with Chrome + nVidia (and the fact that nVidia enables 3D stereoscopic mode by default). In [Powder Player](https://github.com/jaruba/PowderPlayer) I use these Chromium args:

    "chromium-args": "--d3d9 --disable-d3d11 --gpu-no-context-lost",

for better support for [WebChimera.js](https://github.com/RSATom/WebChimera.js) on Windows. 

``gpu-no-context-lost`` certainly cannot have anything to do with this, but the answer may be in forcing the use of ``Direct3D 9`` instead of ``Direct3D 11`` in Chromium, the reason I disable it is because there are issues with ``Direct3D 11`` in Chrome on Windows, maybe this is somehow related to the pink screen issue.

Try adding ``--d3d9 --disable-d3d11`` to the Chromium args. (if you have a proper testing environment for this bug)

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
