### ISSUE TITLE
[v0.13.0-alpha2-win-ia32] Manifest file is missing or unreadable

### ISSUE THREAD

**Issue by tr0yka** [nwjs/nw.js#3742]
nwjs-v0.12.2-win-ia32 work, 13a2 not work

**Comment by gwicksted** [comment]
+1

**Comment by warnet2git** [comment]
I got this problem fixed.
I use the nwjs-v0.14.5-win-x64, but I think the problem is the same.

You should not zip the folder which contains your app. Instead, you should zip all the files directly.
The clue is when dragging the app.nw into nw.exe, error window says manifest file is missing. So just zip the files without the folder.

Hope this helps u.
