### ISSUE TITLE
[nw13]addon crashes when using Nan::AsyncQueueWorker

### ISSUE THREAD

**Issue by imskull** [nwjs/nw.js#3754]
Code below

```
NAN_METHOD(Unzip) {
  Nan::HandleScope scope;
  ...
  Nan::Callback* callback = new Nan::Callback(v8::Local<v8::Function>::Cast(info[2]));
  Nan::AsyncQueueWorker(new zip::UnzipAsyncWorker(callback));
  info.GetReturnValue().Set(Nan::Undefined());
}

void UnzipAsyncWorker::Execute() {
  // nothing
}
```

It crashed on nw13-alpha2 without any log in console, but it runs fine on nw12 and node.js.

Btw, I couldn't find nw-gyp for 0.13.0-alpha2, I am using "nw-gyp xxx --target=0.12.3", is this the reason of crash?

```
nw-gyp configure --target=0.13.0-alpha2
nw-gyp configure --target=0.13.0
```

all failed.
##

**Comment by schahriar** [comment]
I've managed to build for alpha2 using the alpha0 headers (0.13.0-alpha0). You can search through a list of headers here http://node-webkit.s3.amazonaws.com/. Hope that helps.

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.
