### ISSUE TITLE
resizable flag does not disable maximize button in osx yosemite

### ISSUE THREAD

**Issue by drown-zed** [nwjs/nw.js#3768]
Hi,
It appears that when I set the resizable: false in the manifest file, OSX does not have a disabled maximize button. It works fine on windows 7, however on OSX, it can still maximize the window.
Did anyone encounter the same problem? Maybe there is a workaround?
##

**Comment by bleush38p** [comment]
I've observed this problem as well. The window does not maximize (option + green button) but it does still try to go full screen. There don't seem to be any options to disable this. Here's what I've done—it's super gross, and quite clunky in action. Still, I haven't found anything better:

````javascript
win.on('enter-fullscreen', function() {
  setTimeout(function() {
    win.leaveFullscreen()
  }, 1000)
})
````

I'm using `setTimeout` because (I'm not sure if this is a nw.js problem or I've been doing something wrong) `win.leaveFullscreen()` doesn't seem to work while the transition is happening—or, it only works sometimes, and then the value of `win.isFullscreen` varies based on how the planets are aligned afterward.

**Comment by drown-zed** [comment]
I've found a solution to this. It's quite simple, just use "fullscreen": false in the manifest file. For some reason it was not included in the documentation

**Comment by bleush38p** [comment]
I've added a [note](https://github.com/nwjs/nw.js/wiki/Manifest-format#resizable) in the documentation.

**Comment by Christywl** [comment]
I can't reproduce this issue on Mac with nwjs-sdk-v0.22.3.

**Comment by Christywl** [comment]
close until there is more information.
