### ISSUE TITLE
Exists keyboard shortcut for show developer tools?

### ISSUE THREAD

**Issue by 2byte** [nwjs/nw.js#3781]
For windows

**Comment by rdtsc** [comment]
Use [Window.showDevTools](https://github.com/nwjs/nw.js/wiki/window#windowshowdevtoolsid--iframe-headless):
```javascript
window.addEventListener('keydown', function(event) {
  if(event.keyIdentifier === 'F12') {
    require('nw.gui').Window.get().showDevTools();
  }
});
```

**Comment by bleush38p** [comment]
You can also create a [menu item](https://github.com/nwjs/nw.js/wiki/MenuItem) for it. This (or something like this) is what I use in a number of applications, and it could easily be modified for windoze:
````javascript
appmenu.append(new gui.MenuItem({
  label: 'Developer tools',
  key: 'i',
  modifiers: 'cmd-alt',
  click: function () {
    win.showDevTools()
  }
}))
````

Part of the design goals of nw.js involve including as little as possible by default, so the user can easily add on the features they need, but not have the features that aren't needed or would be detrimental to the end user's experience.

So, because of that, there's not any *built in* keyboard shortcuts for anything, but it's very simple to create them yourself.

**Comment by 1j01** [comment]
[nw-dev](https://github.com/1j01/nw-dev) will also give you an <kbd>F12</kbd> shortcut in less code than
`onkeydown=function(e){e.keyCode==123&&nwwin.showDevTools()}`
just install it and include:
`<script src="node_modules/nw-dev/lib/dev.js"></script>`
nw-dev will *toggle* the devtools on <kbd>F12</kbd>, not refocus them if already open, and it'll also do other stuff
I think this issue can be closed.
