### ISSUE TITLE
nw.exe shows up as "Russian Roulette 2" in Nvidia Control Panel

### ISSUE THREAD

**Issue by janpetersen** [nwjs/nw.js#3793]
At least the 0.12.0 release of the nw.exe shows up as "Russian Roulette 2" in the Nvidia Control Panel. But I think the underlying problem is a general one:

Nvidia picks up the "nw.exe" by some checksum (?) and stores it in their database with the current application's name. The first entry into this database seems to "win" and persists over time.

Even worse, Nvidia applies a stored graphics setting for "Russian Roulette 2" to the application, which might cause trouble for some users.

And last but not least, this irritates some users, since a title "Russian Roulette 2" does not sound very trustworthy.

Please take this issue into consideration for your future releases, and perhaps get in contact with Nvidia on how to change the entry in their database.

**Comment by baconface** [comment]
This is unfortunately an issue only Nvidia can resolve.

**Comment by AforAnonymous** [comment]
Hi,

nVidia does simple string matching on the executable path and name. This issue can be worked around by using nVidia inspector, exporting the current profiles in the nVidia proprietary format, opening the exported file (it's a plaintext file.), finding the entry for "nw.exe" and editing it according, then importing it back in using nVidia inspector.

Unfortunately, this workaround then has to be repeated after each driver update.

2 ways to get this properly fixed:
1. Rename nw.exe to some different name. This way the profile does not get applied. 
2. Open a case with nVidia (someone who is considered associated with the nw.js project would have to do that) and have them fix it. (Good luck with that.)

#2 could also be accomplished by hassling nVidia via social media, e.g. /r/nvidia. Not that I'd recommend that, of course.

A bit off topic, but since nw.js is javascript based, I figured it might interest some people:
This same behavior also is why many custom firefox builds don't seem to work completely right on Windows - the nVidia driver looks for firefox.exe, not whatever the custom build is called, be it cyberfox.exe, waterfox.exe, palemoon.exe or whatever else they're all called. Subsequently, the shims nVidia has developed for firefox don't get applied. This is also useful for testing how shims affect Chrome (and Firefox), btw.

**Comment by gianluca-nitti** [comment]
In my opinion someone should officially contact Nvidia and explain them that "nw.exe" shouldn't be used to identify that game, but it's a runtime that can be used for various applications.
I mean, Nvidia would never associate "javaw.exe" with "Minecraft" because obviously the fact that a popular game uses Java doesn't mean that any Java process is related to that game.
They should understand what nw.js is and fix the problem.

**Comment by rogerwang** [comment]
Please report this issue to Nvidia.
