### ISSUE TITLE
Menubar not working on Ubuntu 15.04

### ISSUE THREAD

**Issue by thenitai** [nwjs/nw.js#3836]
Hi,

Anybody actually got menubar working in their app on Ubuntu 15.04?

I got some pseudo bar working, but its not in the standard menubar as expected.

Any feedback appreciated. Thx.
##

**Comment by tshinnic** [comment]
Do you mean that you see nothing, or that the menubar items seen don't work?  I ask because I can see a menubar, but the menu item click handlers don't work under LinuxMint which is the older Ubuntu 14.04.  Using nw.js 0.12.3.  Using the following index.html works fine under Win7/Win10 (logs seen, debug entered) but no "Saw click" log or debugger entered when the menubar item is clicked under Ubuntu 14.04.  This is 'surprising' :-/
```
<html>
<head>
  <title>Test04 Menu APIs</title>
  <script>
//  window.addEventListener('load', function(e) {
//    'use strict';
      console.log('hello from "load" event');

      var nwGui = require('nw.gui');
      var nwWin = nwGui.Window.get();

      var menu = new nwGui.Menu({ type: 'menubar' });
      var item = new nwGui.MenuItem({
                    label:  'First',
                    click:  function(){ 
                              console.log('Saw click on menubar "First"'); 
                              debugger;
                            }
                  });
      menu.append(item);
      nwWin.menu = menu;
//  });
  </script>
</head>
<body>
</body>
</html>
```
However, in my original program, click handlers on **submenu** items *did* work.

And just tried the above test program under Fedora 22 (May 2015) and menubar is not handling clicks under 0.12.3.  So I think there is a problem with my test program, or NW.js menus under Linuxes is not working.

**Comment by Gho57X90** [comment]
You have sent this email to the wrong address.

**Comment by tshinnic** [comment]
@Gho57X90  
Could it be that you have clicked the "Watch" button at top when viewing nwjs/nw.js#3836 and then selected "Watching Be notified of all conversations" ?  I wouldn't know how else it could be that you got a notification email.... ?

Cool, I found this [list of people watching nw.js](https://github.com/nwjs/nw.js/watchers?page=34) and you are on the list at the end.  Can you try 'unwatching' the nw.js project by selecting "Not watching" ?

**Comment by tshinnic** [comment]
I've just tested with nw.js 0.13.0-alpha3 and manually typing into console:
```
nwWin = nw.Window.get()
menu = nw.Menu.createMenu({type: 'menubar'})
item = nw.Menu.createItem({label: 'First', click: function(){console.log('First!');debugger;}})
menu.append(item)
nwWin.menu = menu
```
and then clicking on the single menubar item "First".  On LinuxMint (Ubuntu 14.04) it does nothing.  On Win10 it does log "First!" and stops in the debugger.

So both 0.12.3 and 0.13.0-alpha3 are broken on Linuxes, with regard to the items on a menubar which are not submenus.

**Comment by sourceskyboxer** [comment]
Oh my god you say nw 0.12.3 for ubuntu is broken with menu?

Thanks I will test with ubuntu.  
Possible did you not install same full package of gnome or gtk or kde ????

Or you need to switch to classic desktop version?  I think unty desktop doesn't work because menu was more to top edge.  I am not sure I will try later.

**Comment by maxbarry** [comment]
Confirming all behaviour described in all comments above by @tshinnic is also seen on Ubuntu 15.04, i.e. clicking generated menu buttons logs nothing under nwjs 0.12.3 nor under 0.13.0-alpha3.

**Comment by thenitai** [comment]
Hi all,

Sorry couldn't reply sooner as I'm travelling. With pseudo bar, I mean it doesn't integrate into the Ubuntu menu at all. I get some "strange" looking bar underneath the supposed menubar. I took the code from @tshinnic and this is how it looks for me.

![selection_029](https://cloud.githubusercontent.com/assets/372121/9925099/3699c338-5d31-11e5-8fdf-df023ce897f4.png)

Obviously, I don't want it to be like that. Since this is a Linux app only, I don't care if it works on other platform.

Thanks.

**Comment by Christywl** [comment]
It works well on Linux with nwjs-sdk-v0.22.3.

```
<script>
      var nwWin = nw.Window.get();

      var menu = new nw.Menu({ type: 'menubar' });
      var item = new nw.MenuItem({
                    label:  'First',
                    click:  function(){
                              console.log('Saw click on menubar "First"');
                              debugger;
                            }
                  });
      menu.append(item);
      nwWin.menu = menu;
</script>
```

**Comment by Christywl** [comment]
close until there is more information.
