### ISSUE TITLE
Working ffmpegsumo.so for chromium 41.0.2272.76/ Node webkit v0.12.2

### ISSUE THREAD

**Issue by suriyaprashath** [nwjs/nw.js#3854]
Does anyone have a working ffmpegsumo.so for chromium 41.0.2272.76 to work in mac.

**Comment by MniD** [comment]
Hi, I have, it work with
arch: "x64"
version: "v1.2.0"
chromium: "41.0.2272.76"
https://mega.nz/#!TAFjBKxC!6Y8iHcpbfOrXQS8-l7yJhrDA_rY5tp0nhH6kOcoXG9E
I'm get this lib in Electron today.

**Comment by hems** [comment]
i can't find a working version as well.

**Comment by frankhale** [comment]
@hems can you elaborate on what exactly you mean by "I can't find a working version as well"? It's unlikely anyone can solve this without more information.

**Comment by rogerwang** [comment]
0.12 is not supported so I am closing this.

**Comment by hems** [comment]
@frankhale i meant i didn't find a working version of ffmpegsumo.so, i believe because there is a README file somewhere saying that 0.12.2 was using 41.0.2272.76 but it seem that ffmpegsumo from those chromiun versions would just crash the app. anyway some good soul found the working version and posted somewhere else and it sorted my issue out
