### ISSUE TITLE
Loading JS remotely to handle auto updates to app

### ISSUE THREAD

**Issue by alexcroox** [nwjs/nw.js#3901]
So my app heavily relies on the internet and can't function without it.

I have an app self updater process I built and it works pretty well for a group of 30 that use the app.

However I was thinking today that it would be much easier if I just loaded the concatenated js file from a remote server every time the app started, as almost all of my monthly updates just change the javascript. That way as soon as user's load the app they have the latest version, instead of having to download 40mb of NW every time.

Has anyone else tried this and are there any pitfalls I should be aware of using this method?

**Comment by baconface** [comment]
We use NW.js for a POS we maintain. About 99% of it is hosted on a server and about 1% is a local code. We are able to break the sandbox by white listing certain web servers in our package.json. The 1% double checks a server list for a usable web server testing each one before it loads it in. If none are available or an error occurs we can let them know. When they connect the local storage saves the version number. We now have our code do a heartbeat check about every minute. Part of this is to also check to see if a version has changed. If so we can alert the user. If they choose to update we simply refresh the NW.js browser. And all the files we call have ?ver=0.3.2 or whatever appended to the file name to break any caching. We additionally have an unload event to show if this refresh fails. If so we attempt to connect to another server. Works great for us. The only pitfalls are increased daily bandwidth usage and a slightly slower app since we cannot load locally. But the trade off of not having a version hell of 100 different versions of the client on the network and reducing heavy updates of our NW.js app is well worth it which was a problem with our old VB based POS.

**Comment by alexcroox** [comment]
Yer it's working nicely, I keep all the fonts and heavy 3rd party libraries bundled in the app and then it's only 100kb remote load max. Cheers!

**Comment by vinaynb** [comment]
@alexcroox @baconbrad does this technique work even when i am compiling my js code to binary code and using `Window.get().evalNWBin()` to load the js into my app ?
