### ISSUE TITLE
Unable to visit FTP urls without launching an external application

### ISSUE THREAD

**Issue by jlcastillo** [nwjs/nw.js#3935]
The following 2 tests make NWJS 12.0 - 12.3 jump to the external default browser:

```
1)   <a href="ftp://127.0.0.1">Hello World</a>

2)   <iframe src="ftp://127.0.0.1"></iframe>
```

In NWJS 13.0 alpha 4 they don't have any effect.

Is there any way to force NWJS to process FTP URLs without jumping to other apps?
##

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows with nwjs-sdk-v0.22.2.

**Comment by Christywl** [comment]
close until there is more information.

**Comment by cdog** [comment]
Having same issue with recent versions. Trying to load FTP URL via `<webview>` or `<iframe>` elements. Same works if opened in Chrome, but not with NW.js (`nwjs-sdk-v0.50.1-osx-x64`). Tested on Mac and Linux.

URLs:
* ftp://speedtest.tele2.net/
* ftp://test.rebex.net/

Using same HTML and manifest file:
```
<webview src="ftp://speedtest.tele2.net/"></webview>
```

Opening from Chrome Apps (`chrome://apps`) renders as expected:
![ftp-chrome](https://user-images.githubusercontent.com/690647/100572028-cc7afd80-32d4-11eb-9311-4679c9d5b975.png)

Loading same code from NW.js displays `ERR_UNKNOWN_URL_SCHEME` instead of FTP contents:
![ftp-nw](https://user-images.githubusercontent.com/690647/100572071-e87e9f00-32d4-11eb-923c-65af47885899.png)

Is there any way to use `ftp://` with NW.js?

**Comment by bluthen** [comment]
It works for me with "chromium-args": "--enable-features=FtpProtocol"  in package.json
None of the ftp servers you listed worked though, I ended up testing with:
ftp://ftp.ftpx.com/pub/ftpx

I'm not sure if nwjs plans to go a different path just for ftp but I'd expect not, so take note of this:
https://chromestatus.com/feature/6246151319715840

**Comment by cdog** [comment]
Hi @bluthen makes a lot of sense, thank you!
