### ISSUE TITLE
nw.exe is infected?

### ISSUE THREAD

**Issue by chrisjandrade** [nwjs/nw.js#3946]
Downloaded the win64 nwjs 0.13.0-alpha5 zip file, but Panda anti virus is marking nw.exe as infected? anyone else getting this?
##

**Comment by dkfiresky** [comment]
Github is a source of the viruses. The infection is done each time you download any software from Releases page. Even after you download the source of a software and build it on your own, it's already infected with malicious code that will blow up your pc, destroy all files and burn your HDD.

Beware, because if you remove any software downloaded from GitHub.com, your pc will get overheated and fired up.

**Comment by EasyGitHub99** [comment]
No joke my pc started crashing with BSOD after I started a noon tutorial build for nw.js

**Comment by EasyGitHub99** [comment]
Noob*

**Comment by dkfiresky** [comment]
@EasyGitHub99 
> Noob*

Kid go learn how to be polite with people.

**Comment by baconface** [comment]
It is likely a false positive. This isn't the first time a false positive has happened with NW.js and likely won't be the last.

To be safe, just in case, upload the file to Virus Total. - https://www.virustotal.com/

**Comment by EasyGitHub99** [comment]
@dkfiresky wasn't calling anyone a noob :)
I was correcting a typo from my previous comment. I know I'm a noob tho.

**Comment by dkfiresky** [comment]
@EasyGitHub99 There is an edit button for that.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
