### ISSUE TITLE
Why is the compass pointed toward North East (NE)?

### ISSUE THREAD

**Issue by ddfssdfkofdsfighdfuigf** [nwjs/nw.js#4038]
It's not called NE.js. It's NW.js. The reference is mirrored for some reason. Why is this?

**Comment by chaseWillden** [comment]
Where is this typo at?

**Comment by ddfssdfkofdsfighdfuigf** [comment]
It's not a typo. I'm talking about the logo for NW.js.

**Comment by karlrwjohnson** [comment]
I cannot answer for the maintainers of the NW project, but if I were to speculate, I would guess that the compass needle's direction was not relevant when the logo was created.

It appears that the logo was discussed in [issue #148](https://github.com/nwjs/nw.js/issues/148) as a combination of "[node's hexagon + webkit's compass](https://github.com/nwjs/nw.js/issues/148/issuecomment-10096152)". Its current form was selected due to Back then, the project was called node-webkit, not NW. This is reflected in jeroenrasjin's [prototype](https://dribbble.com/shots/816239-Icon-node-webkit-pre-release) of the final graphic.

If you look up [images of the Webkit project's logo](https://www.google.com/search?q=webkit+logo), you'll see that the compass needle points to the northeast as well, and that decision goes all the way back to Apple. I imagine that NW followed Webkit's lead for the compass needle.

If you're suggesting that the compass needle be reoriented to match the project's new name, then I concur; I think it's rather clever. But if you're just wondering why the needle points the way it does, then the answer is simply that nobody has thought to change it.

**Comment by ddfssdfkofdsfighdfuigf** [comment]
Thanks for that explanation. It makes sense. Still, I think it should be changed to reflect the name.

**Comment by rogerwang** [comment]
When you are facing NW, and the compass points to North, it looks exactly like the logo
