### ISSUE TITLE
Request: new version of nwjs 0.12

### ISSUE THREAD

**Issue by matthew-dean** [nwjs/nw.js#4095]
I know you're currently working on nwjs 0.13, but Chrome 41 has some web-font-rendering issues that I'm still trying to hack around. Originally this project stated more frequent releases were coming after migrating to io.js. So, is it possible to have a 0.12 release with a newer version of Chromium (and Node.js if possible)? The Chrome Web App integration of 0.13 is of little value, but newer Chrome / Node would be great.

**Comment by rogerwang** [comment]
What's the problem of using 0.13?

**Comment by matthew-dean** [comment]
0.13 is in alpha and hasn't ported all APIs, correct? This is for production release software.

**Comment by rogerwang** [comment]
Our plan is: if there is any 0.12 release, it would happen after 0.13 release. And theoretically there shouldn't be any 0.12 release anymore to update the chromium, because a) 0.13 should fit the needs for 0.12 and b) we don't update chromium while the major version remains unchanged. 

The beta version will be released with 0.12 features ported in several days. We hope to keep a close eye on the bug reports and release the final version soon after that.

**Comment by matthew-dean** [comment]
> The beta version will be released with 0.12 features ported in several days

That's good news! Thanks for the update!
