### ISSUE TITLE
AngularJS templates fail to load on v0.13.0-beta2

### ISSUE THREAD

**Issue by Gimmeaphatbeat** [nwjs/nw.js#4155]
From nwjs Developer Tools Console:

`XMLHttpRequest cannot load file:///C:/Users/path/here/template-name.html. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.`

**Comment by Gimmeaphatbeat** [comment]
Related to #4119

**Comment by Gimmeaphatbeat** [comment]
The following manifest setting solves this:

`"chromium-args" : "--allow-file-access-from-files"`

**Comment by ghostoy** [comment]
I tested with AngularJs tutorial and it works in latest nw nightly except the images are broken.

The images issue is because AngularJS added `unsafe:` prefix to unknown URLs. In NW.js, the URLs are started with `chrome-extensions:`. The solution is here https://github.com/angular/angular.js/issues/3721. You can add following configs to fix image issues:

```javascript
myApp.config(['$compileProvider',
  function($compileProvider) {
    $compileProvider.imgSrcSanitizationWhitelist(/^\s*((https?|ftp|file|blob|chrome-extension):|data:image\/)/);
    $compileProvider.aHrefSanitizationWhitelist(/^\s*(https?|ftp|mailto|tel|file:chrome-extension):/);
  }]);

```

**Comment by Gimmeaphatbeat** [comment]
My problem was that my NW app navigates to an HTML file held outside my app folder, and so it uses the file:// protocol.
