### ISSUE TITLE
Does nwjs 0.13 beta2 support Windows XP ia32 (sp3)？

### ISSUE THREAD

**Issue by chptx** [nwjs/nw.js#4181]
1、download nwjs-v0.13.0-beta2-win-ia32.zip and extract
2、double click on nw.exe but no window display

**Comment by AndryBray** [comment]
I can confirm, tested with latest build beta3 and the app window is not opened. (tested with and without sdk build)
I see the first process runs, then te 2nd will open and close after some second and nothing will happen.

**Comment by rogerwang** [comment]
If Chromium 47 or 48 can run on XP then we should support it too.

**Comment by AndryBray** [comment]
I'm trying to open the clean build of nwjs (with no app package or customization) but it doesn't start. Did you test it?

**Comment by skyup-str** [comment]
Same issue here.
I've tested nw13-alpha5, 6, 7, 8,  nw13-beta1, 2 and 3
(each in the normal and the sdk build and with and without an app, too) 
under Windows XP Professional SP3 and no version works properly. No 
matter which combination i've tried, it leads always to the same result:
- the main process starts
- the second process starts but terminates after 1 sec.
  without an errormessage or some output in the debug.log
- no window opens
- no code (for example in a backround script) will execute
- the main process keeps running

nw13-alpha4 was the last release which runs as expected.
To figure out if it's caused by the upstream releases, I've checked the latest
chromium (portable), io.js and node.js versions. All of them working fine under
the same machine.

It would be really nice when this could be fixed.

**Comment by ghostoy** [comment]
@AndryBray Could you test if Chrome 47 and 48 works on XP? I can't find a PC running XP.

**Comment by AndryBray** [comment]
@ghostoy I can confirm Chrome `47.0.2526.106 m` and `48.0.2564.71 beta-m` are working on XP without problems.

**Comment by ghostoy** [comment]
I'll look into this issue.

**Comment by AndryBray** [comment]
@ghostoy any news about that? 
Thank you

**Comment by ratones** [comment]
I can confirm this issue in nw13-beta4.
nw proccess is shown in task manager, but no window.
Chrome 47.0.2526.106 working.

**Comment by rogerwang** [comment]
Will be available in the next nightly build.
