### ISSUE TITLE
DevTools window is blank

### ISSUE THREAD

**Issue by niutech** [nwjs/nw.js#4383]
I cannot inspect any page using remote dubugging port nor showDevTools in NW.js 0.13 beta5. When I go to `http://localhost:9222`, I can see two inspectable pages, but clicking on one of them gives me a blank page with URL: `http://localhost:9222/devtools/inspector.html?ws=localhost:9222/devtools/page/66B9CE70-36FF-4E16-B941-C695F786B17B`

It happened only in Normal release, SDK works fine.

I am using:
Windows 8 x64
nw.js v0.13.0-beta5
Node v5.4.1
Chromium 48.0.2564.97
commit hash: cb79ab8-7b8b7ed-a93f67b-09f2a6d

**Comment by rogerwang** [comment]
The normal build doesn't have devtools.

**Comment by julmot** [comment]
@rogerwang When I run `nwbuild` everything works as expect. But when I run `nw` the developer toolbars are blank like @niutech described. 

Isn't `nw` running in SDK flavor? How to get the same behavior in dev + prod?

**Comment by Spown** [comment]
I would suggest, since ``win.showDevTools()`` in normal build opens a window anyway, to put a simple text line in the window "this is a normal nw.js build. to use devTools pleas download and install SDK build" and maybe a link to the corresponding to the current SDK version? I've just spent an hour trying to solve this "bug"...

**Comment by KylePalko** [comment]
For those coming from Google, to install the npm version of `nw` in SDK mode:

```
npm install nw --nwjs_build_type=sdk
```

Also check out: https://www.npmjs.com/package/nw#install-a-specific-build-type-of-nwjs
