### ISSUE TITLE
[nw13]how to migrate data

### ISSUE THREAD

**Issue by gitawego** [nwjs/nw.js#4469]
I just updated my application from 0.12.x to 0.13.x in windows, then all the data are lost, because the dataPath has changed. how can I seamlessly update an application from nwjs 0.12.x to 0.13.x without data loss ?

thanks in advance

**Comment by MadSpyxFR** [comment]
In order to avoid this, I use my own save logic in files in user/documents or appdata folders.
You can update your app with new save logic with 0.12.x and release a new version with 0.13.x later

**Comment by rogerwang** [comment]
Where is your data stored? The localstorage can be automatically migrated.

**Comment by gitawego** [comment]
localStorage is migrated automatically, but not indexedDB, all the data are stored in indexedDB in my application.

**Comment by chino23** [comment]
websql seems to migrate just fine too

**Comment by gitawego** [comment]
any update on this issue ?@rogerwang  
It seems indexedDB structures are copied to nw13, but not the data (of each collection). 
it's the only problem which prevent us from migrating to nw13..

**Comment by rogerwang** [comment]
will fix this soon.

**Comment by rogerwang** [comment]
The fix for migrating indexeddb is pushed to chromium repo. Please try it after the next nightly build.

You'll see something like INFO:indexed_db_backing_store.cc(1266)] migrated indexed db: dbname in the log.

**Comment by gitawego** [comment]
cool, thanks a lot

**Comment by parthi82** [comment]
I tried using latest releases (v0.14.1, v0.14.2) and the local storage is migrated automatically for my app using nwjs v0.12.2. but the indexeddb is not migrated.

**Comment by bachel** [comment]
I have a problem with cookies migration from nw12 to nw13. My stats are based on cookies and users are log in my app based on cookies. I know that cookies in nw13 is located in different folder but I cannot copy them when my app is running because they are locked.

**Comment by rogerwang** [comment]
@parthi82 could you please submit an example with the user data dir?

**Comment by parthi82** [comment]
@rogerwang user data dir is /Users/parthi/Library/Application Support/myapp/IndexedDB/app_pstn-app.live_0.indexeddb.leveldb

**Comment by parthi82** [comment]
I can see that "file__0.indexeddb.leveldb" is hard coded here https://github.com/nwjs/nw.js/blob/nw14/src/nw_content.cc#L349, but in my app the indexeddb file is app_pstn-app.live_0.indexeddb.leveldb because my app used  global 'app://xyz' in package.json as given here https://github.com/nwjs/nw.js/wiki/App-protocol

**Comment by RohitSharma27** [comment]
"app://" protocol isn't supported anymore, if it helps.

**Comment by parthi82** [comment]
yes, i removed it while building for new version. but i was saying that the indexeddb file is named as xyz_0.indexeddb.leveldb because of the app://xyz in the old version (v0.12.x). the migration code https://github.com/nwjs/nw.js/blob/nw14/src/nw_content.cc#L349 uses "file_0.indexeddb.leveldb" so it not migrating indexeddb data.
