### ISSUE TITLE
Facebook and Guardian in iframe reload nwjs based app

### ISSUE THREAD

**Issue by krneticz** [nwjs/nw.js#4588]
When Facebook is opened in iframe in nwjs based app and you open somebody's shared photo and then click close (x icon in corner, or just click in black space outside of image) it reloads app. It is happening with win 64 sdk rc3 and rc4 (nightly build from mar 17). Same thing happens with Guardian site opened, when you open some image in website's photo viewer and then close the photo viewer.

I have attached simple app that just consist of html page with iframe that loads Facebook. Just drag folder to nw.exe, login into Facebook, open some shared photo and close it and app will reload.

[iframe.zip](https://github.com/nwjs/nw.js/files/177574/iframe.zip)

**Comment by rogerwang** [comment]
Is it reloading the app or the iframe?

**Comment by krneticz** [comment]
It reloads whole app.

**Comment by rogerwang** [comment]
@ghostoy pls try to reproduce.

**Comment by ghostoy** [comment]
Yes, I can reproduce. No matter whether `node-remote` is set.

**Comment by rogerwang** [comment]
@krneticz This issue is triggered by calling history.back() in the iframe after setting window.name. 

I created a case to demo this: https://github.com/rogerwang/4588-reload ; before the top frame reloads it will show a popup. To reproduce it, navigate the iframe to child2.html, then click the 'back' button.
If you comment out the line setting 'window.name' it works well.

Unfortunately this bug is also in Chromium browser. I suggest to report an issue to upstream.

Before it's fixed you can use webview tag over iframe...

**Comment by krneticz** [comment]
@rogerwang Thanks Roger. This is not anymore issue for us, since we have switched our in-app browser to the webview tag.
