### ISSUE TITLE
Unable to turn off / disable debug.log

### ISSUE THREAD

**Issue by Yonezpt** [nwjs/nw.js#4637]
Supposedly the debug.log file should no longer be created by default since https://github.com/nwjs/nw.js/commit/9a4562b031afb7558963e22adf4c5951c87efc5b

However it keeps creating a debug.log file whenever the app runs. I already tried `"chromium-args": "disable-logging"` and `"chromium-args": "--disable-logging"` but the debug.log file keeps being generated.

I've only noticed this file because it was reaching an extremely large size. While I can delete it myself periodically or perhaps even create a routine to do it, this is not an ideal behavior for end users.

I did test this with the Normal NWJS version expecting this to be linked to SDK, but the behavior still stands.

Either the debug.log should be disabled unless the user adds the flag to enable it or the opposite, either way as it currently stands the debug.log file cannot be disabled by any means.

NWJS Normal: v0.13.1
OS: Win7x64

**Comment by Yonezpt** [comment]
Looks like this problem returned/is present in current NWJS 0.14.0 rc2, probably a regression or perhaps the current fix in 13 was never applied to 14.

**Comment by rogerwang** [comment]
The fix was merged to the branch for 0.14 after 0.14.0-rc2. It's in the nightly build:

http://dl.nwjs.io/live-build/04-07-2016/9e26cf8-4903036-1df60de-98bfcac

**Comment by Yonezpt** [comment]
Glad to hear that, I wasn't aware of rc3 yet.

**Comment by Yonezpt** [comment]
On Win7x64 sdk0.13.3 and sdk0.14.0rc3 the issue appears to be mostly fixed so far, but error messages are still going through to the debug log and only error messages, nothing else.

The one I keep receiving is as follows:
````txt
[0407/223545:ERROR:image_metadata_extractor.cc(114)] Couldn't load libexif. 126
````

It is spontaneous and I haven't yet manged to find a way to replicate it for a reproducible case. Don't know if error messages are supose to ignore logging by design, but if they are then this is working as it is suppose to.

**Comment by rogerwang** [comment]
@ghostoy please check the error msg case. debug.log in the binary directory should be able to turn off completely. It should behave as https://www.chromium.org/for-testers/enable-logging

**Comment by ghostoy** [comment]
@rogerwang This logging is because of decoding corrupted image file, for example bad icon provided in `package.json`. We can ship libexif to prevent logging just like Chrome.

But libexif is deprecated in latest Chromium upstream. See https://chromium.googlesource.com/chromium/src/+/cd96b6f874573d7089bf2eb9d54ed53d7469bb56.

**Comment by rogerwang** [comment]
why the log goes to debug.log, not chrome_debug.log in user data dir?

**Comment by ghostoy** [comment]
Every log message created by `LOG(severity)` will be output to `g_log_file_name` if `g_logging_destination` contains `LOG_TO_FILE` flag.

It happens on Windows only because `g_logging_destination` is initialized to `LOG_TO_FILE` on Windows, but set to `LOG_TO_SYSTEM_DEBUG_LOG` on other OSes (see https://github.com/nwjs/chromium.src/blob/nw13/base/logging.h#L158-L160). Then `g_log_file_name` will be initialized to `debug.log` on the side of `nw.exe`. If the log file creation fails, it will try to create `debug.log` in current directory.

We can try to init `g_logging_destination` to `LOG_TO_SYSTEM_DEBUG_LOG` on Windows. This will fix this issue completely, but there may be some side effects we don't know.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by bluthen** [comment]
It appears to be doing this again at least in v0.87.0
