### ISSUE TITLE
Can't debug no domain modules

### ISSUE THREAD

**Issue by chrisjandrade** [nwjs/nw.js#4682]
Windows 7 Home Premium x64
nw 0.13.0-sdk
node v4.2.2

Previously I was able to step into, or view source code for my own node modules that I include in using require.

For example:

in index.html
`<script src="js/app.js"></script>`

and in the app.js file

```
var Controller = require('../app/controllers/main.js');

var app = (function (app) {
  var controller = Controller({ id: 'main-controller' });
  controller.check('something'); // I would like to debug this code
  
  app.ctrl = controller;
  return app;
}(app || {}));
```

However I am no longer able to step into this code using the dev tools.

Also, I can not look at the source code to set a break point.
Here are screenshots comparing 0.12.3 and 0.13.0-sdk

**0.12.3**
![ss1](https://cloud.githubusercontent.com/assets/3063835/14282358/fe13c62a-fb0b-11e5-89e2-92699db163dd.png)

**0.13.0-sdk**
![ss](https://cloud.githubusercontent.com/assets/3063835/14282365/05dbca42-fb0c-11e5-896b-581ff145da41.png)

**Comment by rogerwang** [comment]
@ghostoy does this share the same root cause of #4269 ?

**Comment by ghostoy** [comment]
@chrisjandrade It's not a bug. Node modules are loaded in background page. If you want to debug into it, please open DevTools for background page as well. When you step into the function of Node modules, you will be focused to the devtools of background page and highlight the next statement.
And also you can try `--mixed-context` CLI argument (see [JavaScript Contexts in NW.js](http://docs.nwjs.io/en/latest/For%20Users/Advanced/JavaScript%20Contexts%20in%20NW.js/)), which will load Node modules within the same context of your page. Then you can debug the script within one devtools window.

@rogerwang It's not related to that issue. However since the debugging behavior is different from 0.12, we should note it in our document site. Three pages may be related:

* [JavaScript Contexts in NW.js](http://docs.nwjs.io/en/latest/For%20Users/Advanced/JavaScript%20Contexts%20in%20NW.js/)
* [Debugging with DevTools](http://docs.nwjs.io/en/latest/For%20Users/Debugging%20with%20DevTools/)
* [Migrate from 0.12 to 0.13](http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/)

**Comment by maxbarry** [comment]
I've found my modules aren't in "Source" in the Dev Tools of the background page, either. 

For example, using the same test case as https://github.com/nwjs/nw.js/issues/4269#issuecomment-199627254, neither "Inspect" -> "Sources" nor "Inspect background page" -> "Sources" contains  "myModule.js" in nwjs 0.13.3. But it is there in 0.12.3, under "file://".

**Comment by RohitSharma27** [comment]
I am using nw 0.13.0 on Mac OS X El Capitan. When I am opening the devtool by "Inspect" and then when I go to the console, I see repetition of output that I have console logged in my "app.js" file which I have injected via "inject_js_start" from my package.json. The output on the console is from 2 different file it seems. One is from "VM181" and other from "app.js".
Why is this happening? I am having hard time trying to understand the reason behind this. And I am using 
`require('./myModule.js');`
as the last line in my "app.js".
The content of "myModule.js" is

> console.log('inside my module.');

I can't see this output being logged in the console window when I do "Inspect" -> "Console"
But,
It is there on the console when I do "Inspect Background Page" -> "Console"
And also the content of "app.js" is getting logged only once and that too because of "app.js".
And @maxbarry 's above comment is true. I am facing that issue too. I want to know the difference between "Inspect" and "Inspect Background Page".
Thanks.

**Comment by chrisjandrade** [comment]
@ghostoy Thanks
