### ISSUE TITLE
ERROR:image_metadata_extractor.cc(114)] Couldn't load libexif. 126

### ISSUE THREAD

**Issue by xvliang** [nwjs/nw.js#4694]

**Comment by rogerwang** [comment]
Do you have any more detail than just the error message? e.g.:

* which version are you using
* which OS version are you running with
* Provide steps to reproduce

**Comment by Yonezpt** [comment]
I also have it, as mentioned in https://github.com/nwjs/nw.js/issues/4637#issuecomment-207127742 and ghostoy indicated that this is caused by decoding a corrupt image file, suggesting custom icon as an example. Problem is I cannot replicate it on purpose, it happens sporadically. However, considering thats libexif is supposedly going to be dropped I don't know how important it should be to find a solution for this error.

NWJS: sdk0.13.3 and sdk0.14.0rc3 (haven't yet tested on 0.13.4)
OS: Win7x64

**Comment by rogerwang** [comment]
close as duplicate.
