### ISSUE TITLE
capturePage with hidden window

### ISSUE THREAD

**Issue by dasmike** [nwjs/nw.js#4814]
Hi.
I open new hidden window with

```
window.require('nw.gui').Window.open('http://site.com', {'show':false}, function(newWindow){
    newWindow.once('loaded', function(){
          newWindow.capturePage(function(data){console.log(data)}, {'format':'png'})
    })
})
```

and console.log() show me undefined. but with not hidden window evething is good.
this trouble I met with nw 0.13.4 but with 0.12.1 it works normally

**Comment by avb-qlik** [comment]
I'm having the exactly issue with 0.18.8. I don't know if the API win.capturePage works as designed in this case (from documentation http://docs.nwjs.io/en/latest/References/Window/#wincapturepagecallback-config I'm reading that this method captures the visible area of the window). And if so, is there any way for capturing hidden windows ?

**Comment by DjulLau** [comment]
Hi there,

Any progress about that ?
Is it possible to call capturePage on an hidden window ?

The behavior I got now with NW v0.19.5 / Windows is that the callback is not called if the window is opened with { show:false } ...

**Comment by danschumann** [comment]
The window can be called with `show: true`, and then `w.hide()`, and it still fails.  Any hidden window seems to fail.

**Comment by DjulLau** [comment]
`The window can be called with show: true, and then w.hide(), and it still fails. Any hidden window seems to fail.`
Yup :(

And for the record I've been trying to use an invisible iframe (because I was having trouble with windows) and it doesn't work either. The iframe needs to be visible and unobstructed (capturePage seems to capture more the area over the iframe than just the iframe content).

**Comment by danschumann** [comment]
I only need to capture 1 pixel, because I want to know if the user clicked on actual text or not...

I make my window size 1x1 and put it at x,y = 99999 ( off screen )

On windows, I can't make it 1x1(it's bigger), but I can put it off screen

On linux I can make it 1x1, but it is in the bottom right hand of the screen ( I haven't noticed it. )

Basically I just print whatever div I want, move it to -top/left of the mouse.x,y that the user clicked, and then see if the background is still the same.

**Comment by 1j01** [comment]
@danschumann If you wanted to get a Text node in the DOM that a user clicked on, you could use `getSelection().anchorNode`.
But if you really want only the shape of the text to be clickable, it seems like you'd have a much easier time drawing the text to a canvas and using `isPointInPath`, or using SVG and a `click` event.
And then you could do hover effects as well. But I don't know what your use case is.
I don't know if that's helpful, just.. making a tiny window to get the color of a pixel seems really roundabout / hacky (although clever / interesting)

**Comment by danschumann** [comment]
I've done the canvas method a few times.  I was going this route because it could be more flexible ( ie if there is a lot of dom structure, it could work better.

Native click detection wasn't an option for a while, but with all the changes I made, it might be an option again.. (perhaps thanks to pointerEvents: 'visiblePainted').  I have a 3d scene, actually nested 3d scenes, so I was having to do all the conversions myself.  I end up with an x,y of an element, and I need to manually detect if its painted or not.  ( hence the popup window, snapshotting, and detecting the color for that x,y )

I'll probably go the canvas route when I get around to it, though I always hate doing that because of needing to match the canvas element to the actual html element ( alignment, font-sizing, etc ).

The popup 1x1 window is nice because I can just apply the same css, rather than converting all the css into canvas things.  (there's all sorts of possible differences when converting an html element to svg or canvas -- word break, line heights, etc etc).

I could nix the text element being html in the scene, and just enforce everything being svg, which might be a better option, as well, and would at least solve my `testPoint(x,y)` problem.

**Comment by 1j01** [comment]
> I could nix the text element being html in the scene, and just enforce everything being svg
