### ISSUE TITLE
nw.Clipboard: image implementation discards png transparency (Windows)

### ISSUE THREAD

**Issue by bennol** [nwjs/nw.js#4825]
Copying a base64 encoded png to the clipboard using the new implementation of `clipboard.set()` of #4775 (built into v0.14.4) discards PNG transparency under Windows. Transparent pixels are replaced with black when pasted to Paint, Wordpad, Word or similiar.

Error occurred on Windows (7, 8.1, 10).
Everything is working fine under OSX.

```
var fs = require('fs');
var gui = require('nw.gui');
var clipboard =  gui.Clipboard.get();

var data = fs.readFileSync('./TESTIMAGE.png').toString('base64');
var dataURI = "data:image/png;base64," + data;
clipboard.set(dataURI, 'png', true); 
// clipboard.set(data, 'png', true); // changes nothing
```

**Comment by ghostoy** [comment]
@bennol NW.js did write alpha channels into clipboard via Windows clipboard API. However applications, like Paint, WordPad and MS Word, doesn't read alpha channel from clipboard. That causes the transparent black pixels become opaque black pixels. And some apps, like Paint.Net, does read the alpha channel.

In addition, MS Word also support pasting HTML snippets from clipboard, in which you can put `<img src="path/to/your/image">` to support images in MS Word.

I'm working on enhancing the clipboard API so that you can write multiple types of data into clipboard simutaneously. Then you can write an opaque image with white background along with an HTML snippet to clipboard to support all apps mentioned above.

**Comment by bennol** [comment]
@ghostoy Thanks for your reply and the hint!
I didn't believe that not supporting transparency from the clipboard was still a thing for big applications like these.
Multiple data types sounds promising - looking forward to any progress in this field. Thanks for the great work.

**Comment by zhenyuan2015** [comment]
I meet the same question as bennol, when I use clipboard to record png imagedata, the background is black. But when I download the image to write on the harddisk, the background is transparent.

**Comment by ghostoy** [comment]
@zhenyuan2015 Please read my previous comment.

I suggest you can put multiple types of data into clipboard simultaneously. For example, you have an image saved in `image.png` and you have already read it into a buffer `imgBuf`. You can use:

```javascript
var clip = nw.Clipboard.get();
clip.set([
  {type: 'png', data: imgBuf.toString('base64'), raw: true},
  {type: 'html', '<img src="path/to/image.png">'}
])
```

For more details, please read official document: http://docs.nwjs.io/en/latest/References/Clipboard/#clipsetclipboarddatalist

**Comment by zhenyuan2015** [comment]
thanks 
i tried your suggest, and your code throw error.
I used this:
clip.set(
					 '<img src="app/images/preview.png">', 'html'
				);

it does not throw error ,but set clipboard nothing.
I use nwjs 15.4

**Comment by ghostoy** [comment]
@zhenyuan2015 Sorry. I forgot the `data:` for the html type.

**Comment by zhenyuan2015** [comment]
it throws error:
extensions::schemaUtils:113 Uncaught Error: Invocation of form nw.Clipboard.setSync(array, string, boolean) doesn't match definition nw.Clipboard.setSync(string content, string type, boolean raw)normalizeArgumentsAndValidate @ extensions::schemaUtils:113(anonymous function) @ extensions::binding:414NWClipboard.set @ extensions::nw.Clipboard:41(anonymous function) @ dom.js:679dispatch @ jquery.js:4435r.handle @ jquery.js:4121

**Comment by ghostoy** [comment]
@zhenyuan2015 Which version of NW.js were you using?

**Comment by zhenyuan2015** [comment]
how to check my version?

**Comment by ghostoy** [comment]
`process.versions['nw']`

**Comment by zhenyuan2015** [comment]
0.15.3

**Comment by ghostoy** [comment]
@zhenyuan2015 Multiple type data was added in 0.15.4 (Stable) and 0.14.7 (LTS).

**Comment by zhenyuan2015** [comment]
I tried "0.16.0"
the same code did not throw error,but still get a black background image  in clipboard
	clip.set([
					{type: 'png', data: base64Data, raw: true},
					{type: 'html',data:  '<img src="app/image/preview.png">'}
				])

**Comment by ghostoy** [comment]
@zhenyuan2015 Please read my previous comments on the usage of multiple type of data. The image data in clipboard was correctly set with alpha channels by NW.js. However apps like Word or WordPad doesn't handle alpha channels well. And some other apps, like Paint.Net, can get the correct image. If you are developing native apps reading images from clipboard, you should handle alpha channels properly like Paint.Net.

Multiple type data is used to support Word, which picks images in an order. For example, Word prefers HTML type over raw images. So you can put both HTML and image in the clipboard so that Word can pick HTML for rendering. Meantime apps, only reads images, should process the alpha channels correctly.

**Comment by zhenyuan2015** [comment]
you are right ,pain.net does handle correctly the transparent image.
And many other apps cannot display transparent .
I wonder why there are so many apps even like office cannot handle clipboard image data corrently?

**Comment by ghostoy** [comment]
@zhenyuan2015 Well, I can't answer for them...
