### ISSUE TITLE
MP4 videos were working in previous versions, not in 0.14.6

### ISSUE THREAD

**Issue by joshterrill** [nwjs/nw.js#4977]
I have a video embedded in my app running nwjs 0.14.6 that's no longer working. We were running 0.12.2 (I believe) prior, and it was working fine. Any special trick to getting this to work in 0.14.6?

**Comment by RohitSharma27** [comment]
You are gonna have to compile and build your own ffmpeg, i guess. The steps are there in the latest documentation on nwjs.io and you will have to buy license as well, i think. I hope it helps. Cheers. :)

**Comment by rogerwang** [comment]
http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/

**Comment by frankhale** [comment]
If you don't want to roll your own ffmpeg then you can try to replace the ffmpeg with the one that Electron ships (which is what I do) because it has more codec support compiled in by default.

**Comment by joshterrill** [comment]
@frankhale I tried replacing the Electron `ffmpeg.dll` file with the `0.14.6` one, and `nw.exe` won't even open. How exactly did you get it to work?

**Comment by frankhale** [comment]
Just by literally replacing the ffmpeg with one from Electron. I am using 0.15.2 x64 so picked compatible Electron with same Chromium release. In my case I had issues with stock NW.js not being able to play some YouTube videos. As soon as I replaced ffmpeg I was able to play the videos that weren't previously able to play due to the ffmpeg in NW.js not being compiled with some codecs.

I've been doing this for a while and it's working well for me.
