### ISSUE TITLE
NW.jS Custom build

### ISSUE THREAD

**Issue by NegativeIQ** [nwjs/nw.js#4984]
Guys, how about some way of making custom builds of NW.js? Mainly chromium.
At the moment its a hude library (~90mb on windows), and for some simple apps its overkill.
So if we could strip down everything we dont need that would be awesome.

**Comment by rogerwang** [comment]
close as duplicate of #3955

**Comment by frankhale** [comment]
I think people commonly forget what they are actually getting in those 90 megabytes. You are getting a complete platform in order to develop apps and it's a very small price to pay for such raw power. Put your app on a thumb drive. I recently bought a 32 gigabyte thumb drive for $11 US dollars. Space is cheap.
