### ISSUE TITLE
Application cache max size

### ISSUE THREAD

**Issue by Wujerry** [nwjs/nw.js#4991]
OS: window XP/7/10
nwjs: 0.14/0.15

* Any way to change Application cache max size?
* ``nw.App.clearCache()``did not clear Application cache 

I considered pack my app , but my app is high frequency updated

thanks

**Comment by rogerwang** [comment]
Will fix the limit and clearCache. For now you can use '--unlimited-storage' to workaround it.

**Comment by Wujerry** [comment]
##Test
* OS: windows10 x64
* Version: nwjs-sdk-v0.15.5-win-ia32

##Result
``App.clearAppCache(manifest_url)`` works fine

thank for your time

**Comment by Yonezpt** [comment]
I don't understand what should be inserted as `manifest_url`, does it have to be a direct path to the package.json file like `"chrome-extension://" + chrome.runtime.id + "/package.nw/package.json"`? The wiki does not explain this part and using the path I mentioned does not appear to make any difference, the cache folder decrease its size.

**Comment by Wujerry** [comment]
@Yonezpt I did this in my app:
``nw.App.clearAppCache(window.location.origin+'/app.manifest');``

**Comment by Yonezpt** [comment]
I don't think that that is even a valid manifest link, are you certain that it is working correctly? Does it also work if you change "/app.manifest" to "/manifest_url"? Where did you find that url? Because I cannot find any mention of "/app.manifest" being a valid manifest path anywhere.
I get no errors trown for any type of string I use and since there is no callback option I can never tell if a cleanup actually happened.
I just tried `nw.App.clearAppCache("asdasdasd")` and there was no difference from using your url, no errors and no size reduction in the cache folder either.

**Comment by Wujerry** [comment]
@Yonezpt 
``<html ng-app="app" manifest="app.manifest" >``
``app.manifest`` is the name of your manifest file.

You can see this in chrome developer tool console:
``Document was loaded from Application Cache with manifest http://192.168.4.61/app.manifest``

**Comment by Yonezpt** [comment]
I don't think that the manifest you are referring to is the same manifest that is suppose to be linked. This is mainly for offline browsing, which is deprecated: https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache

This is the actual manifest that I assume should be used with `clearAppCache` : http://docs.nwjs.io/en/latest/References/Manifest%20Format/

Which is usually named `package.json`. @rogerwang or @ghostoy could either of you clarify this whenever you have some free time? Exactly which manifest_url should be passed to `nw.App.clearAppCache`?
