### ISSUE TITLE
No event for check internet connectivity

### ISSUE THREAD

**Issue by freddy-tech** [nwjs/nw.js#5156]
NW JS is great tool for HTML cross-platform apps but.There is still in-completion in this tool.I need event firing when lose internet connection (not network connectivity).navigator.Online can't give such a feature.Why this chromium based tool don't have this great feature.I don't like to use any setTimeout,setInterval functions and lookup(timeout functions make performance issues).

**Comment by rogerwang** [comment]
I think you'll need to define "internet connection". Then you could check it in the event listener of the navigator event.

Defining "internet connection" is an interesting topic and should be left to application programmer. Here on my android phone the system checks internet connection by pinging Google server and it fails due to the Great Firewall of China. And when you develop an enterprise application which is supposed to run inside the intranet it would be better to ping some well know corporate servers.

**Comment by freddy-tech** [comment]
I know ping/dns-lookup is an option but it need to run in every intervals..

**Comment by kailniris** [comment]
@freddy-tech Actually performance wise an ajax or ping is not a big deal, they are pure async so your users will not notice about them. You can also use socket.io which has built in connection checkings in them.

The other part is, lets assume that nw.js has some connectivity check built in which has a hight chance to work the same as the examples above.
