### ISSUE TITLE
Child process spawned from browser context starts in node context

### ISSUE THREAD

**Issue by drunksaint** [nwjs/nw.js#5182]
I needed to use child processes to perform cpu intensive tasks. The problem is that these tasks make use of apis from the browser context (like indexeddb, chrome filesystem api and xmlhttprequest) but the child process starts in node context. is there a way to start this child process in the browser context?

I'm using nwjs v0.15.4 on ubuntu 14.04. I'm starting a child process this way: `require('child_process').fork('./child_process_file.js');`

**Comment by RohitSharma27** [comment]
The object that will be returned from this fork call is going to have a built in communication channel. So, pass on indexdb, File objects from parent to the child and in your child_process_files.js, listen for these parameters and use them as you may. Since the execution environment is same, it should work. Do let me know if it works or doesn't. It should, I guess.

**Comment by rogerwang** [comment]
You can use the 'new_instance' option to open a new hidden window in a separate process.

And please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
