### ISSUE TITLE
Feature request: support multiple tabs like chrome

### ISSUE THREAD

**Issue by mangaga** [nwjs/nw.js#5205]
when i open a new url with window.open， I want to it opened in a new tab page not a new window，is it possible to provide a api to support this？  thank you.

**Comment by mscreenie** [comment]
Use Webviews and some JS? How would it differ from tabs and what functionalities would you be missing?

**Comment by mscreenie** [comment]
@mangaga Use Webviews and some JS? How would that differ from tabs and which functionalities would you miss from doing this to regular tabs?

**Comment by frankhale** [comment]
I agree with @mscreenie, there are a few tab libraries out there that mimic the Chrome look and feel. 

Here is one that looks just like Chrome tabs:

https://github.com/alanshaw/br-chrome-tabs

**Comment by ghostoy** [comment]
As @mscreenie suggested, you could use HTML & webview tag to simulate "tabs" in browser. 

@mangaga I don't understand the scene you shown. Would you please show why is it necessary to implement it in native tab ui other than using HTML & webview?

**Comment by mangaga** [comment]
I just want to made window.open(url) show in a new tab, and this behavior is from nw itself .  Otherwise I need to change my layout of site. And if I want to make the tabs at the top of screen，I need  to set nw without frame and adjustment all my css. 

If you think the request may be not very  necessary for most，I’ll close  it. Thks all.

**Comment by frankhale** [comment]
@mangaga there is a new-window event on the Window object that you can use to redirect a window.open to do whatever you want in your app.

http://docs.nwjs.io/en/latest/References/Window/#event-new-win-policy-frame-url-policy

**Comment by frankhale** [comment]
@mangaga using a webview is going to give you the isolation you desire for each page you load. It's like a iframe but better!

**Comment by ghostoy** [comment]
What you need is to write a page that have tab-like UI with any JS frameworks you like and intercept up all window opening requests with `new-win-policy` and open the requested URL in `<webview>`. `<webview>` is rendering out of process, which means it won't break your app out of `<webview>` even pages in `<webview>` are crashed. You can look into the [document](http://docs.nwjs.io/en/latest/References/webview%20Tag/) of `<webview>` for the usage.

I'm closing this issue since the request can be done with existing APIs. Be free to reopen it or raise another issue if you believe there is anything you can't do with NW API or `<webview>` tag.
