### ISSUE TITLE
Significant performance different between Chrome and NW.js on Mac for https://material.angularjs.org

### ISSUE THREAD

**Issue by alexcriss** [nwjs/nw.js#5241]
I am seeing a significant difference in performance when browsing https://material.angularjs.org with Chrome on a Macbook Pro Retina 13" (early 2015) and when using NW.js 0.16.1 (SDK) with --url="https://material.angularjs.org".

The issue can be better seen by navigating to the demo page and going to the dialog demo. Here, just open a custom dialog and dismiss it. NW.js takes much more time to dismiss the dialog and after it is gone the page remain unresponsive for even more time (no scroll, no input). On Chrome the webpage works "as expected", that is the dialog goes away imemtiale and then the page is usable

**Comment by ghostoy** [comment]
@alexcriss I didn't see the slowness on my Mac mini (late 2014) with Core i7 & Intel Iris 1536 MB GPU.

**Comment by alexcriss** [comment]
@ghostoy 

I can replicate it 100% with my hardware, running on El Capitan. If I can help with logs I will be more than willing to provide them, I just need instructions about what/how to collect :)

What I cam doing is nothing more that navigating with chrome or with a NW.js app launched with --url

**Comment by iteufel** [comment]
Hardware acceleration isn't supported anymore for older Macs since Chromium 53.

## Hardware
- MacBookAir4,1
- Intel HD Graphics 3000

## Graphics Feature Status
- Canvas: Software only, hardware acceleration unavailable
- Flash: Software only, hardware acceleration unavailable
- Flash Stage3D: Software only, hardware acceleration unavailable
- Flash Stage3D Baseline profile: Software only, hardware acceleration unavailable
- Compositing: Software only, hardware acceleration unavailable
- Multiple Raster Threads: Unavailable
- Native GpuMemoryBuffers: Software only, hardware acceleration unavailable
- Rasterization: Software only, hardware acceleration unavailable
- Video Decode: Software only, hardware acceleration unavailable
- Video Encode: Software only, hardware acceleration unavailable
- WebGL: Unavailable

## Problems Detected
- GPU process was unable to boot: All GPU features are blacklisted.
- Disabled Features: all
- Intel HD 3000 driver crashes frequently on Mac: 592130
- Disabled Features: all
- Some GPUs on Mac can perform poorly with GPU rasterization. Disable all known Intel GPUs other - than Intel 6th and 7th Generation cards, which have been tested.: 613272, 614468
- Disabled Features: gpu_rasterization

**Comment by Christywl** [comment]
I don't find the significant slowness on MacBook Pro (Retina, 13-inch, Early 2015) between Chrome M56 and nwjs-sdk-v0.21.3.

**Comment by rogerwang** [comment]
close until more information is available.
