### ISSUE TITLE
App is seen as trojan horse by F-Secure antivirus

### ISSUE THREAD

**Issue by bengyles** [nwjs/nw.js#5457]
So we converted our Chrome Packaged app to an nw.js app and it works fine! But we tested it on a computer with F-Secure antivirus installed and it was seen als a trojan horse so it didn't want to run. Is there a way this can be resolved in code, do we need to provide a workaround for our users and does anyone know other anti virus software that could be a problem when using nw.js?

I think it's best for everyone who uses nw.js that we don't just get blocked by another program so if you know other software that blocks it please add it to the comments.

the article on the website of F-secure can be read here: [https://www.f-secure.com/v-descs/trojan_w32_nomadsnore.shtml]( https://www.f-secure.com/v-descs/trojan_w32_nomadsnore.shtml )

**Comment by TheJaredWilcurt** [comment]
NW.js has a feature that allows you to protect your source code by doing a V8 snapshot. This comes from Roger's philosphy with NW.js, that a JS developer should be able to do anything a C/C++ developer can do with a native desktop app. Including compile the code so that the source is obscured.

About a year ago someone used this feature to package an infection. We had people from Norton and Trend Micro in the Gitter chat trying to find out how to reverse engineer the infection. Unfortunately for them no one has yet been able to reverse engineer an NW.js V8 snapshot. That however *is* a positive thing to the 99.9% of people who are using it for closed source enterprise purposes and not for malicious intent.

Unfortunately, however, many protection software companies use heuristics algorithms to look for files that *similar* to known infections. Since there was a cataloged infection wrapped in NW.js, now all NW.js apps get flagged with a false-positive from these programs.

The best thing you can do is report to that company a link to the NW.js executable download as a known good/safe source. So they can white-list it. 

* https://www.f-secure.com/en/web/labs_global/submit-a-sample

If you know which version of NW.js you were using that got falsely flagged, you should mention that so that others can submit reports as well to F-Secure to get them to fix this.

**Comment by shamun** [comment]
Roger's philosophy is absolutely correct. 

When a C/C++/Java/Go coders code we cant see there source code and for that they feel proud, same way why would we show our code? Therefore Roger did the right thing. 

its not NodeWebkit issue, Norton and others has to fix it they are getting paid for it, put pressure on there neck not on NodeWebKit. 

And also they should contribute in NodeWebKit to improve the code of Roger's philosophy instead of flagging as virus "what a nonsense"

**Comment by ghostoy** [comment]
@bengyles You can report to the antivirus as false alarm.

**Comment by rogerwang** [comment]
Thanks all for the explanation and the information from chat room.

**Comment by bengyles** [comment]
Thank you guys! It's going to be a whole process I'm afraid to contact all those antivirus companies but I guess that's what I'm going to have to do for now...
