### ISSUE TITLE
Monitoring node-main process

### ISSUE THREAD

**Issue by pablozandona** [nwjs/nw.js#5458]
I need to monitor node-main process, to restart it on exception crashes.
How do this?

**Comment by georgir** [comment]
https://nodejs.org/api/domain.html
run your code in a domain with error handler that exits the process, and run your process from a wrapper that will auto-restart it when it exits, like nodemon or forever or even just a while true in a shell script

you can also use the child processes api or a js library that does instead of a wrapper process for this. however i'm not sure how well spawn/fork/etc would work when ran from nw - both parent and child processes would likely try to have the webkit gui elements, which might be problematic, or at the very least inefficient. it'd be better to use pure node.js for one of the processes if available on the system.
