### ISSUE TITLE
how to get packaged app version

### ISSUE THREAD

**Issue by feverzy2** [nwjs/nw.js#554]
hi，i'm new here，
i just found node-webkit so amazing ！
 follow some steps，
i can easily package my html app into a native windows desktop app，

but when i try to achieve app auto update。
i can't find a way to get current app version to compare with the server。

any help will be thankful！

**Comment by djmisterjon** [comment]
i update this because searching fast anwser and fall on this with no solution.
So for ask about 
**how to found package.json in nwjs**
**how to found loaded manifest in nwjs**
use `nw.global.manifest`
![image](https://user-images.githubusercontent.com/24865815/149628467-4785f918-23e1-46d6-81a1-e3b59cd644a5.png)

**Comment by ayushmanchhabra** [comment]
Even `nw.App.manifest.version` works
