### ISSUE TITLE
Wrong Node Webkit Application open in Mac in case of URI invoke

### ISSUE THREAD

**Issue by Mayank516** [nwjs/nw.js#5592]
Hi @rogerwang 

Steps to reproduce :
* Install two different node webkit applications(.app files) with same node webkit version on Mac
* Register one application for URI invoke (eg. abcde://) using following entry in info.plist:
```xml
        <key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLName</key>
			<string>com.abc.abcde</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>abcde</string>
			</array>
		</dict>
	</array>
```
* Close the application which is just registered for URI invoke and open the other application.
* Now use URI invoke (abcde://) from Safari to invoke application. Instead of registered application second application comes in foreground. If both applications are closed or open then correct application is launched.

* Node Webkit : NW 14.7
* OS : Mac OS X Sierra (Any OS X)

**Comment by rogerwang** [comment]
Does it happen with latest 0.19?

**Comment by Mayank516** [comment]
Hi @rogerwang 

Yes, we have verified it with 0.19.3 and it is still reproducible.

**Comment by ghostoy** [comment]
@Mayank516 Did you tried to set a different `CFBundleIdentifier`?

**Comment by Mayank516** [comment]
@ghostoy 

Thanks for the response.
Yes, I have tried it with different bundle identifiers and it is still reproducible.

**Comment by ghostoy** [comment]
Looks like this issue is caused by `CFBundleSignature`. You can set it to your own 4-character signature and try again.

**Comment by ghostoy** [comment]
These info might be cached by Launch Services in macOS. So internally it might be stay the old value and you won't see any difference after changing `Info.plist` and `PkgInfo`. You can use following command to rebuild the cache and try launch it again:

```bash
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user
```

**Comment by ghostoy** [comment]
@Mayank516 Could you test if previous suggestions work for you?

**Comment by Mayank516** [comment]
@ghostoy 

Thanks, for your suggestions. It worked for us.

**Comment by ShivaniPahuja02** [comment]
Hi @ghostoy,

we are also facing similar issue on nwjs build 14.7 on MAC. Custom uri was invoking wrong node webkit application.
As a solution we tried the approach proposed by you,changed the last 4-characters in PkgInfo and cleared the cache. This solution worked for us. we did all the changes in final 
nwjs build by extracting build package. But now we were trying to make changes in code itself so that final build PkgInfo and Info.plist should contain new value rather than ApplCr24. we changed mac creator  in file "chrome_settings.gypi"  as 'mac_creator': 'abcd'.

After this change PkgInfo in nwjs build still have ApplCr24 .we request you to please suggest how can we achieve this by code as now we are manuaaly replacing values each time we create a nwjs build.


Regards,
Shivani Pahuja
