### ISSUE TITLE
Facebook/VK displaying in iframe

### ISSUE THREAD

**Issue by monobogdan** [nwjs/nw.js#5619]
Facebook and VK not loading in iframe.
VK: blink and whitescreen
Facebook: Offer to go to facebook.com
Screenshots:
https://imgur.com/a/MHESC

**Comment by CosmoMyzrailGorynych** [comment]
Информативно — трындец. Ты бы хоть код добавил.

This is because facebook and VK have some basic protection against simple embeds of their main pages. Facebook tries to change his top location (nw) to Facebook to avoid XSS attacks, simple bots, etc.
Actually, FB and VK try to attack you instead and FB easily gets access to parent window.

![fghj](https://cloud.githubusercontent.com/assets/3174357/21789340/b2773574-d730-11e6-8553-1301151539f6.JPG)

Use [webview](http://docs.nwjs.io/en/latest/References/webview%20Tag/) and live in happiness.  Otherwise, use [special attributes for unsafe frames](http://docs.nwjs.io/en/latest/References/Changes%20to%20DOM/#iframe).

![adsasd](https://cloud.githubusercontent.com/assets/3174357/21789271/4175daf6-d730-11e6-9202-caed5ada5f0b.JPG)

**Comment by monobogdan** [comment]
webview can't handle newwindow :+1:

**Comment by rogerwang** [comment]
Does nwfaketop iframe work for you?

**Comment by monobogdan** [comment]
yes, but both iframe and webview can't handle newwindow

**Comment by rogerwang** [comment]
Cloud you give more details and how would you like it to be handled?

**Comment by rogerwang** [comment]
close until more information is provided.
