### ISSUE TITLE
The custom ICO of nw app  is invalid on Windows TaskBar

### ISSUE THREAD

**Issue by finscn** [nwjs/nw.js#5662]
In Windows 7  ,  the custom icon of my nw app is invalid on TaskBar and  `task switch bar (alt+tab)`.
there is still default icon of nw.js.

But the icon of  exe file is OK.

-------------------------------
NwJS version:   0.20.0-rc1  

OS :  Windows 7  64bit  

And  I build the app on macBook  , the wine is the last version on brew.

**Comment by SchizoDuckie** [comment]
The culprit seems to be that the shortcut that is created on the fly is looking at a specific icon file that is not provided by the icons section in package.json or something we control:

![image](https://cloud.githubusercontent.com/assets/111710/22444087/bf09094a-e741-11e6-802c-a76202db8a5e.png)

I have attached an example link for DuckieTV
[DuckieTV-Standalone.lnk.zip](https://github.com/nwjs/nw.js/files/740557/DuckieTV-Standalone.lnk.zip)




I do see where you're going with this, no more resource hacking (which I applaud!)

**Comment by finscn** [comment]
@SchizoDuckie ,  Sorry , my english is very bad . I can't understand you. 
I know (with google's help) every word in your sentences ， but I don't know what's your mean.

**Comment by Christywl** [comment]
custom icon in package.json works well for me on Windows 8. The icon on the taskbar is my custom icon, not nwjs default icon.
```
{
    "name": "test",
    "main": "index.html",
    "window": {
	 "width": 800,
        "height": 600,
        "icon": "customicon.png"
	}
}
```
@finscn , could you please upload your sample for me to reproduce your issue?

**Comment by Christywl** [comment]
close until there is more information
