### ISSUE TITLE
BUG - OSX 10.11.6 Screen capture does not work

### ISSUE THREAD

**Issue by shamun** [nwjs/nw.js#5689]
nwjs version 0.20.1 - works in Windows but not in OSX. 
it shows the screen capture selection popup, but after clicking the share button, no stream is captured / not showing in the success_func canvas.

```
function success_func(stream) {
document.getElementById('video_1').src = URL.createObjectURL(stream);
                        stream.onended = function() { console.log("Ended"); };
}

window.onload = function() {
  gui.Screen.Init();
  gui.Screen.chooseDesktopMedia(["window","screen"],
    function(streamId) {

      var sourceId = "screen:0";
      var vid_constraint = {
        mandatory: {
          chromeMediaSource: 'desktop',
          chromeMediaSourceId: sourceId,
          maxWidth: 1920,
          maxHeight: 1080
        },
        optional: []
      };
      navigator.webkitGetUserMedia({audio: false, video: vid_constraint}, success_func, fallback_func);
    }
  );
}
```

**Comment by ghostoy** [comment]
Two issues of your code snippet.

1. The hardcoded `sourceId` "screen:0" doesn't work for macOS. Please try [Screen.DesktopCaptureMonitor](http://docs.nwjs.io/en/latest/References/Screen/#synopsis_1) to get the real id of the screen.
2. `chromeMediaSourceId` should be passed to a stream id obtained by [Screen.DesktopCaptureMonitor.registerStream(sourceId)](http://docs.nwjs.io/en/latest/References/Screen/#screendesktopcapturemonitorregisterstreamid). The stream id is limited only to be valid in a few seconds after registration in order to prevent holding resources during the whole life time of your app.

Following is the suggested way to stream the entire screen to a `<video>` tag.

```javascript

var dcm = nw.Screen.DesktopCaptureMonitor;
nw.Screen.Init();
dcm.on("added", function (id, name, order, type) {
   //select first stream 
   var constraints = {
      audio: false,
      video: {
         mandatory: {
             chromeMediaSource: 'desktop',
             chromeMediaSourceId: dcm.registerStream(id),
             maxWidth: 1920,
             maxHeight: 1080
         }
      }
  };

  navigator.webkitGetUserMedia(constraints, success_func, fallback_func);

  // ... and shutdown the monitor
  dcm.stop();
});

// start monitor screens only
dcm.start(true, false);

```

**Comment by ghostoy** [comment]
Please kindly close this issue if it solves your problem.
