### ISSUE TITLE
nw.js with express RegExp Not working !

### ISSUE THREAD

**Issue by YeTech** [nwjs/nw.js#5719]
when i run this code from node it works fine ,
but when i run it in **nw.js** the RegExp routes didn't work error message : `Cannot GET /id`  ,

**index.js**

`var express = require('express')`
`var exp_app = express();`

`exp_app.get(/\/id/i, function (req, res) {`
  `res.send('Hello from id!')`
`});`

`exp_app.get('/', function (req, res) {`
  `res.send('Hello World!')`
`});`

`exp_app.listen(80, function () {`
 ` console.log('Example app listening on port 80!')`
`})`

**index.html**
`test`
`<script src="index.js"></script>`

**Comment by rogerwang** [comment]
This is because express is not compatible with NW's default 'separate context' mode, where DOM and Node has different context. Express thinks RegExp from DOM is not RegExp type in Node. You can run NW in mixed context mode to work around. Or change source code.

See more here: http://docs.nwjs.io/en/latest/For%20Users/Advanced/JavaScript%20Contexts%20in%20NW.js/
And #890
