### ISSUE TITLE
webview clearData not working in mac nwjs 0.18.8 

### ISSUE THREAD

**Issue by zhailei31665431** [nwjs/nw.js#5763]
webview url  http://127.0.0.1/index.html  and set localStorage.settimeout  then click button clearData  not work ....
```
let webview = document.getElementById('phone-inset');
      var data = {
        appcache: true,
        cache: true,
        cookies:true,
        fileSystems: true,
        indexedDB: true,
        localStorage: true,
        webSQL: true
      }
      webview.clearData({
        since: 0
      }, data, () => {
        webview.reload();
        console.info('WebviewBody.js _clearWebviewData success!')
      })
```

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux and Mac with nwjs-sdk-0.21.0, webview.clearData works fine for me. 
![screen shot 2017-03-10 at 2 33 07 pm](https://cloud.githubusercontent.com/assets/20039821/23785040/9baf2c36-05a0-11e7-91ca-8bc4cd0f0f3b.png)

My code:
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
</head>
<body style="width:800px; height:800px">
  <div style="width:800px; height:800px">
    <webview src="https://nwjs.io" id="webview" style="display:block;width:700px; height:700px"></webview>
  </div>
  <button id="clear">clear data</button>
  <script type="text/javascript">
  window.onload = () => {
    var webview = document.getElementById('webview')
    var clear = document.getElementById('clear')

    clear.addEventListener('click', () => {
      var data = {
        appcache: true,
        cache: true,
        cookies:true,
        fileSystems: true,
        indexedDB: true,
        localStorage: true,
        webSQL: true
      }
      webview.clearData({
        since: 0
      }, data, () => {
        webview.reload();
        console.info('WebviewBody.js _clearWebviewData success!')
      })
    })
  }
  </script>
</body>

</html>
```

**Comment by zhailei31665431** [comment]
@Christywl My code also consoe ...You must add localStorage in webview to test..... that is not work

**Comment by Christywl** [comment]
@zhailei31665431 ,could you please share your test case for me to reproduce this issue?

**Comment by rogerwang** [comment]
close until more information is available.

**Comment by corwin-of-amber** [comment]
I am trying this on Mac with 0.27.0-beta1-sdk and I noticed that clearData returns "false" (with `chrome.runtime.lastError == undefined`) when the webview does not have a loaded page. Remove `src="https://nwjs.io"` from your sample document and you will see.

Not sure if this is what the OP meant. However it seems reasonable to clear the storage **before** loading the page rather than after the page has been loaded (and possibly already had a chance to observe the storage). Chrome's documentation is vague if `clearData` is actually supposed to clear data saved by all visited domains.
