### ISSUE TITLE
NW.js crashes when requiring aws-sdk package and embedded youtube video present on page

### ISSUE THREAD

**Issue by jaredmcateer** [nwjs/nw.js#5980]
Running this using the Ubuntu 16 LTS. I've tested this with `nw` version `0.23.0`, `0.23.1`, `0.23.2`, `0.23.3`, and `0.24.0-beta1sdk`.

To reproduce simply install the dependencies using the npm-shrinkwrap.json provided in the sample and run the app. The app will crash while loading the `index.html`.

I've boiled this down to the smallest test case I could and included a crash dump.

[youtube-crash-test.tar.gz](https://github.com/nwjs/nw.js/files/1095354/youtube-crash-test.tar.gz)

**Comment by jaredmcateer** [comment]
I should note that I've also tested this in early versions as well but `0.23.0` is when I've found the problem to manifest.

**Comment by kpineo** [comment]
I may be experiencing the same issue, except I've been experimenting with Stripe's JS SDK. It adds multiple iframes into the page. Can use either on their own, but the second I try to load both it crashes.

Ubuntu 16.04.2 LTS
NodeJS: v6.11.0 - LTS
NW.js: v0.23.5

[AWS_SDK_Stripe_Crash.zip](https://github.com/nwjs/nw.js/files/1106592/AWS_SDK_Stripe_Crash.zip)

**Comment by jmx** [comment]
we are having this issue in any of our content that loads a video from youtube (our application is a content management system so the reproduction step at this stage is non-trivial).  I'll attempt to get a simple repro case during the week but I can confirm that:
a) this issue is more severe and less esoteric than the examples above might imply.  We don't use the AWS SDK, for example.
b) issue did not occur in 22.x, but occurs as of 23.x+

**Comment by Christywl** [comment]
I can reproduce this issue on Linux with nwjs-sdk-v0.23.5.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build. It will be released with 0.25.0 soon.
