### ISSUE TITLE
Not able to play flash videos.

### ISSUE THREAD

**Issue by Ajeey** [nwjs/nw.js#6097]
I am trying to play the following flash video(http://www.flashls.org/latest/examples/chromeless/) in node webkit version - 0.24.2 by embedding the url in an iframe.
```<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Test</title>
</head>
<body>
    <h1>Hello World :-)</h1>
   <iframe src="http://www.flashls.org/latest/examples/chromeless/" width="1200px" height="1000px"></iframe>
</body>
</html>
```

In package.json, I have enabled the following configuration - 

`
"webkit": {
		"plugin": true,
		"page-cache": true
	},
"chromium-args": "--ignore-certificate-errors --disable-web-security --ppapi-flash-path=plugins/PepperFlashPlayer.plugin --ppapi-flash-version=26.0.0.151",`

And in the plugins folder I have the pepper flash plugin along with the manifest file

But I am stuck at the screen which says - "Control-click to run adobe flash player"

<img width="726" alt="screen shot 2017-08-14 at 5 06 17 pm" src="https://user-images.githubusercontent.com/1799117/29270182-294453b2-8113-11e7-94da-46be3f3a35b8.png">

And when I ctrl+click, these are the options I got - 
<img width="995" alt="screen shot 2017-08-14 at 5 06 27 pm" src="https://user-images.githubusercontent.com/1799117/29270213-49aad6da-8113-11e7-8898-ba937f5c4fcb.png">

Please suggest what is the way ahead so that I can play flash videos! Thank you.

**Comment by Christywl** [comment]
Please refer to the doc: http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Flash%20Plugin/#using-flash-plugin

**Comment by Blatman** [comment]
FWIW I tried the supplied project from Gitter and it works fine if the PepperFlash is in the nwjs binary as per the docs but if not the fallback to system installed PepperFlash may not work - Adobe installs appear to install Flash Player.plugin into the Internet Plug-Ins folder rather than use the PepperFlash folder which nwjs needs. Because the Adobe install is in a different format I now have to install Chrome to get the latest PepperFlash folder to put into the nwjs binary. The latest Chrome install I did seemed to only install PepperFlash for Chrome and not update the system install so it is all a bit messy. See also #6072 
Cheers.

**Comment by Ajeey** [comment]
@Christywl the doc says to verify plugin via `--url='chrome://plugins'`
And chrome://plugins is blocked since chrome 57+. 
More info here - https://superuser.com/questions/1193959/chrome-plugins-not-working

Please suggest how to proceed. Thanks.

**Comment by Ajeey** [comment]
@Blatman did the supplied project just work without you having to do anything extra?

**Comment by Blatman** [comment]
@Ajeey  The only mod to the project was in package.json ----
"chromium-args": "--ignore-certificate-errors --disable-web-security",
I deleted the flash path/ver arguments as they mess up the pepperflash operation in the nwjs package (I have never found them to be workable). I find if the PepperFlash folder is not available in the nwjs binary then it usually falls back to the system install but ONLY if the system install has a pepperflash folder rather than Flash Player.plugin

To test I placed 0.24.3-sdk into the project root folder. This file had the latest PepperFlash folder inserted into the Internet Plug-Ins folder so -
node-webkit-flash-master/nwjs-0.24.3-sdk-pepper2600151+mpeg.app/Contents/Versions/60.0.3112.90/nwjs Framework.framework/Internet Plug-Ins/PepperFlash/PepperFlashPlayer.plugin (and also the associated manifest.json file).
The pepperflash was obtained from the Chrome Profile folders.

Initially you get a black screen then after clicking the load button the fabulously unique movie starts.

![works](https://user-images.githubusercontent.com/11089335/29357909-28f0d85e-8271-11e7-8daf-9ba0e7510ac7.jpg)

Cheers.

**Comment by Ajeey** [comment]
@Blatman Thanks let me try what you suggested :)

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by rogerwang** [comment]
close until more information is available.
