### ISSUE TITLE
Support for DevTool extensions

### ISSUE THREAD

**Issue by RobertLowe** [nwjs/nw.js#612]
Specifically DevTool extensions would be the most helpful.

I'm thinking it would be nice to use the [angular-batarang](https://github.com/angular/angularjs-batarang).

Any thoughts on a hack?

Can we programmatically get access to a devtools' window?

**Comment by Serabe** [comment]
Any hint about this? Currently, developing an Ember application with Ember-CLI without being able to use the Ember Inspector is a no-go.

Is this on the roadmap somehow?

**Comment by blackgate** [comment]
Try atom-shell, i switched because of this.

**Comment by rogerwang** [comment]
@Serabe it will be supported no later than nw13.

**Comment by rogerwang** [comment]
@ghostoy 0.13.0 beta should be able to support this. Could you please check it?

**Comment by ghostoy** [comment]
@RobertLowe DevTools extension can be loaded with [`chrome.developerPrivate.loadUnpacked`](https://developer.chrome.com/apps/developerPrivate#method-loadUnpacked). But it doesn't work. The content scripts appear not to be injected into the page.

**Comment by rogerwang** [comment]
How does Chrome user install devtools extension? Since we support many features of Chrome now, there shouldn't be much work to enable it in nw 0.13. Please find a way to enable it.

**Comment by ghostoy** [comment]
In Chrome, the extension is loaded in the `chrome://extensions/` view, and can be loaded through "Load Unpacked Extension ..." button, which simply call [`chrome.developerPrivate.loadUnpacked`](https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/resources/extensions/extension_loader.js&sq=package:chromium&type=cs&l=202).

**Comment by ghostoy** [comment]
Extensions like [Grunt Devtools](https://chrome.google.com/webstore/detail/grunt-devtools/fbiodiodggnlakggeeckkjccjhhjndnb) is currently supported via [chrome.developerPrivate.loadUnpacked](https://developer.chrome.com/apps/developerPrivate#method-loadUnpacked) API.

React and Angular devtools extension currently not working because of not able to injecting content scripts into the apps. 

I'll fix it in 0.13.0 and seek a better way to support these extensions without using APIs.

**Comment by TomKaltz** [comment]
+1

**Comment by ghostoy** [comment]
Currently extensions can be loaded with `--load-extension` CLI option.

But Angular or ReactJS extensions do not working because of following reasons:
* Chrome is not designed to enable injecting scripts into Chrome apps (see https://code.google.com/p/chromium/issues/detail?id=77440). And Angular or ReactJS extension depend on this feature. A simple patch can fix this issue.
* Chrome apps do not have a tab id, which is necessary for those extensions to dispatch and sending messages. I'm still blocking on this issue.

**Comment by jmx** [comment]
I've followed the rabbithole to here from #4440 
To further expand on @ghostoy's explaination above, It seems that the tabid is going to need to exist for a large number of these types of extensions (they're all going want to do chrome.tabs.sendMessage, chrome.tabs.executeScript or so)

I am currently trying to get the cerebral debugger working (which works in a similar way tot he React/Angular extensions mentioned above)

**Comment by TomKaltz** [comment]
@jmx I am interested in getting the cerebral debugger working in this environment.

**Comment by rogerwang** [comment]
It will be supported in the next beta version. Thanks

Thomas Kaltz III <notifications@github.com>于2016年2月24日周三 上午1:48写道：

**Comment by rogerwang** [comment]
Full devtools extension support (including react extension etc) is done. You can try the live build from http://dl.nwjs.io/live-build/02-24-2016/b0d83d7-d77fa71-b8fe343-bce39d3/v0.13.0-beta7/

It's tested with this sample:
https://s3-us-west-2.amazonaws.com/nwjs/sample/react-app.zip
https://s3-us-west-2.amazonaws.com/nwjs/sample/react-devtools.zip

Unpack them, download the SDK build and run it with: nw.exe --load-extension=<path/to/devtools>  <path/to/app/folder>

The app is a simple react app with 'package.json' added. The devtools files are from the Chrome browser's extension folder of official react devtools extension installed from Chrome Web store.  Only the manifest file is modified to add the permission:  "chrome-extension://*".

In theory the AngularJS devtools extension and the cerebral debugger extension should be supported now. But I didn't test them, please try it and give feedback.

**Comment by rogerwang** [comment]
close as it's been supported.
