### ISSUE TITLE
Suggestion: Provide better documentation/distribution package and others

### ISSUE THREAD

**Issue by xcmaya** [nwjs/nw.js#6139]
NW is a great project. However, jumping start in the NW is not easy due to many small issues and bad documentation. Here are some my suggestions and hope it helps.

1: Provide SDK version only. Providing a normal version and an SDK version is confusing for beginners. And some people will often encounter issues like why devTool cannot show up. Anyway, most of users might need a full version only. Please keep it simple!

2: Provide a better sample project in the Github so that people can do 'git clone' and run the 'hello world' project within 3 seconds!

3: Make the 'hello world' project work on all platforms! Otherwise it is very frustrating to find out the 'hello world' sample cannot run properly. 

4: Make the documentation better! Not only the small details, but also the whole documentation system so that it is user-friendly.

5: Try to get more funding from some big company users so that it is easy to recruit some people to improve the product and manage the project.

**Comment by kailniris** [comment]
1. Is a really bad idea. There are several use cases for using the normal version instead of sdk version.
5. Nw.js is sponsored by intel. 

6. Add docs for "How to create a desktop shortcut for and nw.js app on ubuntu".

The docs are not so terrible but could use some tweaking at some points. I think most of the time users have issues with more advanced features then basic one. Check out the google group, you can rarely see basic questions there.

**Comment by xcmaya** [comment]
Intel's core business may not be closely related to NW, but some big companies are heavily depending on NW. Try to get more resource from those companies!
