### ISSUE TITLE
`toolbar` flag in package.json doesn't work

### ISSUE THREAD

**Issue by xcmaya** [nwjs/nw.js#6159]
======== TEMPLATE BUG FORM ========

NWJS Version : 0.25
Operating System : macOS 10.12.6

### Expected behavior

According to the document https://github.com/nwjs/nw.js/wiki/manifest-format#toolbar, the `toolbar` in the package.json can control to show Navigation toolbar or not.

### Actual behavior

However, this flag doesn't work on my computer.

### How to reproduce
1. Put `"toolbar": true` or  `"toolbar": false` in the package.json;
2. Launch an NW.js app. I cannot see any difference.

Thank you.

**Comment by rogerwang** [comment]
This is deprecated since 0.13. We also make official documentation to docs.nwjs.io. The wiki is community maintained knowledge base.

**Comment by xcmaya** [comment]
Then please delete or update the outdated wiki. It's confusing. :)

**Comment by joeyoropesa-dev** [comment]
Why traditional menu with right click mouse is not supported and depreciated. Why NW.js decided this and what is the solution for us. Is this because of security issues? Electron still supports it but it have limited support for chrome extensions (for example some adblock addons cannot be loaded and so on..)

So if someone wants to use NW.js for making apps that are server-side, they cannot have menu? There is server-side apps that requires native right click menu to function and also needs native back button to function properly.

So is now NW.js limited to only client-side apps? No more server-side apps?
