### ISSUE TITLE
NW.js with PHP support?

### ISSUE THREAD

**Issue by FjicdeiwFeiej** [nwjs/nw.js#6193]
Let's face it: I, and many others, know PHP well, but we don't know Node.js. We have zero desire to re-learn everything from scratch. Would it be doable to support PHP in NW.js, perhaps as a separate build as to not bloat everyone's NW.js?

It would sure be mighty swell to be able to make a stand-alone "PHP app" like this. It would be really cool, in fact, and I hope you'll seriously consider it, if it's technically feasible to "embed" PHP like this, instead of Node.js, or together with Node.js.

**Comment by rogerwang** [comment]
php support would be in another project or binary distribution.

**Comment by FjicdeiwFeiej** [comment]
So it's not gonna happen, then? :/

**Comment by ClementNerma** [comment]
@FjicdeiwFeiej The problem is that PHP is a language designed for server-side programming, but not JavaScript. So it would be complicated to make a PHP module for NW.js.

In addition to this, it would need to make a full PHP API or a PHP to JavaScript transpiler, because of course V8 engine can't run it.

**Comment by FjicdeiwFeiej** [comment]
Can't it be embedded to run inside NW.js just as if it contained a local webserver?

**Comment by ClementNerma** [comment]
No. Because even if a local webserver could integrate a PHP interpreter (like NW.js is bundling V8 engine for JavaScript) PHP could not interact with the Node.js API, which is made for JavaScript only.
Using PHP in NW.js would require to make a full API in PHP, which would be complicated - and only a few users will want it.

When I started in JavaScript, I was developping in PHP with CakePHP and my home-made frameworks/libraries, and because I loved PHP I wanted to developp my own client web and desktop apps with PHP, but this was not possible. And with time, I now love JavaScript as much as PHP (if not more). What I'm trying to say, is that JavaScript is a great language too that has a lot of features PHP doesn't have, and trying to use PHP for a domain it definitely wasn't designed for is not a good option. It's like you say "Hey, let's use Scala to make our next AAA game !" or "Why can't we developp client web apps in Java ?" - It's just because they weren't design for that purpose.

**Comment by tekrat** [comment]
Yes but not the way you want.  You could use 'node-php' (https://www.npmjs.com/package/node-php) which just pipes out a set of environmental paramaters to PHP that has to already be installed on machine.  As ClementNerma said PHP is meant to be a server side only lanuage. 'node-php' just emulates a server layer.

I think what you are looking for is:

- https://www.exeoutput.com/
- http://www.byterun.com/website-compiler.php
- http://www.roadsend.com/

**Comment by FjicdeiwFeiej** [comment]
As for "learning JavaScript", I actually know JS pretty well, but I've always used it (almost) only for client-side stuff and a different "realm", if you understand what I mean. Having to relearn stuff sucks.

As for any solution that requires PHP to be already installed or anything like that, it's worthless. Sorry, but it has to be 100% invisible to the user and fully embedded into a single EXE that they double-click to run. Nothing whatsoever that needs to be installed or fiddled about with.

**Comment by FjicdeiwFeiej** [comment]
tekrat: Sadly, the two first of those are payware, and the third is an officially dead project.

**Comment by tekrat** [comment]
One final thought: What about Enigma Virtual Box?  There an old turnorial on doing what you want to do for NW.JS.  You should be able to setup a micro webserver to do what you want.

Old instruction about 2/3 of way down the page:

https://github.com/nwjs/nw.js/wiki/How-to-package-and-distribute-your-apps

WAMP Server: http://www.uniformserver.com/

**Comment by rogerwang** [comment]
We have known users packaging ruby web server with NW.js app. I believe PHP can be done in similar way.
