### ISSUE TITLE
Nwjs O.S Raspberry Pi!?

### ISSUE THREAD

**Issue by EdvaldoLima** [nwjs/nw.js#6224]
Hello, my question is not whether nwjs runs on raspberry within an operating system, but if there is a possibility of launching it as an "operating system", I have spent these days thinking about this possibility and I already see many applications, is there any project in this proposal?

**Comment by tekrat** [comment]
NWJS is not sophisticated to handle all the functionality of an operating
system.  An operating system has to know how to use a processor, sound
chip, video chip, monitor the temperature of the systems, talk with USB
devices. write things to hard drives and talk with GPIO devices.  NWJS,
like any program, just sends requests to the operating system and the OS
responds as best as it can.

However it is possible to create a VERY light version of Linux and have it
launch a NWJS that would act as the UI.  Then the UI could launch more
instances of other NWJS.  That is in essence all a ChromeBook is.  Its a
modifed version fo teh Chromium broswer.  The main difference is that NWJS
uses Node JS for most of the heavy lifting where as Chromium (the core of a
ChromeBook) uses their own API.

I personally has been thinking something like an AtariBox could startup a
base version of Linux (would love to branch off of Ubuntu) and then launch
a NWJS instance.  Then it would just launch other application with
restricted user spaces. So that it could never affect the ROOT NWJS
instance *and* only read from other game's save space.  IE  Super Ultimate
Game Ace 2 could only import character states from Super Ultimate Game Ace
1.

**Comment by EdvaldoLima** [comment]
Thank you, clarified a lot, I'm seeing some possibilities.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
