### ISSUE TITLE
Can't download nw.js

### ISSUE THREAD

**Issue by porsager** [nwjs/nw.js#6301]
It's currently not possible to download any nw.js version.

It closes the connection after downloading only a little.

Could it be the same as what happened here:  https://github.com/nwjs/nw.js/issues/6104 ?

**Comment by rogerwang** [comment]
Could you please find what IP address 'dl.nwjs.io' resolves to on your side?

**Comment by porsager** [comment]
Sure :)

It's 34.206.150.92

**Comment by rogerwang** [comment]
Thanks I'll fix that mirror. Before that please use dl1.nwjs.io or
dl8.nwjs.io as workaround.

On Nov 21, 2017 5:00 PM, "Rasmus Porsager" <notifications@github.com> wrote:

Sure :)

It's 34.206.150.92

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/nwjs/nw.js/issues/6301#issuecomment-345959925>, or mute
the thread

**Comment by porsager** [comment]
Thanks a lot for the quick response roger !

dl8.nwjs.io is downloading currently, but dl1.nwjs.io appeared to have the same issue.

**Comment by rogerwang** [comment]
What's the URL you are using with dl1?

**Comment by porsager** [comment]
Sorry I edited the comment above just after posting, it was dl1 working and dl8 not working.

This is the url http://dl8.nwjs.io/v0.26.6/nwjs-sdk-v0.26.6-osx-x64.zip

**Comment by rogerwang** [comment]
All the mirrors should be fixed now.
