### ISSUE TITLE
Print to PDF leaves the Chrome print dialog set to "Save as PDF" rather than the orginally set default printer

### ISSUE THREAD

**Issue by murrah** [nwjs/nw.js#6529]
NWJS Version : SDK v0.28.3 
Operating System : Win64

### Expected behavior

The currently set default printer should remain set after a "print to pdf".

### Actual behavior

It gets set to "Save as PDF"

### How to reproduce

I print the current window html to a pdf: 

	win.print({
		pdf_path: me.pdfDestinationFile, 
		headerFooterEnabled: false
	});

If I subsequently do this to open a (non nw.js) window, the chrome print dialog opens as it should but the printer is set to "Save as PDF"

	var win = window.open();
	win.print();  

If I set it to a printer then close and re-open it stays set to the printer. And, if I then run the above print to pdf again the default reverts to "Save as PDF".

I also tried using an NW.js window (ie created with `nw.Window.open(...)' ) with the same result.

Thanks!

**Comment by Christywl** [comment]
I try Chrome M65, gets the same behavior, the print dialog always uses the printer which was used last time, not only to 'Save as PDF'. 
@rogerwang , could you please help confirm this?

**Comment by flowt-au** [comment]
I just tested this with nw.js v35.5 and it seems there is no change in behaviour.

I know I can set the printer to use in `win.print({printer:"my printer name"})` which works to set that "default" printer in the dialog box. 

However, my app allows printing to both a PDF file and a printer. As detailed above, once I print to a PDF file, when the user then selects to print to a printer, the dialog still says "Save as PDF". It does that because Chrome helpfully remembers the most recent printer that was used. 

So, if I can save the last printer selected by the user in the Chrome dialog I can then set that printer when the user next elects to print to a printer (as opposed to printing to a PDF file).

I could create a select box in my app and use `win.getPrinters(callback)` and allow the user to nominate a printer to use then remember that and set it each time. I was hoping there was a way to just remember the last printer used by the Chrome dialog then ignore the "Save to PDF" printer and remember any other printer used to set as the default when they next click to print to a printer.

Is this possible now? I couldn't find any reference or API options.

Thanks,
Murray
