### ISSUE TITLE
Can't find sqlite3 modules with nw.js

### ISSUE THREAD

**Issue by LeCozLoick** [nwjs/nw.js#6552]
NWJS Version : 0.21.6
Node v7.9.0
Operating System : Windows 10 64x

I'm using sqlite3 and node.Js to do some request on my Sqlite Database, but when I lauch it with Nw.js I get this error : 

(PATH = path to my code)

Uncaught Error: Cannot find module 'C:\PATH\node_modules\sqlite3\lib\binding\node-webkit-v0.21.6-win32-x64\node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:494:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:522:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\PATH\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:595:32)
    at Object.Module._extensions..js (module.js:610:10)
    at Module.load (module.js:512:32)
    at tryModuleLoad (module.js:471:12)
    at Function.Module._load (module.js:463:3)

Here is the beginning of my code : 

var sqlite3 = require('sqlite3').verbose();
var file =  "DATABASE.sqlite";
var db = new sqlite3.Database(file);
...
After that I'm only using some sqlite3 functions.

Any ideas why ? Thanks

**Comment by Zuzon** [comment]
`cd node_modules/sqlite3 && npm install --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.21.6 && cd ../../`

**Comment by LeCozLoick** [comment]
I executed your command :

C:\Users\Orgalorg\Documents\GitHub\POO_S6\Tests_unitaires\PC\test_classe\node_modules\sqlite3>npm install --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.21.6 && cd ../..

But I get this error : 

> sqlite3@4.0.0 install C:\Users\Orgalorg\Documents\GitHub\POO_S6\Tests_unitaires\PC\test_classe\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp.cmd configure --fallback-to-build --module=C:\Users\Orgalorg\Documents\GitHub\POO_S6\Tests_unitaires\PC\test_classe\node_modules\sqlite3\lib\binding\node-webkit-v0.21.6-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Orgalorg\Documents\GitHub\POO_S6\Tests_unitaires\PC\test_classe\node_modules\sqlite3\lib\binding\node-webkit-v0.21.6-win32-x64 --napi_version=1 --node_abi_napi=napi' (Error: spawn nw-gyp.cmd ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Orgalorg\Documents\GitHub\POO_S6\Tests_unitaires\PC\test_classe\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:77:29)
node-pre-gyp ERR! stack     at emitOne (events.js:116:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:211:7)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:372:16)
node-pre-gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
node-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:180:9)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Orgalorg\\Documents\\GitHub\\POO_S6\\Tests_unitaires\\PC\\test_classe\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Orgalorg\Documents\GitHub\POO_S6\Tests_unitaires\PC\test_classe\node_modules\sqlite3
node-pre-gyp ERR! node -v v8.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.9.0
node-pre-gyp ERR! not ok
Failed to execute 'nw-gyp.cmd configure --fallback-to-build --module=C:\Users\Orgalorg\Documents\GitHub\POO_S6\Tests_unitaires\PC\test_classe\node_modules\sqlite3\lib\binding\node-webkit-v0.21.6-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Orgalorg\Documents\GitHub\POO_S6\Tests_unitaires\PC\test_classe\node_modules\sqlite3\lib\binding\node-webkit-v0.21.6-win32-x64 --napi_version=1 --node_abi_napi=napi' (Error: spawn nw-gyp.cmd ENOENT)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Orgalorg\AppData\Roaming\npm-cache\_logs\2018-04-07T12_49_06_074Z-debug.log

**Comment by Christywl** [comment]
It works fine for me on Windows/Linux with nwjs-sdk-v0.29.3.
Steps:
1. create index.html and package.json files
2. npm install sqlite3
3. cd node_modules\sqllite3
4. npm install --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.29.3
5. start the app with nwjs

**Comment by yutent** [comment]
@LeCozLoick 你need to install vs 2015 or above...

**Comment by Christywl** [comment]
close until there is more information

**Comment by npk48** [comment]
Oki, here's what I did to make sqlite3 and typeorm work with nw.js

1. npm install --global --production windows-build-tools --vs2017
to install the build tool for windows

2. fix the stupid bug in node-gyp manually by modifying 
C:\Users<UserName>\AppData\Roaming\npm\node_modules\nw-gyp\gyp\pylib\gyp\MSVSVersion.py
line 228-246

change them to

versions = {
'2015e': VisualStudioVersion('2015',
'Visual Studio 2015',
solution_version='12.00',
project_version='14.0',
flat_sln=False,
uses_vcxproj=True,
path=path,
sdk_based=sdk_based,
default_toolset='v141'),
'2015': VisualStudioVersion('2015',
'Visual Studio 2015',
solution_version='12.00',
project_version='14.0',
flat_sln=False,
uses_vcxproj=True,
path=path,
sdk_based=sdk_based,
default_toolset='v141'),

3. First run vs2017 dev prompt then execute
npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.31.4 --msvs_version=2017
in your app folder

4. Since im using webpack&typescript, need more hacks to make it work
externals: {
    sqlite3: 'require("./node_modules/sqlite3")'
  },
add the above to webpack.config.js, so all import/require sqlite3 will be replaced with the proper require and avoid bundling it to your main bundle.

5. Make sure you only require this thing once in your app, otherwise you will get a “Module did not self-register” error.
or if you want you can drop more code in externals: { sqlite3. to proper check it only import once, but then it will be too hackish.

I just can't believe there's so many tricks you have to do just to make sqlite work.

**Comment by LeCozLoick** [comment]
I opted for a different solution in the end, but thank you for your answers.

**Comment by ifdandy** [comment]
> 最后，我选择了其他解决方案，但感谢您的回答。

请问如何在nwjs里面使用sqlite数据库？

**Comment by rogerwang** [comment]
> > 最后，我选择了其他解决方案，但感谢您的回答。
> 
> 请问如何在nwjs里面使用sqlite数据库？

please use English only in this project so all users can read.

**Comment by Kalmon** [comment]
Thanks @Zuzon, quick manual for Sqlite3 on NWJs.

Install VISUAL STUDIO INSTALLER 2017.
Tab -> Individual Components
[X] Visual Studio C++ Core Features
[X] VC++ 2017 version 15.9 v14.16 latest v141 tools
[X] Windows Universal CRT SDK
INSTALL

Python 2.7.5
Download and install, don't forget to activate as variables.

CMD ->
cd node_modules/sqlite3
npm install --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.66.1 --msvs_version=2017

CONGRATULATIONS!

**Comment by MAMMOL** [comment]
> Al final opté por una solución diferente, pero gracias por sus respuestas.

¿Puedes compartir la otra opción o el proyecto? Saludos :)
