### ISSUE TITLE
Window is not resized by setting width/height when resizable was set to false on Linux

### ISSUE THREAD

**Issue by slibychyby** [nwjs/nw.js#6593]
NWJS Version : v0.30.2
Operating System : Ubuntu 16.04.4 LTS

### Expected behavior

When you click on the button, the window should be resized (height and width are swapped).

### Actual behavior

When you click on the button, the window is not resized.

### How to reproduce

```json
{
  "name": "test",
  "main": "index.html",
  "window": {
    "height": 600,
    "width": 300
  }
}
```

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Hi</title>
  </head>
  <body style="width: 100%; height: 100%;">
    <script>
      nw.Window.get().setResizable(false)

      const resize = () => {
        const newHeight = nw.Window.get().width
        const newWidth  = nw.Window.get().height

        nw.Window.get().height = newHeight
        nw.Window.get().width = newWidth
      }
    </script>
    <button onclick="resize()">Click to resize</button>
  </body>
</html>
```

**Comment by slibychyby** [comment]
works on mac and windows afaict

**Comment by Christywl** [comment]
I try this on three platforms and get the different results:
  ```
    According to the sample, the original size: width => 300, the original height => 600.
    After resize click, expected result:  width => 600, height => 300.
```
- Linux: the window isn't resized, the width is 300, the height is 600 after clicking the button(I think this is an expected behavior)
![6593-linux](https://user-images.githubusercontent.com/20039821/39857258-411e0da4-5465-11e8-9849-890b7325212f.png)
- Windows: the window size has the weak change, the width is > 300, the height is > 600.
![6593](https://user-images.githubusercontent.com/20039821/39857087-b25f3638-5464-11e8-94ea-62528a4cc229.png)
- Mac: the window is resized, the width and height changed, the width is 600, the height is 300.
![6593-mac](https://user-images.githubusercontent.com/20039821/39857411-d48cba0e-5465-11e8-99ee-9aefd4a64870.png)

**Another issue:** 
**Windows**: 
 the height and width from nw.Window.get() is not equal to the window setting in package.json.
