### ISSUE TITLE
Add APIs to support MacOS Mojave dark modes

### ISSUE THREAD

**Issue by gpetrov** [nwjs/nw.js#6819]
Please add API to detect system macOS Mojave dark modes, just like in Electron

https://github.com/electron/electron/commit/0d2a0c758353667aaf37450612585562a9ef1b55#diff-8330cc91b59f45f220fe480486215c97

It might be useful to other the other System Preferences API as well @rogerwang 

https://github.com/electron/electron/commits/master/docs/api/system-preferences.md

**Comment by theDevelopper** [comment]
dark mode support would really be great. We need an event that fires on appearance change and a way to fetch the current appearance.

**Comment by averzen** [comment]
Try this - https://github.com/sindresorhus/node-dark-mode

**Comment by averzen** [comment]
Or you just use macOS terminal command 'defaults' to read this:
defaults read -g AppleInterfaceStyle
if it dark it will return a string: "Dark"

**Comment by theDevelopper** [comment]
I tried the node-dark-mode already. It does nothing on my Mojave machine. And using the Shell won't solve the issue of changing the Appearance later on as there is no event handler listening to changes.
Also neither solve high contrast themes which are also available.

**Comment by averzen** [comment]
Ok another dirty solution, because I don't believe that API happens in near time))

- we know that macOS store it's settings in a file right after user change something.
- we can watch that file and do something when it changed
- we need to figure out the settings key names for dark mode in Mojave and for high contrast themes
- we can check this values when settings file was updated

File we need: ~/Library/Preferences/.GlobalPreferences.plist

something like this:

fs.watchFile('/Users/<user>/Library/Preferences/.GlobalPreferences.plist', async (curr, prev) => {
	// check settings values by shell command 'defaults read -g AppleInterfaceStyle'
});
