### ISSUE TITLE
when mouse move over webview, document cannot catch mousemove event

### ISSUE THREAD

**Issue by chatcan** [nwjs/nw.js#6833]
see
[demo mousemove.zip](https://github.com/nwjs/nw.js/files/2506309/mousemove.zip)
inspect background
in nw 0.24.4 when mouse move over webview, can log mousemove
but in nw 0.34.1 nothing happen

**Comment by rogerwang** [comment]
This is expected as Chromium now implements webview as iframe, with which is events are not supposed to bubble across documents: https://www.w3.org/TR/DOM-Level-2-Events/events.html#Events-flow-bubbling . See solution for this here: https://stackoverflow.com/questions/5645485/detect-mousemove-when-over-an-iframe/11865037#11865037

See also https://github.com/nwjs/nw.js/issues/6620#issuecomment-406939043

**Comment by chatcan** [comment]
could not access webview.shadowRoot.querySelector('iframe').contentWindow
![1661540352048_ pic](https://user-images.githubusercontent.com/11750641/47405252-49952980-d783-11e8-98fd-afe014b1bd99.jpg)

**Comment by rogerwang** [comment]
I think the way you are accessing webview's DOM window is not working, such as `webview.shadowRoot.querySelector('iframe').contentWindow.window`, because the web page and DOM of the webview resides in a separate process and the window object and its properties should not be accessible across process boundaries.

Consider using [webview.executeScript](https://developer.chrome.com/apps/tags/webview#method-executeScript) to inject scripts and message passing APIs to pass events back.

**Comment by gpetrov** [comment]
For everybody locking for a solution to catch mouse move or drag events on the top document and not in webviews/iframes there is a simple solution.

Just add a simple css class to your body when start dragging/hovering to all webviews/iframes with **pointer-events;none**
This will prevent them temporally from catching your events. Like:

```css
.disableAllFrames iframe, .disableAllFrames webview{
  pointer-events: none;
}
```` 

When you are done dragging - just remove the class
