### ISSUE TITLE
Update App.argv for each "open" event

### ISSUE THREAD

**Issue by elpeleq42** [nwjs/nw.js#6905]
I would like to suggest that, each time an NW.js application receives an open command, that the App.argv would be updated to receive it. This would allow for apps' user to open multiple files, or give multiple external commands thru the terminal, which is quite handy in many cases.

I know that arguments are not meant for communication to the app, but if they work as a easy/quick way to do so, why not?

EDIT: Welp i'm dumb, found a way now, sorry.

**Comment by cszucko** [comment]
@elpeleq42 Any chance you could share your solution?  I've run into the same scenario and this issue was one of the top hits on Google.

I'm currently using an approach similar to [this one from StackOverflow](https://stackoverflow.com/a/29342910/4075918) but if you discovered something more clever I'd certainly be interested since relying on `--original-process-start-time` appearing in a particular location is more brittle than I would like.
