### ISSUE TITLE
Terrible perfomance , single core cpu usage only

### ISSUE THREAD

**Issue by fg16** [nwjs/nw.js#6931]
======== TEMPLATE BUG FORM ========

NWJS Version : 0.35.2
Operating System : Win 10 V1809

### Expected behavior

nw.js using atleast 4-8 cores

### Actual behavior

It uses a single thread only making my cpu , using less than 4% CPU (20-core , 40-thread Xeon)

Any idea on how could I fix this?

**Comment by elpeleq42** [comment]
Well javascript is synchronous and single core "by default". The only way to work with more cores is changing your code to be as asynchronous as possible or try dividing the task and giving each part to a web worker.It is pretty hard to do those things, but still a lot easier than working with multiple cores in other languages.

Your problem is(most probably) either you're not doing what I said above, or a problem with your code
