### ISSUE TITLE
some sites acts strange on webview eg. www.bundesanzeiger.de 

### ISSUE THREAD

**Issue by dansachelarie** [nwjs/nw.js#6986]
Operating System : windows and linux

Accessing www.bundesanzeiger.de, searching for Microsoft and going inside a result will get an error. It reproduces only if you do the test inside an webview. If I try in a nwjs window it will work as expected. (same behavior as it has on chrome)

Any idea why?

**Comment by ffanny** [comment]
If you are referring to the console log: 
"<webview>: The load has aborted with error -3: ERR_ABORTED. --extensions::webViewEvents:293 "
![2019-02-26 00-24-32](https://user-images.githubusercontent.com/19678102/53351997-ffa09800-395c-11e9-8350-b3dbccd30140.png)

For me, this is because the redirect event is too frequent to be processed in time, and this problem does not occur when patiently waiting for the page to load. And this prompt in console does not affect the continued browsing of the webpage.

**Comment by dansachelarie** [comment]
Not really, doing a search and clicking on a result will have the next output - on chrome
![1](https://user-images.githubusercontent.com/31573257/53424898-bbf56f00-39ec-11e9-9ebf-f2ccf6e7ee13.JPG)

But on a webview inside nwjs:
![2](https://user-images.githubusercontent.com/31573257/53424940-cf083f00-39ec-11e9-8d75-ae623f10b425.JPG)

The message from the print screen said: For security reasons, your session ended. Please restart the search.

**Comment by alexnegrea** [comment]
Any updates here ? I have the same issue with same site. When I open it in webview returns the above error but in normal Window it works and displays the captcha.
