### ISSUE TITLE
Cannot read property 'getExtension' with nwjs 0.14.7

### ISSUE THREAD

**Issue by TongDaDa** [nwjs/nw.js#7013]
First, let me introduce the conditions that I was encountered and some of my thoughts.

Because of the compatibility of Windows XP, I considered using the 0.14.7 version of nwjs. but I had met these errors as below.

NWJS Version :
0.14.7

Operating System : 
WindowsXP 
4gb
i3-3240

### Expected behavior

Can run this application that including WebGL function as same as the higher version of nwjs.

Of course, I was thinking of that is unpractical, but It should be supported WebGL at least.

### Actual behavior

Cannot read property 'getExtension' of null when I used WebGL.

### How to reproduce

Opening a new window with the arg of 'https://get.webgl.org' on the 0.14.7 version of NW.

**Comment by ffanny** [comment]
OS: Windows10
With nwjs-sdk-v0.14.7-win, I used `nw.Window.open('https://get.webgl.org/');` as you said. And I can see a spinning cube.

**Comment by TongDaDa** [comment]
@ffanny

Please note that I was talking about Windows XP.

Your testification above maybe not proves that NWJS can be compatible with WebGL on Windows XP effectively.

I have also run this experimental application on my computer that installed Windows XP virtual machine, It was still as same as the above situation.

**Comment by TongDaDa** [comment]
You can imitate the XP enviroment that righting click the application and then select the compatible mode option to use the XP env run this application. you will be also encountered that situation.

**Comment by ffanny** [comment]
I tested it with nw.exe compatible with Windows Vista because there is no Windows XP option. The web page will prompt me "while your browser seems to support WebGL, it is disabled or unavailable.if possible, please ensure that you are running the latest drivers for your video card."

After looking up the information about Windows XP and WebGL, I found a way to use WebGL in chrome: add `  "chromium-args":"--enable-webgl --ignore-gpu-blacklist --allow-file-access-from-files"` in package.json.
Then I succeed to see a spinning cube.

I also noted: [GPU render & Windows XP](https://superuser.com/questions/958238/how-to-enable-webgl-on-chrome-on-xp).

**Comment by TongDaDa** [comment]
@ffanny 大兄弟，你真牛逼
