### ISSUE TITLE
0.39.0 video plays without audio?

### ISSUE THREAD

**Issue by indexofrefraction** [nwjs/nw.js#7078]
with this version my **video does not have audio** anymore
video/audio play is unlocked and plays normal on chrome/firefox/msie/safari

NWJS Version : 0.39.0
Operating System : macOS 10.12

**Comment by TheJaredWilcurt** [comment]
@indexofrefraction 

What was the last version of NW.js the video played in. If this is your first version of NW.js you've tested have you read this:

* http://docs.nwjs.io/en/latest/For%20Developers/Building%20NW.js/#enable-proprietary-codecs

**Comment by intel0753** [comment]
You may need to test whether the audio of the video is played in the Right Channel instead of being played in stereo. 
I've occurred in this issue and I am trying to solve this via changing the ffmpeg.dll in the NW.js directory. 
https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases
But currently, I don't have a problem-involved PC to test if this works, so if you can test this and have a result, please reply to me.
Thank you very much!
