### ISSUE TITLE
bug with window.resizeTo

### ISSUE THREAD

**Issue by TooBug** [nwjs/nw.js#708]
I'm new to node-webkit, so I'm not sure whether it is a bug.

The size of window is 120px*33px

![image](https://f.cloud.github.com/assets/1243593/491319/f3ec6ef2-ba15-11e2-891d-f1cb00533a95.png)

Then I resized the window size with `window.resizeTo(200,100)`:

![image](https://f.cloud.github.com/assets/1243593/491322/111775c6-ba16-11e2-8dc7-239755dc7205.png)

And then, when I want to resize it back to 120px*33px, the width works currently, but height failed, the height remains 100px:

![image](https://f.cloud.github.com/assets/1243593/491323/32928448-ba16-11e2-92e1-5c8dfcefdd4f.png)

Then I tested some cases, and found that the height of window can't be resized less than 100px.

Is this a bug? Or it's excepted that the height can't be less than 100px?

**Comment by romangetman** [comment]
Just encountered this bug. Fixed by using the native resizeTo() (from gui.Window.get) as opposed to window.resizeTo. However, some issue with 100px height still exists at least on OS X, because resizing to heights less than 100px, requires accounting for the window frame containing controls (which on OS X is 23px). i.e:
I want to resize to 120px: gui.Window.get().resizeTo(something, 120) - works fine
I want to resize to 50px: gui.Window.get().resizeTo(something, 50) - nope, window height ends up being 27px. 
Doing gui.Window.get().resizeTo(something, 50 + 23) solves the problem.
