### ISSUE TITLE
Feature Request: Load from Folder

### ISSUE THREAD

**Issue by marcgfx** [nwjs/nw.js#7154]
It would be great if NWjs could load data from folder (could be called package too), instead of from the package.nw. I have made a game using NWjs that is on Steam and to update the game I always need to update the full package. If it would load from a folder I could mostly just update the encoded javascript binary leading to much faster updates. It would also speed up production a lot, as I would not have to first zip the data.

**Comment by gpetrov** [comment]
You can already do this. Just call your folder package.nw and place all the files inside.
No need for any zipping this way. It will also load much faster as it will load directly from the folder instead of unzipping first.

See packaging option 1 at:
http://docs.nwjs.io/en/latest/For%20Users/Package%20and%20Distribute/#package-your-app

**Comment by marcgfx** [comment]
That's fantastic! Thank you!
