### ISSUE TITLE
NW2:     "show_in_taskbar": false - Doesn't work Macos 10.14.6

### ISSUE THREAD

**Issue by raguay** [nwjs/nw.js#7296]
NWJS Version : 0.43.3
Operating System : macos 10.14.6

### Expected behavior

Setting  `"show_in_taskbar": false` in the `package.json` file should stop the Dock icon from appearing.

### Actual behavior

Nothing changes. The icon still appears.

### How to reproduce

1. Create a project with `"show_in_taskbar": false,` in the package.json file.
2. Launch your project
3. Icon shows in the Dock and window switcher.

### BTW: win.setShowInTaskbar(false) crashes the program every time.

**Comment by aliblackwell** [comment]
Thank you so much @rogerwang! I love your work :)

This issue is similar to https://github.com/nwjs/nw.js/issues/6956 and https://github.com/nwjs/nw.js/issues/6678 and https://github.com/nwjs/nw.js/issues/6859

You should be able to close all of them by fixing this. I am happy to help with testing if you need it!

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
