### ISSUE TITLE
iframe with nwfaketop denies samesite cookies

### ISSUE THREAD

**Issue by gpetrov** [nwjs/nw.js#7305]
NWJS Version : 0.43.3+
Operating System : Windows 10

When using iframe with nwfaketop when fully enforcing samesite cookies (currently with  --enable-experimental-web-platform-features) - cookies are not set.

This works well with webview but not with iframe

### How to reproduce

Use the sample:

[samesite_cookies.zip](https://github.com/nwjs/nw.js/files/4026655/samesite_cookies.zip)

Included are also some php files to set the cookies with different samesite options.

When you run the sample you will see that the iframe accepts only the cookie with SameSite=None, while the webview accept all 3 types of cookies (with or without the samesite option), see the output:

![samesite_cookies_display](https://user-images.githubusercontent.com/504730/71827844-66283380-30a1-11ea-8c9c-91b32ca5bb05.png)

@rogerwang Please fix the iframe to accept the samesite cookies correctly as this will be enforced in Chrome 80

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
The nightly build for this issue is available at https://dl.nwjs.io/live-build/nw43/20200109-162000/fc4c9349a

**Comment by josh83abc** [comment]
I have a problem with this change introduced in v0.43.5.

In my app I am embedding Youtube videos (the normal way, in iframe) and I was using the flags _nwdisable_ and _nwfaketop_ just in case but since v0.43.5 video doesn't load anymore.

<iframe type="text/html" allow="autoplay" nwdisable nwfaketop width="400" height="300" src="https://www.youtube.com/embed/QYh6mYIJG2Y" frameborder="0"></iframe>

Removing _nwfaketop_ solve the issue but it breaks the previous behavior so I think it is a bug.

Let me know :)
