### ISSUE TITLE
Kiosk Mode not restricting desktop access on Mac as of node-webkit 0.4

### ISSUE THREAD

**Issue by scottgmeadows** [nwjs/nw.js#746]
In recent releases of nw, kiosk mode does not restrict the same desktop-level functionality that it did between 3.1 and 3.7.

IE: On a mac running 10.8, alt-tab, the tray menu, etc are all available even when a nw window is in kiosk mode.

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.
