### ISSUE TITLE
Using node.js 'edge' module

### ISSUE THREAD

**Issue by carlskii** [nwjs/nw.js#760]
Hi,

I'm trying to use the nodejs 'edge' module from within my node-webkit application. e.g.

```javascript
var edge = require('../node_modules/edge')
   var helloWorld = edge.func('async (input) => { return ".NET Welcomes " + input.ToString(); }');
      helloWorld('JavaScript', function (error, result) {
         if (error) throw error;
         console.log(result);
});
```
However, whenever I call it I get the following error:-

    Uncaught Error: %1 is not a valid Win32 application.
    C:\data\node_modules\edge\lib\native\win32\ia32\0.10.0\edge.node 

If I run the same code outside of node-webkit using nodejs it works OK - This also works OK:

```javascript
 var dns = require('../node_modules/native-dns')
        var question = dns.Question({
            name: 'www.google.com',
            type: 'A'
        });

        var req = dns.Request({
            question: question,
            server: { address: '8.8.8.8', port: 53, type: 'udp' },
            timeout: 1000
        });

        req.on('timeout', function () {
            console.log('Timeout in making request');
        });

        req.on('message', function (err, answer) {
            answer.answer.forEach(function (a) {
                console.log(a.address);
            });
        });

        req.on('end', function () {
            console.log('Finished processing request');
        });

        req.send();

```

Any guidance would be appreciated!

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.
