### ISSUE TITLE
Active builder/packager for NW.js?

### ISSUE THREAD

**Issue by calarin** [nwjs/nw.js#7693]
Is there an actively maintained builder/packager for NW.js?

I am using nwjs-builder-phoenix but the last update was a couple of years ago and I can no longer get the build working for latest macOS (Catalina etc), so I now only have the Windows builds working. Even that can be problematic at times.

Is anyone aware of an up to date builder or packager to help get NW.js into a distributable package on Win/macOS/linux?

**Comment by mishagin-tim** [comment]
You can try this https://github.com/charlielee/nwjs-packager

**Comment by calarin** [comment]
Thanks for the link -- this certainly looks more up to date, but it also looks like @charlielee has moved his app from NW.js to electron, so it would seem this will no longer be maintained.

NW,js is great but the building is becoming more and more of an issue and I would prefer to be coding my app than figuring out the intricacies of building something for macOS.

@mishagin-tim What do you use for building? nwjs-packager?

**Comment by mishagin-tim** [comment]
@calarin We have our custom solution for every platform. 

Hopefully, a lot of parts stays the same between each of them. Some parts like signing, packaging may vary but it depends on your needs. You can always use third-party cross-platform npm scripts for any part of your building process.

You can base your solution on existing ones. I don't think there is something you can't deal with.

**Comment by charlielee** [comment]
> NW,js is great but the building is becoming more and more of an issue and I would prefer to be coding my app than figuring out the intricacies of building something for macOS.

@calarin this is one of the main reasons I moved away from NW.js. I intend to deal with bug fixes to nwjs-packager but new functionality is likely to be limited.

Also I found the NW.js package docs to not be 100% accurate. You may wish to look through the nwjs-packager source code if you end up creating your own solution.

**Comment by t-mish** [comment]
@calarin 
Found smth interesting
https://github.com/strawbees/desktop-packager

**Comment by Jelmerro** [comment]
As someone who is experimenting with using NW.js for a project, this is holding me back from moving beyond "just trying it out". This project seems to have so many advantages compared to Electron, but if I can't ship compiled packages/installers to users because there is no maintained builder, I'll have to stick with Electron. I'm not here to demand a decent builder at once or anything like that, I just want to express my concern over the lack of a decent builder, because it seems to me like this project could really benefit from that. If I as a developer have a hard time finding up-to-date docs on how to actually do this, I don't expect the end users of projects made with NW to go through the same steps. It's troublesome that none of the suggested projects to package apps seem to support common formats such as `.exe`, `.appImage` and `.app`, let alone more specialized formats like `.rpm`, `.deb` or `.snap`. In other words, I won't be able to use NW for real projects until I discover a decent method of packaging NW apps in those formats, or even build my own tools for it. I hope that NW can make that process easier in the future, or at even provide an official packager, because else I'm suspect that many people (like me) will be hesitant of using NW for any new projects.

**Comment by Elanis** [comment]
Got the same issue, I was using nwjs-builder-phoenix, but now, it begins to have vulnerabilities in dependencies, and I can't even PR the repo to help maintain this.

I'm currently creating a comparison between multiple tools including nw.js, and this is one of the rare downside of nw.js.

**Comment by Elanis** [comment]
https://docs.nwjs.io/en/latest/For%20Users/Package%20and%20Distribute/ and https://nwjs.readthedocs.io/en/latest/For%20Users/Package%20and%20Distribute/ still reference nwjs-builder-phoenix, it should be removed as its repo has been archived for years

**Comment by ayushmxn** [comment]
@Jelmerro Agreed! That's what I'm working on next with [`nw-builder`](https://github.com/nwutils/nw-builder).
