### ISSUE TITLE
Windows Defender flags wacatac.B!ml in v0.53.0 as a trojan

### ISSUE THREAD

**Issue by bswanwick** [nwjs/nw.js#7725]
NWJS Version : nwjs-sdk-v0.53.0-win-ia32.zip
Operating System : Win 10 Pro

### Expected behavior

Unzipping the NWJS SDK should not cause Windows Defender to freak out.

### Actual behavior

Windows Defender freaks out after unzipping nwjs-sdk-v0.53.0-win-ia32.zip.  

### How to reproduce

Unzip nwjs-sdk-v0.53.0-win-ia32.zip on a Windows 10 machine with Windows Defender and wait...  After I quarantined the file, I deleted my downloads and redownloaded the nwjs-sdk-v0.53.0-win-ia32.zip SDK unzipping it a second time caused the same issue with Defender.  

Googling for the name of this Trojan appears to indicate it could be a false-positive?  Either way, I've never encountered this issue unzipping the NWJS SDK before v.0.53.0
![wacatac](https://user-images.githubusercontent.com/7740392/117480940-42dcf500-af30-11eb-96eb-ed0cc99ffb2a.png)

**Comment by bluthen** [comment]
I've found the best thing you can do is sign your product before releasing. I don't think the answer is for nwjs team to sign nwjs,  what probably is the way to go is you as a person using nwjs to sign it as part of your own app. Add an exclusion in some folder and unzip nwjs there.

Can try to submit it, maybe there is an automated way to submit, when releasing:
https://www.microsoft.com/en-us/wdsi/filesubmission

However likely there is some malware that uses nwjs and that is why it is getting flagged and so I don't know if submitting it every release would help any. I have this issue a lot using PyInstaller, because a lot of malware seems to also use PyInstaller which is a shame but trying to satisfy all virus/malware detectors seems like a waste of time IMO. You can argue if you are going to satisfy only one detector maybe it could be windows defender since it comes with windows.

**Comment by ACC-Math** [comment]
Hello,
Feedback from one of our customers whose computer malfunctioned following the use of one of our digital product created with NWJS, we noticed in the export generated with NWJS v53.0 Chromium 90 for Win32, the file _notification_helper.exe_ is detected by many antivirus as containing a Trojan.
A link to check : https://www.virustotal.com/gui/file/a45c3bfb9b0eb356fcb860a54fd900d0244f00440cc60e143236a2ea0ea283b1/detection

The version located on nwjs website [https://dl.nwjs.io/v0.53.0/](https://dl.nwjs.io/v0.53.0/) is also compromised.

There is no sign of it to be a false positive. It might be the cause of a system crash on our customer's computer.
Thanks for checking this and maybe remove it from your previous versions.
Best regards.
Math

**Comment by Jaifroid** [comment]
Do you actually use notification_helper in your builds? Our app doesn't use notifications, so I omitted it (if I remember rightly) last time I saw that warning, though I haven't seen it in recent downloads.

**Comment by ACC-Math** [comment]
I tried to delete this file and launch my project .exe file and it didn't launched.
Do you have any idea of what the purpose of "notification_helper.exe" is ?

**Comment by baconbrad** [comment]
While false positives are common by AVs due to lazy detection of malware that use NW.js and Electron the Win32 release of NW.js 53.0 is concerning. Attempting to do my own analysis on notification_helper.exe Pestudio flat out rejected the file as too malicious to process. This has not been the case with previous false positives. I do not have my test VM on this machine to safely do a more in depth check and conclusively confirm it is malicious or safe. With supply chain attacks on the rise maybe we should no longer be so quick to declare a false positive without knowing for sure.

**Comment by Spartak0s** [comment]
I see that the latest version of nw (https://dl.nwjs.io/v0.72.0/) solves the problem, so maybe the case is closed?
