### ISSUE TITLE
merge log

### ISSUE THREAD

**Issue by luuxis** [nwjs/nw.js#7859]
NWJS Version : 0.62.1-sdk-x64
Operating System : Windows 10 21h2 64 bits
hello, the logs of my application are separated in two dev-tools, and I would like to group all the logs in the main dev-tool (F12).

while searching on the internet I came across these arguments and unfortunately it does not work would it be possible to help me because there I am lost

```json 
{
    "chromium-args": "--enable-logging=stderr",
}
```

**Comment by TheJaredWilcurt** [comment]
If you want logging output in the terminal/command prompt, you can try [nwdc](https://github.com/nwutils/nwdc) (from https://nwutils.io).

Otherwise, if you just want it all in the chromium dev tools, as long as you aren't using `new_instance`, this should work:

```html
<!-- window-a.html -->
<script>
global.logToA = function () {
  window.console.log(...arguments);
}
</script>
```
```html
<!-- window-b.html -->
<script>
console.log = global.logToA;
console.log('Some message');
</script>
```

* [working example.zip](https://github.com/nwjs/nw.js/files/8548269/7859.zip)

* * *

Closing issue. If this does not answer your question, you can re-open the issue with more detail, or ask in the community chatrooms (Gitter or Discord), found at the top of https://nwutils.io or the bottom of https://nwjs.io
