### ISSUE TITLE
nwjc compression size

### ISSUE THREAD

**Issue by xthdraft** [nwjs/nw.js#7864]
I compile my minified javascript file of 336kb in both nwjc v275 and nwjc v63 (ie the current version)' In v275 I get a final binary file of 798kb. Using v63 the binary file is 578kb.  Both output files seem to run equally fast with no issues.   Has nwjc improved its compression in recent versions (if so: great),  or could there be another reason for the size difference.

**Comment by TheJaredWilcurt** [comment]
By `v275` I assume you mean NW.js `v0.27.5`, which came out in January of 2018. Yes, there have been a lot of changes since then in NW.js, Chromium, Node and V8. The snapshot is based on a copy of your file running in memory in the V8 engine. So it will be different for each OS and each version of the V8 engine.

* **nwjc fixes:**
  * https://nwjs.io/blog/v0.31.3
  * https://nwjs.io/blog/v0.32.4
  * https://nwjs.io/blog/v0.33.1
* **V8 API changed:**
  * https://nwjs.io/blog/v0.34.0-beta1
  * https://nwjs.io/blog/v0.34.0
* **V8 security fixes:**
  * https://nwjs.io/blog/v0.31.2
  * https://nwjs.io/blog/v0.33.0
  * https://nwjs.io/blog/v0.34.0
  * https://nwjs.io/blog/v0.34.3
  * https://nwjs.io/blog/v0.35.0
* **V8 new features:**
  * https://nwjs.io/blog/v0.34.1
  * https://nwjs.io/blog/v0.34.2
  * https://nwjs.io/blog/v0.35.0-beta1
  * https://nwjs.io/blog/v0.34.3
  * https://nwjs.io/blog/v0.34.4
  * https://nwjs.io/blog/v0.34.5
  * https://nwjs.io/blog/v0.35.0
  * https://nwjs.io/blog/v0.35.1
  * https://nwjs.io/blog/v0.35.2
  * https://nwjs.io/blog/v0.35.3
  * https://nwjs.io/blog/v0.35.4
  * https://nwjs.io/blog/v0.35.5
  * https://nwjs.io/blog/v0.36.0-beta1
  * https://nwjs.io/blog/v0.36.0
  * https://nwjs.io/blog/v0.36.1
  * https://nwjs.io/blog/v0.36.2
  * https://nwjs.io/blog/v0.36.3
  * https://nwjs.io/blog/v0.36.4
  * https://nwjs.io/blog/v0.37.0-beta1
  * https://nwjs.io/blog/v0.37.0
  * https://nwjs.io/blog/v0.37.1
  * https://nwjs.io/blog/v0.37.2
  * https://nwjs.io/blog/v0.37.3
  * https://nwjs.io/blog/v0.37.4
  * https://nwjs.io/blog/v0.38.0-beta1
  * https://nwjs.io/blog/v0.38.0
  * https://nwjs.io/blog/v0.38.1
  * https://nwjs.io/blog/v0.38.2
  * https://nwjs.io/blog/v0.38.3
  * https://nwjs.io/blog/v0.38.4
  * https://nwjs.io/blog/v0.40.0-beta1
  * https://nwjs.io/blog/v0.40.0
  * https://nwjs.io/blog/v0.40.1
  * https://nwjs.io/blog/v0.40.2
  * https://nwjs.io/blog/v0.41.0-beta1
  * https://nwjs.io/blog/v0.41.0
  * https://nwjs.io/blog/v0.41.1
  * https://nwjs.io/blog/v0.41.2
  * https://nwjs.io/blog/v0.41.3
  * https://nwjs.io/blog/v0.42.0-beta1
  * https://nwjs.io/blog/v0.42.0
  * https://nwjs.io/blog/v0.42.1
  * https://nwjs.io/blog/v0.42.2
  * https://nwjs.io/blog/v0.42.3
  * https://nwjs.io/blog/v0.42.4
  * https://nwjs.io/blog/v0.42.5
  * https://nwjs.io/blog/v0.42.6
  * https://nwjs.io/blog/v0.44.0-beta1
  * https://nwjs.io/blog/v0.44.0
  * https://nwjs.io/blog/v0.44.1
  * https://nwjs.io/blog/v0.44.2
  * https://nwjs.io/blog/v0.44.3
  * https://nwjs.io/blog/v0.44.4
  * https://nwjs.io/blog/v0.44.5
  * https://nwjs.io/blog/v0.44.6

**Comment by xthdraft** [comment]
Thanks for that. Noted.
