### ISSUE TITLE
possible to integrate with golang and hard to assembly 

### ISSUE THREAD

**Issue by passerbyo** [nwjs/nw.js#7918]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version :
Operating System :

### Expected behavior

<!- What do you think should happen? ->

### Actual behavior

<!- What actually happens? ->

### How to reproduce

<!- 

- Detail a step by step guide to reproduce the issue
- A copy of your code would help. Include: JS, HTML. 
- If you have a crash report, copy it in. 
- Test your steps on a fresh environment to see if you still have an issue
- Post!

->

**Comment by TheJaredWilcurt** [comment]
There are some Go specific alternatives to NW.js available, if that's what you are looking for:

* https://xpda.net/?filter=additive&languages=%5B%22Go%22%5D

Otherwise, you could write a CLI tool with GO, compile it to a native binary (.exe), and use Node to run that as a child process, and Chromium as the GUI.

Closing this. Feel free to create a new issue and fill out the description if you have something more specific to report/ask.
