### ISSUE TITLE
Why nw unpack the exe file everytime when running it?

### ISSUE THREAD

**Issue by oklai** [nwjs/nw.js#815]
The nw app start slowly, and I found it will unpack exe file every time when run the app. Why need to doing this, every time after decompression file are the same.
It should be unpack only once, when the app is updated to unpack again.

Here is my temp folder, too scary:
![screenshot](http://ww4.sinaimg.cn/mw690/6fb2c1e4gw1e61g46p9akj20d40k541e.jpg)

**Comment by tunderdomb** [comment]
Did the question in the issue got answered? I've been searching for answers why nw needs to unpack packaged apps into a temp dir but haven't find anything. 
It'd also be nice to point this behavior out in the docs more clearly; 
since It's not a great experience to discover it well into development, after packaging or near distribution.

So again, why nw needs to unpack files on every startup? 
And what if I don't want my files to be exposed in any way?
Packaged apps gets unpacked -> exposed. 
Unpackaged apps have the source code in a nice tree distributed with nw.exe -> exposed.
Also: Enigma Virtual Box is for Windows only.

**Comment by Mior** [comment]
@tunderdomb :+1: 
It would be great if nw.js have option to specify unpacking location. I have project using local sqlite db and when unpacked into different location every time I'm not able to persist any data. I come up with workaround described here https://github.com/nwjs/nw-builder/issues/273#issuecomment-161963651 but having it supported in nw.js's packed distribution (`app.nw` or bundled with `nw.exe`) would be nice.
