### ISSUE TITLE
Flash plugin bundle

### ISSUE THREAD

**Issue by Aeal** [nwjs/nw.js#942]
Hello, I just found node-webkit and so far I am really liking it. However I have reached a point where I want to bundle my app with some plugins pre-installed, namely flash, I read on the wiki that you place the plugin in the /app/plugins folder but it does not say what to include nor how to include it. right now i placed the pepflashplayer.dll in the /plugins folder along with its manifest file and I also tried to have it in the folder like it is in the chrome install directory but that did not work either. Is there some other file that I need to include or additional options I need to have in the package.json file? Thanks!

**Comment by DogsForArms** [comment]
@yss did you say that you can run pepflashplayer.dll  in nodewebkit?

**Comment by RandyMustache** [comment]
Hi, I know this is an old thread based on an old version. I need the NPAPI flash plug-in for my app, so I am forced to use an older version of NWJS (unless someone has some actual answers on using flash workers in the pepper flash player in NW 13+).

I was wondering if there was any way to force NW to use the /plugins folder for the Flash dll. If flash is installed on a User's system, NW will default to that, if it isn't, it uses the /plugins folder. I want it to always use the /plugins folder.

**Comment by johnwclark** [comment]
You need to have one installed for your webkit install.  Think of it just like any other browser, they each need the plugin for it to work, there are no system globals.

The only way I ever got this to work was to copy the DLL from IE into the plugins folder, and then setup the plugins in the config.

**Comment by sourceskyboxer** [comment]
Why not use ppapi version of flash player because he.exe has chrome drive. You can try to use pepper flash plugin. Npapi version can not work good. Thanks

**Comment by RandyMustache** [comment]
Thanks @johnwclark , I have solved the problem using Chromuim args to prevent any plugins from loading except the version of NPAPI flash I need. Works flawlessly now, and recognises my flash permissions file.

@sourceskyboxer, I can't use the Pepper flash player as I am finding it impossible to get custom flash permission files working within it. I am unable to find any resources helping, and the crucial NW-Flash-Trust API doesn't seem to work at all with the Pepper flash player (despite working with pepper in Electron). If you have any answers to my issue, I am all ears. It's very important my app uses an internal copy of flash (shipped with app), as well as internally writing it's own trust file for flash. 

Thank you both for replying :)

**Comment by sourceskyboxer** [comment]
Hello my dear @RandyMustache , I suggest you try electron with pepper flash plugin. Don't forget about current architectures ( ia32 / x64 )

If you can't get working with nw.exe than you can move to electron because I saw many many developers use only electron because electron is safer than nw.exe because nw.exe always extract to temp directory.

If you want know - how do you try?
If you make sure for directory of electron
root: = /
electron.exe
.. ( all pak, dll and dat files )
resources/app/ <- root directory of content ( html, css, js )
plugin like pepper flash player in /

than you make sure with Engima Virtual Box ( Embedded resources/app/ and pepperflash.dll into electron.exe to electron_boxed.exe )
Rename your own application name example electron_boxed.exe to your-application.exe and release your own application.
